<%@ Page Language="VB" AutoEventWireup="false" EnableViewState="True" CodeFile="docrepomod.aspx.vb" Inherits="docrepomod_class" %>

<%@ Register Src="~/UserControls/DatePicker.ascx" TagPrefix="uc" TagName="DatePicker" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <!--Generated by ViSoftLabs Forms Generator (http:// www.vifeandi.net)-->
    <meta charset="utf-8">
    <title></title>
    <!--#include File="../../topinitdetail.aspx"-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <script>
        $(function () {
            $("input[type=submit], button")
            .button()
            var div1 = $("#divnavi").accordion({ collapsible: false, heightStyle: "content", active: 0 });
            var div2 = $("#divsearch").accordion({ collapsible: false, heightStyle: "content", active: 0 });
            var div3 = $("#divdata");
            div1.show();
            div3.show();
        });
    </script>
    <!--#include File="../../topscriptdetail.aspx"-->
</head>
<body>
    <form id="frmform" runat="server">
        <!--#include File="../../include/FormHeader1.aspx"-->

        <div class=" container-fluid bg-light" style="font-size: 1rem;">
            <div class="row listpage">
                <div class="col-md-2 bg-light ">

                    <div style="padding-top: 1em; font-size: 0.8rem; text-align: left;">
                        <div style="text-align: left">
                            <asp:Button ID="btnadd" CssClass="btn btn-sm btn-info w-100" Text="Add Document" runat="server" OnClick="redirecttonext" Style="width: 160px" /><br />
                            <br />
                            <asp:Button ID="btnback" CssClass="btn btn-sm btn-info w-100" Text="<< Back" runat="server" OnClick="backpage2" Style="width: 160px" CausesValidation="false" />
                            <br />
                            <b>Messages:</b><br />
                            <asp:Label ID="lblMessage" runat="server" class="cssrequired"></asp:Label>
                            <br />
                        </div>
                    </div>
                    <div style="text-align: left; display:none;">
                        <b>Please enter search key:</b><br />
                        <asp:TextBox ID="search_key1" runat="server" Columns="23" MaxLength="50"></asp:TextBox><br />
                        Search Field:<br />
                        <asp:PlaceHolder ID="phSearchFields" runat="server"></asp:PlaceHolder>
                        <br />
                        <hr class="cssdivider" width="100%" runat="server" id="hrdate" />
                        <br />
                        <uc:datepicker ID="uc_from" runat="server" AllowNull="false" Width="72px" PlaceHolder="From Date" />
                        <uc:datepicker ID="uc_to" runat="server" AllowNull="false" Width="72px" PlaceHolder="To Date" />
                        <asp:PlaceHolder ID="phSearchDate" runat="server"></asp:PlaceHolder>
                        <br />
                        <asp:Button ID="btnsearch" CssClass="btn btn-info btn-sm w-100" Text="Search" runat="server" OnClick="SearchStr" Style="width: 150px" />
                    </div>

                </div>
                <div class="col-md-10 bg-white">
                    <asp:Literal ID="filterhead" runat="server"></asp:Literal>
                    <div style="padding-top: 1em;">

                        <div class="ui-widget-header alert p-1 form-fonts w-100  bg-header " role="alert" style="text-align: left; padding-left: 1em!important; margin-bottom: 1em!important">
                            <span runat="server" id="nmtitle"></span>
                        </div>

                    </div>

                    <table id="table_listing" width="100%" cellpadding="5" cellspacing="0">
                        <asp:Repeater ID="rep" runat="server" OnItemCommand="rep_ItemCommand">
                            <ItemTemplate>

                                <tr id="trRow" class="ui-widget-content" runat="server">
                                    <td align="center" class="cssdetail" width="48px" style="border-bottom: solid 1px silver" valign="top">
                                        <asp:Literal ID="litimage" runat="server"></asp:Literal>
                                    </td>
                                    <td class="cssdetail" style="border-bottom: solid 1px silver">
                                        <asp:Literal ID="litData" runat="server"></asp:Literal>
                                        <br />
                                        <asp:LinkButton ID="lnkEdit" runat="server" CommandArgument='<%#DataBinder.Eval(Container.DataItem, "doc_id")%>' CommandName="Edit">Edit</asp:LinkButton>
                                        <asp:Literal ID="litSepDel" runat="server">|</asp:Literal>
                                        <asp:LinkButton ID="lnkDelete" runat="server" CommandArgument='<%#DataBinder.Eval(Container.DataItem, "doc_id")%>' CommandName="Del" OnClientClick="return confirm('Are you sure want to delete this record?')">Del.</asp:LinkButton>

                                    </td>
                                </tr>

                            </ItemTemplate>
                        </asp:Repeater>
                        <tr class="ui-widget-header">
                            <td colspan="<%=columnscount%>" align="center" class="cssdetail" style="height: 20px">
                                <asp:Label ID="lblCurrentPage" Visible="false" runat="server"></asp:Label></td>
                        </tr>
                    </table>

                </div>

            </div>

        </div>

        <input type="hidden" runat="server" id="mode" name="mode" />
        <input type="hidden" runat="server" id="rid" name="rid" />
        <input type="hidden" runat="server" id="bid" name="bid" />
        <input type="hidden" runat="server" id="da" name="da" />
        <!--#include File="../../include/FormFooter1.aspx"-->
        <hr width="100%" />
    </form>
        <!--#include File="../../include/footerscript.aspx"-->
</body>
</html>




