Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.OleDb
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls
Partial Public Class docrepomod_class
    Inherits listpage
    'Generated by VI FEANDI SOFTLABS FORM GENERATOR (http://www.vifeandi.net) VER 2014.1
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        _searchkeystr = ""
        listingpage = ""
        _FormsName = "Document Repository"
        'columnscount = "10"
        TableName = ""
        DetailPage = "docdocmod.aspx"
        IDPField = ""
        IDField = "dg_id"
        AppIDField = ""
        MerchantIDField = ""
        FilterField = ""
        '_pagesize = 20
        APPCode = "" '"SMS"
        AddRights = "" '"SM0001"
        DelRights = "" ' "SM0003"
        ModRights = "" '"SM0002"
        ViewRights = "" '"SM0004"
        FullRights = ""
        NmSpace = "docdocmod"
        pFieldNames = ""
        pJoinFields = ""
        Orderby = ""


        '        If WebLib.PrevURL.trim = "" Then
        'lblMessage.Text = "Inconsistency detected. Unable to upload document."
        'btnadd.Enabled = False
        'Exit Sub
        'End If

        If Page.IsPostBack = False Then
            da.Value = Request("da")
        End If
        Call InitLoad()
        Call loaddoc(" doc_uniqueid='" & bid.Value & "'")

        btnadd.Visible = True
    End Sub
    Private Sub loaddoc(Optional ByVal _p_searchkey As String = "")

        Dim cn As New OleDbConnection(connectionstring)

        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow

        If _p_searchkey.Trim <> "" Then
            _p_searchkey = " and " & _p_searchkey
        End If

        mode.Value = "D"
        nmtitle.InnerHtml = "Attachment"

        cn.Open()
        cmd.CommandText = "Select docdoc.*,dg_name,dg_id from docdoc left outer join docgroup on doc_group = dg_id where isnull(doc_group,0) = -1 " & _p_searchkey & " order by doc_subject"

        cmd.Connection = cn
        ad.SelectCommand = cmd
        ad.Fill(ds, "datarecords")
        Dim dt As DataTable = ds.Tables("datarecords")
        Dim dv As New DataView(dt)
        Dim pgitems As New PagedDataSource()
        pgitems.DataSource = dv

        rep.DataSource = pgitems
        rep.DataBind()

    End Sub
    Protected Sub rep_ItemCommand(ByVal source As Object, ByVal e As System.Web.UI.WebControls.RepeaterCommandEventArgs)

        If e.CommandName = "Edit" Then
            Response.Redirect("postpage.aspx?NextPage=" & DetailPage & "&ga=" & e.CommandArgument & "&ba=" & bid.Value)
        End If
        If e.CommandName = "Del" Then

            If FileExistsOrNot(e.CommandArgument) Then
                lblMessage.Text = "Please delete the file before deleting the record"
                Exit Sub
            End If
            Call DeletetheRec(e.CommandArgument)
        End If
    End Sub

    Protected Sub rep_ItemDataBound(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.RepeaterItemEventArgs) Handles rep.ItemDataBound

        Dim drv As DataRowView
        drv = e.Item.DataItem

        Dim objdata As Literal = e.Item.FindControl("litData")

        If objdata Is Nothing Then
            Exit Sub
        End If

        objdata.Visible = True

        Dim lhead As String = ""
        If drv.Row("doc_attach1").ToString.Trim <> "" Then
            lhead = "" & drv.Row("doc_subject").ToString.Trim & ""
        Else
            lhead = "<b>" & drv.Row("doc_subject").ToString.Trim & "</b>"
        End If
        objdata.Text = lhead & "<br><font color=""gray"">" & drv.Row("doc_details").ToString.Trim & "<br>Uploaded On: " & drv.Row("doc_createdt").ToString.Trim & " by " & drv.Row("doc_createby").ToString.Trim & "</font>"
        objdata = e.Item.FindControl("litimage")
        Dim obj As New clsFileTypes
        obj.InitFile(drv.Row("doc_attach1").ToString.Trim)
        If Not objdata Is Nothing Then
            objdata.Text = "<img src=""" & WebLib.ClientURL(obj.FileImageFile) & """ width=""64"">"
        End If
        obj = Nothing


    End Sub
    Public Sub redirecttonext(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Response.Redirect("postpage.aspx?NextPage=docdocmod.aspx&da=" & da.Value & " &ba=" & bid.Value)
    End Sub
    Public Sub backpage2(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Dim lid As String = ViFeandi.General.GetValue(connectionstring, "workflowstatus", "wst_module", "wst_ucode", "'" & bid.Value & "'", "", WebLib.MerchantID, "", WebLib.FilterCode)
        Dim lURL As String = ""

        If WebLib.isStaff = False Then
            ' customer, click back button 
            If lid = "zcustom_ccr" Or lid = "zcustom_ccrp" Or lid = "zcustom_ccrs" Or lid = "zcustom_ccrc" Then
                lid = "zcustom_ccrc"
            End If
        End If

        lURL = Redirector.Redirect(lid, bid.Value) & ""
        If lURL.Trim = "" Then
            Response.Redirect("~/main.aspx")
        Else
            Response.Redirect("~/" & lURL)
        End If
    End Sub

    Public Sub DeletetheRec(ByVal pID As String)
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()

        If IsNumeric(pID) = False Then
            lblMessage.Text = "Nothing to delete"
            Exit Sub
        End If

        Try
            cn.Open()
            cmd.CommandText = "Delete from docdoc where doc_id=" & pID & " and doc_uniqueid='" & bid.Value & "'"
            cmd.Connection = cn
            cmd.ExecuteNonQuery()
            cn.Close()
            cmd.Dispose()
            cn.Dispose()
            lblMessage.Text = ""
            Call loaddoc(" doc_uniqueid='" & bid.Value & "'")


        Catch ex As Exception
            lblMessage.Text = ex.Message
        End Try
    End Sub

    Public Function FileExistsOrNot(ByVal pID As String) As Boolean
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow

        Dim lFileName As String = ""

        If IsNumeric(pID) = False Then
            Return True
            Exit Function
        End If

        Try
            cmd.CommandText = "Select doc_attach1 from docdoc where doc_id=" & pID
            cmd.Connection = cn
            ad.SelectCommand = cmd
            ad.Fill(ds, "datarecords")
            For Each dr In ds.Tables("datarecords").Rows
                counter = counter + 1
                lFileName = dr("doc_attach1") & ""
                Exit For
            Next
            cn.Close()
            cmd.Dispose()
            cn.Dispose()

            If (lFileName).Trim <> "" Then
                Return True
            Else
                Return False
            End If



        Catch ex As Exception
            lblMessage.Text = ex.Message
            Return True
        End Try
    End Function

End Class

