Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.OleDb
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls

Partial Public Class ceval_class
    Inherits detailspage
    Private FORMCODE As String = "CEVAL"  'Hardcoded for customised form
    Private f_custype As String = "1|New;;2|Review"
    Private f_yesno As String = "No|No;;Yes|Yes, Please elaborate"
    Private f_custgroup As String = "1|Distributor;;2|Ready Mix;;3|Industrial User;;4|Project;;5|Retail;;6|International"

    Private _l_format As String = "###,###,##0"

    'Generated by VI FEANDI SOFTLABS FORM GENERATOR (http://www.vifeandi.net) VER 2014.1

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        listingpage = "wlist.aspx"
        _FormsName = "CREDIT EVALUATION FORM"
        TableName = "[zcustom_ceval]"
        IDPField = ""
        IDField = "cus_id"
        AppIDField = ""
        MerchantIDField = "cus_merchantid"
        FilterField = "cus_filter"
        APPCode = "WORKFLOW"
        AddRights = ""
        DelRights = ""
        ModRights = ""
        ViewRights = ""
        FullRights = "CV0005"
        NmSpace = "zcustom_ceval"

        cus_remarks6.Visible = False

        Call validationgroup()
        wfb_bar.workflownamespace = NmSpace
        wfb_bar.custommode = True
        wfb_bar.overridemode = True
        wfb_bar.attachmentbycreatoronly = True

        If Page.IsPostBack = False Then
            lblrefno.Text = "<b>Auto Generated</b>"
            cus_refno.Text = Request("rc") & ""
            WebLib.SetListItems(cus_custype, f_custype)
            WebLib.SetListItems(cus_cusgroup, f_custgroup)
            WebLib.SetListItems(cus_groupexposure, f_yesno)
            WebLib.SetListItems(legalbackcruptcy, f_yesno)
            WebLib.SetListItems(legalwind, f_yesno)

            If (Request("wp2") & "").Trim <> "" Then '2 always use for custcode
                Dim obj As New RuntimeCustomer
                Call obj.getInfo((Request("wp2") & "").Trim)
                ccode.Value = (Request("wp2") & "").Trim
                cus_company.Text = obj.CustName & ""
            End If

            cus_accountholder.DataSource = backend.GetAccountHolders(WebLib.LoginUserCompanySelected)
            cus_accountholder.DataValueField = "salesrepcode"
            cus_accountholder.DataTextField = "usr_name"
            cus_accountholder.DataBind()
            cus_accountholder.Items.Insert(0, New ListItem("Please Select", ""))
        End If

        createdt.Value = DateTime.Now
        cus_refno.ReadOnly = True

        Call InitLoad()
        Call enabledisablecustomer()
        Call validationgroup()

        wfb_bar.parentobj = mp

        Call assigninitvalues()

        If (wfb_bar.canAction()) Then
            lvlvalid.Value = "True"
        Else
            lvlvalid.Value = "False"
        End If

        If (wfb_bar.statusGet().tolower = "pending" Or wfb_bar.statusGet().tolower = "") And (WebLib.LoginIsFullAdmin = True Or WebLib.hasrights("zcustom_ceval_rfresh", "WORKFLOW", "CVF0005")) Then
        Else
            btnRefreshAnalysis.Visible = False
        End If

        cus_remarks.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"

        If wfb_bar.wlevelAget() <> "" Then
            If wfb_bar.wlevelAget() <= 4 Then
                cus_remarks.CssClass = "validate[required]"
            End If
            If wfb_bar.wlevelAget() = 3 Then
                cus_custype.ValidationGroup = "3-"
                cus_cusgroup.ValidationGroup = "3-"
                cus_company.ValidationGroup = "3-"
                cus_remarks1.ValidationGroup = "3-"
                cus_remarks2.ValidationGroup = "3-"
                cus_remarks3.ValidationGroup = "3-"

                Call InitLoad()
            End If
        End If

        If (WebLib.LoginIsFullAdmin = True And wfb_bar.Workflowended = False) Or (IsNumeric(rid.Value) = False And cus_accountholder.SelectedValue = "") Then
            cus_accountholder.Enabled = True
        Else
            cus_accountholder.Enabled = False
        End If

        loadpr()
    End Sub

    Private Sub validationgroup()
        ' find tagging if new, else find old 
        If rid.Value = "" Then

            Dim lvl As Integer = 0
            lvl = getlvl(2)

            cus_remarks1.ValidationGroup = lvl & "-"
            cus_remarks2.ValidationGroup = lvl & "-"
            cus_remarks3.ValidationGroup = lvl & "-"

            lvl = getlvl(3)
            cus_remarks4.ValidationGroup = lvl & "-"
            cus_remarks5.ValidationGroup = lvl & "-"

            cus_remarks6.ValidationGroup = lvl & "-"
            cus_remarks7.ValidationGroup = lvl & "-"
            cus_remarks8.ValidationGroup = lvl & "-"
            cus_remarks9.ValidationGroup = lvl & "-"
            cus_remarks10.ValidationGroup = lvl & "-"

            cus_groupexposure.ValidationGroup = lvl & "-"
            cus_groupex10.ValidationGroup = lvl & "-"
            cus_groupex11.ValidationGroup = lvl & "-"
            cus_groupex12.ValidationGroup = lvl & "-"
            cus_groupex13.ValidationGroup = lvl & "-"

            cus_groupex20.ValidationGroup = lvl & "-"
            cus_groupex21.ValidationGroup = lvl & "-"
            cus_groupex22.ValidationGroup = lvl & "-"
            cus_groupex23.ValidationGroup = lvl & "-"

            cus_groupex30.ValidationGroup = lvl & "-"
            cus_groupex31.ValidationGroup = lvl & "-"
            cus_groupex32.ValidationGroup = lvl & "-"
            cus_groupex33.ValidationGroup = lvl & "-"

            cus_groupex40.ValidationGroup = lvl & "-"
            cus_groupex41.ValidationGroup = lvl & "-"
            cus_groupex42.ValidationGroup = lvl & "-"
            cus_groupex43.ValidationGroup = lvl & "-"

            cus_groupex50.ValidationGroup = lvl & "-"
            cus_groupex51.ValidationGroup = lvl & "-"
            cus_groupex52.ValidationGroup = lvl & "-"
            cus_groupex53.ValidationGroup = lvl & "-"

            cus_groupex60.ValidationGroup = lvl & "-"
            cus_groupex61.ValidationGroup = lvl & "-"
            cus_groupex62.ValidationGroup = lvl & "-"
            cus_groupex63.ValidationGroup = lvl & "-"

            cus_groupex70.ValidationGroup = lvl & "-"
            cus_groupex71.ValidationGroup = lvl & "-"
            cus_groupex72.ValidationGroup = lvl & "-"
            cus_groupex73.ValidationGroup = lvl & "-"

            cus_groupex80.ValidationGroup = lvl & "-"
            cus_groupex81.ValidationGroup = lvl & "-"
            cus_groupex82.ValidationGroup = lvl & "-"
            cus_groupex83.ValidationGroup = lvl & "-"

            cus_tblc1_1.ValidationGroup = lvl & "-"
            cus_tblc2_1.ValidationGroup = lvl & "-"
            cus_tblc3_1.ValidationGroup = lvl & "-"

            cus_tblc1_2.ValidationGroup = lvl & "-"
            cus_tblc2_2.ValidationGroup = lvl & "-"
            cus_tblc3_2.ValidationGroup = lvl & "-"

            cus_tblc1_3.ValidationGroup = lvl & "-"
            cus_tblc2_3.ValidationGroup = lvl & "-"
            cus_tblc3_3.ValidationGroup = lvl & "-"

            cus_tblc1_4.ValidationGroup = lvl & "-"
            cus_tblc2_4.ValidationGroup = lvl & "-"
            cus_tblc3_4.ValidationGroup = lvl & "-"

            cus_tblc1_5.ValidationGroup = lvl & "-"
            cus_tblc2_5.ValidationGroup = lvl & "-"
            cus_tblc3_5.ValidationGroup = lvl & "-"

            cus_payment1.ValidationGroup = lvl & "-"
            cus_payment2.ValidationGroup = lvl & "-"
            cus_payment3.ValidationGroup = lvl & "-"
            cus_payment4.ValidationGroup = lvl & "-"
            cus_payment5.ValidationGroup = lvl & "-"

        Else
            cus_remarks1.ValidationGroup = backend.getLevelPC(2, rid.Value, NmSpace) & "-"
            cus_remarks2.ValidationGroup = backend.getLevelPC(2, rid.Value, NmSpace) & "-"
            cus_remarks3.ValidationGroup = backend.getLevelPC(2, rid.Value, NmSpace) & "-"

            cus_remarks4.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_remarks5.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_remarks6.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_remarks7.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_remarks8.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_remarks9.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_remarks10.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_groupexposure.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex10.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex11.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex12.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex13.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_groupex20.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex21.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex22.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex23.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_groupex30.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex31.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex32.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex33.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_groupex40.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex41.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex42.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex43.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_groupex50.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex51.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex52.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex53.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_groupex60.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex61.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex62.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex63.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_groupex70.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex71.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex72.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex73.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_groupex80.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex81.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex82.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_groupex83.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_tblc1_1.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_tblc2_1.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_tblc3_1.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_tblc1_2.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_tblc2_2.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_tblc3_2.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_tblc1_3.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_tblc2_3.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_tblc3_3.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_tblc1_4.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_tblc2_4.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_tblc3_4.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"

            cus_tblc1_5.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_tblc2_5.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_tblc3_5.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"


            cus_payment1.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_payment2.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_payment3.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_payment4.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
            cus_payment5.ValidationGroup = backend.getLevelPC(3, rid.Value, NmSpace) & "-"
        End If
    End Sub

    Private Function getlvl(ByVal lvl As Integer) As Integer
        Dim str As String = "select wui_no from workflowlink l inner join workflowitems i on l.wfl_wflowid = i.wui_wid where wfl_subcode = '" + FORMCODE + "' and wui_pno = " + lvl.ToString + ""
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()

        Try
            cmd.CommandText = str
            cmd.Connection = cn
            ad.SelectCommand = cmd
            ad.Fill(ds, "datarecords")

            For Each dr As DataRow In ds.Tables("datarecords").Rows
                Return dr("wui_no") & ""
            Next

            cn.Close()
            cmd.Dispose()
            cn.Dispose()
        Catch ex As Exception
            ' lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
            Return 0
        End Try

    End Function

    Private Sub enabledisablecustomer()
        If cus_company.Enabled = True Then
            '            If cus_custype.selectedindex >= 0 Then
            'If cus_custype.SelectedItem.Value = 1 Then
            'cus_company.enabled = True
            '        Else
            '          cus_company.enabled = False

            '        End If
            '       End If
        End If
    End Sub

    Private Function cansaveitems() As Boolean
        If wfb_bar.wlevelAPget() = "3" Then
            Return True
        Else
            Return False
        End If
    End Function

    Private Function SaveItems(ByVal pucode As String) As String
        Dim lseq As Integer = 0
        Dim lcus_param1 As String = ""
        Dim lcus_param2 As String = ""
        Dim lcus_param3 As String = ""
        Dim lcus_param4 As String = ""
        Dim lcus_param5 As String = ""
        Dim lcus_param6 As String = ""
        Dim lcus_uid As String = ""
        Dim lcus_type As String = FORMCODE
        Dim lsql As String = ""
        Dim myObject As Object
        Dim myObjectdd As Object

        lsql = "Delete from zcustom_genitems where cus_uid='" & pucode & "' and cus_type='" & FORMCODE & "'"

        For Each item In rep.Items
            lseq = lseq + 1

            myObject = item.FindControl("txtparam1")
            If Not myObject Is Nothing Then
                lcus_param1 = myObject.Text
            End If

            myObject = item.FindControl("txtparam2")
            If Not myObject Is Nothing Then
                lcus_param2 = myObject.Text
            End If

            myObject = item.FindControl("txtparam3")
            If Not myObject Is Nothing Then
                lcus_param3 = myObject.Text
            End If

            myObject = item.FindControl("txtparam4")
            If Not myObject Is Nothing Then
                lcus_param4 = myObject.Text
            End If

            myObject = item.FindControl("txtparam5")
            If Not myObject Is Nothing Then
                lcus_param5 = myObject.Text
            End If

            If lcus_param1.Trim = "" Then
            Else
                lsql = lsql & ";Insert into zcustom_genitems ([cus_param1],[cus_param2],[cus_param3],[cus_param4],[cus_param5],[cus_uid],[cus_type],cus_seq) Values (" &
                "'" & lcus_param1.Replace("'", "''") & "','" & lcus_param2.Replace("'", "''") & "','" & lcus_param3.Replace("'", "''") & "','" &
                lcus_param4.Replace("'", "''") & "','" & lcus_param5.Replace("'", "''") & "','" & pucode & "','" & lcus_type & "'," & lseq & ")"
            End If
        Next

        Return lsql
    End Function

    Private Sub loadworkings()
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow

        cn.Open()
        cmd.CommandText = "Select * from zcustom_genitems where cus_uid='" & ucode.Value & "' and cus_type='" & FORMCODE & "' order by cus_seq asc"
        cmd.Connection = cn
        ad.SelectCommand = cmd
        ad.Fill(ds, "datarecords")

        Dim dt As DataTable = ds.Tables("datarecords")
        Dim dv As New DataView(dt)
        Dim lcount As Integer = dt.Rows.Count

        If lcount < 12 Then
            If cansaveitems() = True Then
                For counter = 1 To 12 - lcount
                    dr = dt.NewRow()
                    dt.Rows.Add(dr)
                Next
            Else
                'Added here for empty rows
                For counter = 1 To 12 - lcount
                    dr = dt.NewRow()
                    dt.Rows.Add(dr)
                Next
            End If
        Else
            If cansaveitems() = True Then
                dr = dt.NewRow()
                dt.Rows.Add(dr)
            End If
            'Dont need to do anutjing
        End If

        Dim pgitems As New PagedDataSource()
        pgitems.DataSource = dv
        rep.DataSource = pgitems
        rep.DataBind()

    End Sub

    Private Sub LoadCreditDetails()
        If (ccode.Value & "").Trim <> "" Then
            datats.Value = gettimestamp()
            Call assigntimestamp()

            Dim obj As New RuntimeCustomer
            Dim ds As DataSet
            Dim dr As DataRow
            Dim counter As Integer = 0
            Dim objlit As Literal
            ds = obj.GetBalanceSheetByCustomer_DS(ccode.Value, 5, DateTime.Now.Year)

            For Each dr In ds.Tables(0).Rows
                counter = counter + 1

                objlit = Page.FindControl("cus_tbl" & counter & "_1")

                If IsNumeric(dr("datayear") & "") = True Then
                    If CInt(dr("datayear") & "") <> 0 Then
                        If Not objlit Is Nothing Then
                            Try
                                objlit.Text = WebLib.formatthedate(dr("datadate"))
                            Catch ex As Exception
                            End Try
                        End If
                    Else
                        GoTo NextLine
                    End If
                Else
                    GoTo NextLine
                End If

                objlit = Page.FindControl("cus_tbl" & counter & "_2")
                If Not objlit Is Nothing Then objlit.Text = WebLib.formatthenumber(dr("currentasset") & "", "###,###,##0")

                objlit = Page.FindControl("cus_tbl" & counter & "_3")
                If Not objlit Is Nothing Then objlit.Text = WebLib.formatthenumber(dr("currentliabilities") & "", "###,###,##0")

                objlit = Page.FindControl("cus_tbl" & counter & "_4")
                If Not objlit Is Nothing Then objlit.Text = WebLib.formatthenumber(dr("nettworkingcapital") & "", "###,###,##0")

                objlit = Page.FindControl("cus_tbl" & counter & "_5")
                If Not objlit Is Nothing Then objlit.Text = WebLib.formatthenumber(dr("otherassets") & "", "###,###,##0")

                objlit = Page.FindControl("cus_tbl" & counter & "_6")
                If Not objlit Is Nothing Then objlit.Text = WebLib.formatthenumber(dr("paidupcapital") & "", "###,###,##0")

                objlit = Page.FindControl("cus_tbl" & counter & "_7")
                If Not objlit Is Nothing Then objlit.Text = WebLib.formatthenumber(dr("networth") & "", "###,###,##0")

                objlit = Page.FindControl("cus_tbl" & counter & "_8")
                If Not objlit Is Nothing Then objlit.Text = WebLib.formatthenumber(dr("longtermdebts") & "", "###,###,##0")

                objlit = Page.FindControl("cus_tbl" & counter & "_9")
                If Not objlit Is Nothing Then objlit.Text = WebLib.formatthenumber(dr("tradecreditors") & "", "###,###,##0")

                objlit = Page.FindControl("cus_tbl" & counter & "_10")
                If Not objlit Is Nothing Then objlit.Text = WebLib.formatthenumber(dr("pnlsales") & "", "###,###,##0")

                objlit = Page.FindControl("cus_tbl" & counter & "_11")
                If Not objlit Is Nothing Then objlit.Text = WebLib.formatthenumber(dr("pnlprofitbeforetax") & "", "###,###,##0")

                objlit = Page.FindControl("cus_tbl" & counter & "_12")
                If Not objlit Is Nothing Then objlit.Text = WebLib.formatthemoney(dr("ratiocurrent") & "")

                objlit = Page.FindControl("cus_tbl" & counter & "_13")
                If Not objlit Is Nothing Then objlit.Text = WebLib.formatthemoney(dr("ratiodebt") & "")

                objlit = Page.FindControl("cus_tbl" & counter & "_14")
                If Not objlit Is Nothing Then
                    If IsNumeric(dr("ratiocreditor") & "") = True Then
                        objlit.Text = CInt(dr("ratiocreditor") & "")
                    End If
                End If

                objlit = Page.FindControl("cus_tbl" & counter & "_15")
                If Not objlit Is Nothing Then objlit.Text = WebLib.formatthenumber(dr("dso") & "", "###,###,##0")
NextLine:
            Next

            obj = Nothing
        End If
    End Sub

    Private Function ValidateForm()
        lblMessage.Text = ""

        If cus_custype.SelectedIndex < 0 Then
            lblMessage.Text = WebLib.getAlertMessageStyle(" New/Review Not Selected")
            Return False
        End If

        If cus_cusgroup.SelectedIndex < 0 Then
            lblMessage.Text = WebLib.getAlertMessageStyle(" Customer Group Not Selected")
            Return False
        End If

        Return True
    End Function

    Public Sub SetFieldRights()
        wfb_bar.StrictValidationGroup = True  'have to be before uid

        Call wfb_bar.EnableDisable(mp)
    End Sub

    Private Sub assigninitvalues()

    End Sub

    Public Sub backpagepage(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Response.Redirect(WebLib.ClientURL(Redirector.PrevURL1))
    End Sub

    Private Function assigntimestamp()
        littimestamp.Text = "Data Extracted As Of : " & datats.Value
    End Function

    Private Function gettimestamp() As String
        Return System.DateTime.Now
    End Function

    Private Function getApprovalAmount() As String
        Dim lamount As Double = 0

        Call CalculateExposure()

        If IsNumeric(cus_tradinglimit.Text) = True Then
            lamount = lamount + CDbl(cus_tradinglimit.Text)
        End If
        If IsNumeric(cus_projectlimit.Text) = True Then
            lamount = lamount + CDbl(cus_projectlimit.Text)
        End If
        If IsNumeric(cus_groupextotal1.Text) = True Then
            lamount = lamount + CDbl(cus_groupextotal1.Text)
        End If
        If IsNumeric(cus_groupextotal2.Text) = True Then
            lamount = lamount + CDbl(cus_groupextotal2.Text)
        End If

        Return lamount
    End Function

    Private Sub CalculateExposure()
        Dim ltotal1 As Double = 0
        Dim ltotal2 As Double = 0

        If IsNumeric(cus_groupex11.Text) = True Then
            cus_groupex11.Text = WebLib.formatthenumber(cus_groupex11.Text, "###,###,##0")
            ltotal1 = ltotal1 + CDbl(cus_groupex11.Text)
        End If
        If IsNumeric(cus_groupex21.Text) = True Then
            cus_groupex21.Text = WebLib.formatthenumber(cus_groupex21.Text, "###,###,##0")
            ltotal1 = ltotal1 + CDbl(cus_groupex21.Text)
        End If
        If IsNumeric(cus_groupex31.Text) = True Then
            cus_groupex31.Text = WebLib.formatthenumber(cus_groupex31.Text, "###,###,##0")
            ltotal1 = ltotal1 + CDbl(cus_groupex31.Text)
        End If
        If IsNumeric(cus_groupex41.Text) = True Then
            cus_groupex41.Text = WebLib.formatthenumber(cus_groupex41.Text, "###,###,##0")
            ltotal1 = ltotal1 + CDbl(cus_groupex41.Text)
        End If
        If IsNumeric(cus_groupex51.Text) = True Then
            cus_groupex51.Text = WebLib.formatthenumber(cus_groupex51.Text, "###,###,##0")
            ltotal1 = ltotal1 + CDbl(cus_groupex51.Text)
        End If
        If IsNumeric(cus_groupex61.Text) = True Then
            cus_groupex61.Text = WebLib.formatthenumber(cus_groupex61.Text, "###,###,##0")
            ltotal1 = ltotal1 + CDbl(cus_groupex61.Text)
        End If
        If IsNumeric(cus_groupex71.Text) = True Then
            cus_groupex71.Text = WebLib.formatthenumber(cus_groupex71.Text, "###,###,##0")
            ltotal1 = ltotal1 + CDbl(cus_groupex71.Text)
        End If
        If IsNumeric(cus_groupex81.Text) = True Then
            cus_groupex81.Text = WebLib.formatthenumber(cus_groupex81.Text, "###,###,##0")
            ltotal1 = ltotal1 + CDbl(cus_groupex81.Text)
        End If


        If IsNumeric(cus_groupex12.Text) = True Then
            cus_groupex12.Text = WebLib.formatthenumber(cus_groupex12.Text, "###,###,##0")
            ltotal2 = ltotal2 + CDbl(cus_groupex12.Text)
        End If
        If IsNumeric(cus_groupex22.Text) = True Then
            cus_groupex22.Text = WebLib.formatthenumber(cus_groupex22.Text, "###,###,##0")
            ltotal2 = ltotal2 + CDbl(cus_groupex22.Text)
        End If
        If IsNumeric(cus_groupex32.Text) = True Then
            cus_groupex32.Text = WebLib.formatthenumber(cus_groupex32.Text, "###,###,##0")
            ltotal2 = ltotal2 + CDbl(cus_groupex32.Text)
        End If
        If IsNumeric(cus_groupex42.Text) = True Then
            cus_groupex42.Text = WebLib.formatthenumber(cus_groupex42.Text, "###,###,##0")
            ltotal2 = ltotal2 + CDbl(cus_groupex42.Text)
        End If
        If IsNumeric(cus_groupex52.Text) = True Then
            cus_groupex52.Text = WebLib.formatthenumber(cus_groupex52.Text, "###,###,##0")
            ltotal2 = ltotal2 + CDbl(cus_groupex52.Text)
        End If
        If IsNumeric(cus_groupex62.Text) = True Then
            cus_groupex62.Text = WebLib.formatthenumber(cus_groupex62.Text, "###,###,##0")
            ltotal2 = ltotal2 + CDbl(cus_groupex62.Text)
        End If
        If IsNumeric(cus_groupex72.Text) = True Then
            cus_groupex72.Text = WebLib.formatthenumber(cus_groupex72.Text, "###,###,##0")
            ltotal2 = ltotal2 + CDbl(cus_groupex72.Text)
        End If
        If IsNumeric(cus_groupex82.Text) = True Then
            cus_groupex82.Text = WebLib.formatthenumber(cus_groupex82.Text, "###,###,##0")
            ltotal2 = ltotal2 + CDbl(cus_groupex82.Text)
        End If

        cus_groupextotal1.Text = WebLib.formatthenumber(ltotal1, "###,###,##0")
        cus_groupextotal2.Text = WebLib.formatthenumber(ltotal2, "###,###,##0")

    End Sub

    Public Overrides Function LoadData() As Boolean
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow
        Dim templi As ListItem

        If IsNumeric(rid.Value) = False Then
            wfb_bar.uid = ""
            Call SetFieldRights()
            Call LoadCreditDetails()
            Call loadworkings()
            cus_accountholder.SelectedValue = backend.GetAccountHolder((Request("wp2") & "").Trim)
            Exit Function
        End If

        Try
            cmd.CommandText = "Select * from " & TableName & " where cus_id=" & rid.Value
            cmd.Connection = cn
            ad.SelectCommand = cmd
            ad.Fill(ds, "datarecords")

            For Each dr In ds.Tables("datarecords").Rows
                counter = counter + 1
                cus_company.Text = dr("cus_company") & ""
                ccode.Value = dr("cus_custcode") & ""
                ucode.Value = dr("cus_ucode") & ""
                cus_refno.Text = dr("cus_refno") & ""
                lblrefno.Text = dr("cus_uno") & ""

                '*****
                cus_tradinglimit.Text = WebLib.formatthenumber(dr("cus_tradinglimit") & "", "###,###,##0")
                cus_tradingcperiod.Text = dr("cus_tradingcperiod") & ""
                cus_projectlimit.Text = WebLib.formatthenumber(dr("cus_projectlimit") & "", "###,###,##0")
                cus_projectcperiod.Text = dr("cus_projectcperiod") & ""

                '*****
                cus_remarks1.Text = dr("cus_remarks1") & ""
                cus_remarks2.Text = dr("cus_remarks2") & ""
                cus_remarks3.Text = dr("cus_remarks3") & ""
                cus_remarks4.Text = dr("cus_remarks4") & ""
                cus_remarks5.Text = dr("cus_remarks5") & ""
                cus_remarks6.Text = dr("cus_remarks6") & ""

                cus_remarks7.Text = dr("cus_remarks7") & ""
                cus_remarks8.Text = dr("cus_remarks8") & ""
                cus_remarks9.Text = dr("cus_remarks9") & ""
                cus_remarks10.Text = dr("cus_remarks10") & ""

                '****
                cus_tblc1_1.Text = WebLib.formatthenumber(dr("cus_tblc1_1") & "", _l_format)
                cus_tblc2_1.Text = dr("cus_tblc2_1") & ""
                ' cus_tblc3_1.text = WebLib.formatthemoney(dr("cus_tblc3_1") & "")

                'If IsDate(dr("cus_tblc3_1")) = True Then
                '   cus_tblc3_1.value = CDate(dr("cus_tblc3_1").ToString)
                cus_tblc3_1.textdmy = ViFeandi.General.convertMMDDYYYYtoDDMMYYYY(dr("cus_tblc3_1").ToString)
                ' End If

                cus_tblc1_2.Text = WebLib.formatthenumber(dr("cus_tblc1_2") & "", _l_format)
                cus_tblc2_2.Text = dr("cus_tblc2_2") & ""
                cus_tblc3_2.textdmy = ViFeandi.General.convertMMDDYYYYtoDDMMYYYY(dr("cus_tblc3_2").ToString)


                cus_tblc1_3.Text = WebLib.formatthenumber(dr("cus_tblc1_3") & "", _l_format)
                cus_tblc2_3.Text = dr("cus_tblc2_3") & ""
                cus_tblc3_3.textdmy = ViFeandi.General.convertMMDDYYYYtoDDMMYYYY(dr("cus_tblc3_3").ToString)

                cus_tblc1_4.Text = WebLib.formatthenumber(dr("cus_tblc1_4") & "", _l_format)
                cus_tblc2_4.Text = dr("cus_tblc2_4") & ""
                cus_tblc3_4.textdmy = ViFeandi.General.convertMMDDYYYYtoDDMMYYYY(dr("cus_tblc3_4").ToString)

                cus_tblc1_5.Text = WebLib.formatthenumber(dr("cus_tblc1_5") & "", _l_format)
                cus_tblc2_5.Text = dr("cus_tblc2_5") & ""
                cus_tblc3_5.textdmy = ViFeandi.General.convertMMDDYYYYtoDDMMYYYY(dr("cus_tblc3_5").ToString)

                '***

                cus_payment1.Checked = WebLib.BitToBoolean(dr("cus_payment1") & "")
                cus_payment2.Checked = WebLib.BitToBoolean(dr("cus_payment2") & "")
                cus_payment3.Checked = WebLib.BitToBoolean(dr("cus_payment3") & "")
                cus_payment4.Checked = WebLib.BitToBoolean(dr("cus_payment4") & "")
                cus_payment5.Checked = WebLib.BitToBoolean(dr("cus_payment5") & "")

                templi = cus_groupexposure.Items.FindByValue(dr("cus_groupexposure") & "")
                cus_groupexposure.SelectedIndex = cus_groupexposure.Items.IndexOf(templi)

                Try
                    cus_groupex10.Text = dr("cus_groupex10") & ""
                    cus_groupex11.Text = dr("cus_groupex11") & ""
                    cus_groupex12.Text = dr("cus_groupex12") & ""

                    cus_groupex20.Text = dr("cus_groupex20") & ""
                    cus_groupex21.Text = dr("cus_groupex21") & ""
                    cus_groupex22.Text = dr("cus_groupex22") & ""

                    cus_groupex30.Text = dr("cus_groupex30") & ""
                    cus_groupex31.Text = dr("cus_groupex31") & ""
                    cus_groupex32.Text = dr("cus_groupex32") & ""

                    cus_groupex40.Text = dr("cus_groupex40") & ""
                    cus_groupex41.Text = dr("cus_groupex41") & ""
                    cus_groupex42.Text = dr("cus_groupex42") & ""

                    cus_groupex50.Text = dr("cus_groupex50") & ""
                    cus_groupex51.Text = dr("cus_groupex51") & ""
                    cus_groupex52.Text = dr("cus_groupex52") & ""

                    cus_groupex60.Text = dr("cus_groupex60") & ""
                    cus_groupex61.Text = dr("cus_groupex61") & ""
                    cus_groupex62.Text = dr("cus_groupex62") & ""

                    cus_groupex70.Text = dr("cus_groupex70") & ""
                    cus_groupex71.Text = dr("cus_groupex71") & ""
                    cus_groupex72.Text = dr("cus_groupex72") & ""

                    cus_groupex80.Text = dr("cus_groupex80") & ""
                    cus_groupex81.Text = dr("cus_groupex81") & ""
                    cus_groupex82.Text = dr("cus_groupex82") & ""

                    If IsDate(dr("cus_groupex13")) = True Then
                        cus_groupex13.value = CDate(dr("cus_groupex13").ToString)
                        Try
                            cus_groupex13.textdmy = ViFeandi.General.convertMMDDYYYYtoDDMMYYYY(dr("cus_groupex13").ToString)
                        Catch ex As Exception
                        End Try
                    End If
                    If IsDate(dr("cus_groupex23")) = True Then
                        cus_groupex23.value = CDate(dr("cus_groupex23").ToString)
                        Try
                            cus_groupex23.textdmy = ViFeandi.General.convertMMDDYYYYtoDDMMYYYY(dr("cus_groupex23").ToString)
                        Catch ex As Exception
                        End Try
                    End If
                    If IsDate(dr("cus_groupex33")) = True Then
                        cus_groupex33.value = CDate(dr("cus_groupex33").ToString)
                        Try
                            cus_groupex33.textdmy = ViFeandi.General.convertMMDDYYYYtoDDMMYYYY(dr("cus_groupex33").ToString)
                        Catch ex As Exception
                        End Try
                    End If
                    If IsDate(dr("cus_groupex43")) = True Then
                        cus_groupex43.value = CDate(dr("cus_groupex43").ToString)
                        Try
                            cus_groupex43.textdmy = ViFeandi.General.convertMMDDYYYYtoDDMMYYYY(dr("cus_groupex43").ToString)
                        Catch ex As Exception
                        End Try
                    End If
                    If IsDate(dr("cus_groupex53")) = True Then
                        cus_groupex53.value = CDate(dr("cus_groupex53").ToString)
                        Try
                            cus_groupex53.textdmy = ViFeandi.General.convertMMDDYYYYtoDDMMYYYY(dr("cus_groupex53").ToString)
                        Catch ex As Exception
                        End Try
                    End If
                    If IsDate(dr("cus_groupex63")) = True Then
                        cus_groupex63.value = CDate(dr("cus_groupex63").ToString)
                        Try
                            cus_groupex63.textdmy = ViFeandi.General.convertMMDDYYYYtoDDMMYYYY(dr("cus_groupex63").ToString)
                        Catch ex As Exception
                        End Try
                    End If
                    If IsDate(dr("cus_groupex73")) = True Then
                        cus_groupex73.value = CDate(dr("cus_groupex73").ToString)
                        Try
                            cus_groupex73.textdmy = ViFeandi.General.convertMMDDYYYYtoDDMMYYYY(dr("cus_groupex73").ToString)
                        Catch ex As Exception
                        End Try
                    End If
                    If IsDate(dr("cus_groupex83")) = True Then
                        cus_groupex83.value = CDate(dr("cus_groupex83").ToString)
                        Try
                            cus_groupex83.textdmy = ViFeandi.General.convertMMDDYYYYtoDDMMYYYY(dr("cus_groupex83").ToString)
                        Catch ex As Exception
                        End Try
                    End If
                Catch ex As Exception

                End Try

                templi = legalwind.Items.FindByValue(dr("legalwind") & "")
                legalwind.SelectedIndex = legalwind.Items.IndexOf(templi)

                templi = legalbackcruptcy.Items.FindByValue(dr("legalbackcruptcy") & "")
                legalbackcruptcy.SelectedIndex = legalbackcruptcy.Items.IndexOf(templi)

                Try
                    Dim objlit As Literal
                    For countla As Integer = 1 To 5
                        For countba As Integer = 1 To 15  '14
                            objlit = Page.FindControl("cus_tbl" & countla & "_" & countba)

                            If Not objlit Is Nothing Then
                                'If isnumeric(dr("cus_tbl" & countla & "_" & "1") & "") = True Then
                                '   If CInt(dr("cus_tbl" & countla & "_" & "1") & "") > 0 Then
                                '       objlit.Text = WebLib.formatthemoney(dr("cus_tbl" & countla & "_" & countba) & "")
                                '   End If
                                'End If

                                'If isdate(dr("cus_tbl" & countla & "_" & "1") & "") = True Then
                                If (dr("cus_tbl" & countla & "_" & "1") & "").trim <> "" Then

                                    'If CInt(dr("cus_tbl" & countla & "_" & "1") & "") > 0 Then
                                    If countba = 1 Then
                                        objlit.Text = dr("cus_tbl" & countla & "_" & countba) & ""
                                    Else
                                        'If countba = 14 Then 'creditors angeing then
                                        '   If isnumeric(dr("cus_tbl" & countla & "_" & countba) & "") = True Then
                                        '       objlit.Text = CInt(dr("cus_tbl" & countla & "_" & countba) & "")
                                        '   End If
                                        'Else
                                        '   objlit.Text = WebLib.formatthemoney(dr("cus_tbl" & countla & "_" & countba) & "")
                                        objlit.Text = dr("cus_tbl" & countla & "_" & countba) & ""
                                    End If
                                    '   End If
                                    'End If
                                End If
                            End If
                        Next
                    Next
                Catch ex As Exception

                End Try

                datats.Value = dr("cus_datats") & ""
                Call assigntimestamp()
                Call CalculateExposure()

                templi = cus_custype.Items.FindByValue(dr("cus_custype") & "")
                cus_custype.SelectedIndex = cus_custype.Items.IndexOf(templi)

                templi = cus_cusgroup.Items.FindByValue(dr("cus_cusgroup") & "")
                cus_cusgroup.SelectedIndex = cus_cusgroup.Items.IndexOf(templi)

                cus_accountholder.SelectedValue = dr("cus_accountholder") & ""
                createdt.Value = dr("cus_createdt").ToString.Trim

                wfb_bar.StrictValidationGroup = True  'have to be before uid
                wfb_bar.uid = ucode.Value

                Exit For
            Next

            cn.Close()
            cmd.Dispose()
            cn.Dispose()

            If wfb_bar.Workflowended = True Then
                btnsave.enabled = False
            Else
                btnsave.enabled = True
            End If

            Call SetFieldRights()
            Call enabledisablecustomer()
            Call loadworkings()

            loaddraft()

        Catch ex As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
        End Try

    End Function

    Private Sub savedatadata(ByVal pWorkflowAction As Boolean, ByVal pType As String)
        Dim insertfields, insertvalues As String
        Dim lsrdesc As String = ""
        Dim lsql As String = ""
        insertfields = ""
        insertvalues = ""

        If ValidateForm() = False Then
            Exit Sub
        End If

        Dim lcus_groupexposure As String = ""
        If cus_groupexposure.SelectedIndex < 0 Then
            lcus_groupexposure = ""
        Else
            lcus_groupexposure = cus_groupexposure.SelectedItem.Value
        End If

        Dim llegalwind As String = ""
        If legalwind.SelectedIndex < 0 Then
            llegalwind = ""
        Else
            llegalwind = legalwind.SelectedItem.Value
        End If

        Dim llegalbackcruptcy As String = ""
        If legalbackcruptcy.SelectedIndex < 0 Then
            llegalbackcruptcy = ""
        Else
            llegalbackcruptcy = legalbackcruptcy.SelectedItem.Value
        End If

        wfb_bar.DocumentAmt = getApprovalAmount()

        Try
            If rid.Value = "" Then
                ucode.Value = WebLib.getUniqueKey

                Dim lID As String
                Dim lDocno As String = ""
                lDocno = WebLib.GetDocNo(NmSpace, "cus_uno", APPCode) & ""

                If lDocno.Trim = "" Then
                    lblMessage.Text = WebLib.getAlertMessageStyle("Document No. Not Set")
                    Exit Sub
                End If
                lID = WebLib.GetValue("Workflowlink", "wfl_wflowid", "wfl_subcode", "'" & FORMCODE & "'", "", "")

                If IsNumeric(lID) = False Or (lID & "").Trim = "0" Then
                    lblMessage.Text = WebLib.getAlertMessageStyle("No Workflow Assign for this form")
                    Exit Sub
                End If

                lsql = wfb_bar.GetWorkFlowSaveSQL(lID, ucode.Value, True, cus_refno.Text, NmSpace, "Credit Evaluation Form", cus_company.Text, lDocno)

                '**** CUSTOMISED ******'

                If cansaveitems() = True Then
                    If (lsql & "").Trim <> "" Then
                        lsql = lsql & ";"
                    End If
                    lsql = lsql & SaveItems(ucode.Value)
                    '*****
                End If

                insertfields = insertfields & "cus_merchantid"
                insertvalues = insertvalues & "'" & ccode.Value.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_uno"
                insertvalues = insertvalues & ",'" & lDocno & "'"
                insertfields = insertfields & ",cus_filter"
                insertvalues = insertvalues & ",'" & WebLib.FilterCode.replace("'", "''") & "'"
                insertfields = insertfields & ",cus_ucode"
                insertvalues = insertvalues & ",'" & ucode.Value & "'"

                insertfields = insertfields & ",cus_custype"
                insertvalues = insertvalues & ",'" & cus_custype.SelectedItem.Value & "'"
                insertfields = insertfields & ",cus_cusgroup"
                insertvalues = insertvalues & ",'" & cus_cusgroup.SelectedItem.Value & "'"
                insertfields = insertfields & ",cus_custcode"
                insertvalues = insertvalues & ",'" & ccode.Value.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_company"
                insertvalues = insertvalues & ",'" & cus_company.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_refno"
                insertvalues = insertvalues & ",'" & cus_refno.Text.Replace("'", "''") & "'"

                '************
                insertfields = insertfields & ",cus_tradinglimit"
                insertvalues = insertvalues & ",'" & cus_tradinglimit.Text.Replace("'", "''").Replace(",", "") & "'"
                insertfields = insertfields & ",cus_tradingcperiod"
                insertvalues = insertvalues & ",'" & cus_tradingcperiod.Text.Replace("'", "''").Replace(",", "") & "'"
                insertfields = insertfields & ",cus_projectlimit"
                insertvalues = insertvalues & ",'" & cus_projectlimit.Text.Replace("'", "''").Replace(",", "") & "'"
                insertfields = insertfields & ",cus_projectcperiod"
                insertvalues = insertvalues & ",'" & cus_projectcperiod.Text.Replace("'", "''").Replace(",", "") & "'"

                insertfields = insertfields & ",cus_payment1"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_payment1.Checked)
                insertfields = insertfields & ",cus_payment2"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_payment2.Checked)
                insertfields = insertfields & ",cus_payment3"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_payment3.Checked)
                insertfields = insertfields & ",cus_payment4"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_payment4.Checked)
                insertfields = insertfields & ",cus_payment5"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_payment5.Checked)
                insertfields = insertfields & ",cus_groupexposure"
                insertvalues = insertvalues & ",'" & lcus_groupexposure & "'"
                insertfields = insertfields & ",legalwind"
                insertvalues = insertvalues & ",'" & llegalwind & "'"
                insertfields = insertfields & ",legalbackcruptcy"
                insertvalues = insertvalues & ",'" & llegalbackcruptcy & "'"
                '************

                insertfields = insertfields & ",cus_remarks1"
                insertvalues = insertvalues & ",'" & cus_remarks1.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_remarks2"
                insertvalues = insertvalues & ",'" & cus_remarks2.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_remarks3"
                insertvalues = insertvalues & ",'" & cus_remarks3.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_remarks4"
                insertvalues = insertvalues & ",'" & cus_remarks4.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_remarks5"
                insertvalues = insertvalues & ",'" & cus_remarks5.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_remarks6"
                insertvalues = insertvalues & ",'" & cus_remarks6.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_remarks7"
                insertvalues = insertvalues & ",'" & cus_remarks7.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_remarks8"
                insertvalues = insertvalues & ",'" & cus_remarks8.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_remarks9"
                insertvalues = insertvalues & ",'" & cus_remarks9.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_remarks10"
                insertvalues = insertvalues & ",'" & cus_remarks10.Text.Replace("'", "''") & "'"

                '****
                Dim objlit As Literal
                For countla As Integer = 1 To 5
                    For countba As Integer = 1 To 15  '14
                        objlit = Page.FindControl("cus_tbl" & countla & "_" & countba)
                        If Not objlit Is Nothing Then
                            insertfields = insertfields & ",cus_tbl" & countla & "_" & countba
                            insertvalues = insertvalues & ",'" & objlit.Text.Replace("'", "''") & "'"
                        End If
                    Next
                Next
                '*****

                insertfields = insertfields & ",cus_tblc1_1"
                insertvalues = insertvalues & ",'" & cus_tblc1_1.Text.Replace("'", "''").Replace(",", "") & "'"
                insertfields = insertfields & ",cus_tblc2_1"
                insertvalues = insertvalues & ",'" & cus_tblc2_1.Text.Replace("'", "''").Replace(",", "") & "'"
                insertfields = insertfields & ",cus_tblc3_1"
                insertvalues = insertvalues & ",'" & cus_tblc3_1.value & "'"

                insertfields = insertfields & ",cus_tblc1_2"
                insertvalues = insertvalues & ",'" & cus_tblc1_2.Text.Replace("'", "''").Replace(",", "") & "'"
                insertfields = insertfields & ",cus_tblc2_2"
                insertvalues = insertvalues & ",'" & cus_tblc2_2.Text.Replace("'", "''").Replace(",", "") & "'"
                insertfields = insertfields & ",cus_tblc3_2"
                insertvalues = insertvalues & ",'" & cus_tblc3_2.value & "'"

                insertfields = insertfields & ",cus_tblc1_3"
                insertvalues = insertvalues & ",'" & cus_tblc1_3.Text.Replace("'", "''").Replace(",", "") & "'"
                insertfields = insertfields & ",cus_tblc2_3"
                insertvalues = insertvalues & ",'" & cus_tblc2_3.Text.Replace("'", "''").Replace(",", "") & "'"
                insertfields = insertfields & ",cus_tblc3_3"
                insertvalues = insertvalues & ",'" & cus_tblc3_3.value & "'"

                insertfields = insertfields & ",cus_tblc1_4"
                insertvalues = insertvalues & ",'" & cus_tblc1_4.Text.Replace("'", "''").Replace(",", "") & "'"
                insertfields = insertfields & ",cus_tblc2_4"
                insertvalues = insertvalues & ",'" & cus_tblc2_4.Text.Replace("'", "''").Replace(",", "") & "'"
                insertfields = insertfields & ",cus_tblc3_4"
                insertvalues = insertvalues & ",'" & cus_tblc3_4.value & "'"

                insertfields = insertfields & ",cus_tblc1_5"
                insertvalues = insertvalues & ",'" & cus_tblc1_5.Text.Replace("'", "''").Replace(",", "") & "'"
                insertfields = insertfields & ",cus_tblc2_5"
                insertvalues = insertvalues & ",'" & cus_tblc2_5.Text.Replace("'", "''").Replace(",", "") & "'"
                insertfields = insertfields & ",cus_tblc3_5"
                insertvalues = insertvalues & ",'" & cus_tblc3_5.value & "'"

                insertfields = insertfields & ",cus_datats"
                insertvalues = insertvalues & ",'" & datats.Value & "'"

                insertfields = insertfields & ",cus_createby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",cus_createdt"
                insertvalues = insertvalues & ",getdate()"
                insertfields = insertfields & ",cus_updateby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",cus_updatedt"
                insertvalues = insertvalues & ",getdate()"
                insertfields = insertfields & ",cus_accountholder"
                insertvalues = insertvalues & ",'" & cus_accountholder.SelectedValue & "'"

            Else
                If pWorkflowAction = True Then
                    lsql = wfb_bar.getapprovesql(pType)
                End If

                If cansaveitems() = True Then
                    If (lsql & "").Trim <> "" Then
                        lsql = lsql & ";"
                    End If
                    lsql = lsql & SaveItems(ucode.Value)
                    '*****
                End If

                insertvalues = insertvalues & "cus_updateby='" & WebLib.LoginUser.replace("'", "''") & "'"
                insertvalues = insertvalues & ",cus_updatedt=getdate()"

                If cus_company.Enabled = True Then
                    insertvalues = insertvalues & ",cus_company='" & cus_company.Text.Replace("'", "''") & "'"
                End If
                If cus_custype.Enabled = True Then
                    insertvalues = insertvalues & ",cus_custype='" & cus_custype.SelectedItem.Value & "'"
                End If
                If cus_cusgroup.Enabled = True Then
                    insertvalues = insertvalues & ",cus_cusgroup='" & cus_cusgroup.SelectedItem.Value & "'"
                End If

                '************

                If cus_tradinglimit.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tradinglimit='" & cus_tradinglimit.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_tradingcperiod.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tradingcperiod='" & cus_tradingcperiod.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_projectlimit.Enabled = True Then
                    insertvalues = insertvalues & ",cus_projectlimit='" & cus_projectlimit.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_projectcperiod.Enabled = True Then
                    insertvalues = insertvalues & ",cus_projectcperiod='" & cus_projectcperiod.Text.Replace("'", "''").Replace(",", "") & "'"
                End If

                '************
                If cus_remarks1.Enabled = True Then
                    insertvalues = insertvalues & ",cus_remarks1='" & cus_remarks1.Text.Replace("'", "''") & "'"
                End If
                If cus_remarks2.Enabled = True Then
                    insertvalues = insertvalues & ",cus_remarks2='" & cus_remarks2.Text.Replace("'", "''") & "'"
                End If
                If cus_remarks3.Enabled = True Then
                    insertvalues = insertvalues & ",cus_remarks3='" & cus_remarks3.Text.Replace("'", "''") & "'"
                End If
                If cus_remarks4.Enabled = True Then
                    insertvalues = insertvalues & ",cus_remarks4='" & cus_remarks4.Text.Replace("'", "''") & "'"
                End If
                If cus_remarks5.Enabled = True Then
                    insertvalues = insertvalues & ",cus_remarks5='" & cus_remarks5.Text.Replace("'", "''") & "'"
                End If
                If cus_remarks6.Enabled = True Then
                    insertvalues = insertvalues & ",cus_remarks6='" & cus_remarks6.Text.Replace("'", "''") & "'"
                End If
                If cus_remarks7.Enabled = True Then
                    insertvalues = insertvalues & ",cus_remarks7='" & cus_remarks7.Text.Replace("'", "''") & "'"
                End If
                If cus_remarks8.Enabled = True Then
                    insertvalues = insertvalues & ",cus_remarks8='" & cus_remarks8.Text.Replace("'", "''") & "'"
                End If
                If cus_remarks9.Enabled = True Then
                    insertvalues = insertvalues & ",cus_remarks9='" & cus_remarks9.Text.Replace("'", "''") & "'"
                End If
                If cus_remarks10.Enabled = True Then
                    insertvalues = insertvalues & ",cus_remarks10='" & cus_remarks10.Text.Replace("'", "''") & "'"
                End If

                '****
                Dim objlit As Literal
                For countla As Integer = 1 To 5
                    For countba As Integer = 1 To 15  '14
                        objlit = Page.FindControl("cus_tbl" & countla & "_" & countba)
                        If Not objlit Is Nothing Then
                            insertvalues = insertvalues & ",cus_tbl" & countla & "_" & countba & "='" & objlit.Text.Replace("'", "''") & "'"
                        End If
                    Next
                Next
                insertvalues = insertvalues & ",cus_datats='" & datats.Value & "'"
                '*****

                If cus_tblc1_1.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc1_1='" & cus_tblc1_1.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_tblc2_1.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc2_1='" & cus_tblc2_1.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_tblc3_1.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc3_1='" & cus_tblc3_1.value.Replace("'", "''").replace(",", "") & "'"
                End If

                If cus_tblc1_2.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc1_2='" & cus_tblc1_2.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_tblc2_2.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc2_2='" & cus_tblc2_2.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_tblc3_2.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc3_2='" & cus_tblc3_2.value.Replace("'", "''").replace(",", "") & "'"
                End If

                If cus_tblc1_3.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc1_3='" & cus_tblc1_3.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_tblc2_3.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc2_3='" & cus_tblc2_3.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_tblc3_3.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc3_3='" & cus_tblc3_3.value.Replace("'", "''").replace(",", "") & "'"
                End If

                If cus_tblc1_4.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc1_4='" & cus_tblc1_4.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_tblc2_4.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc2_4='" & cus_tblc2_4.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_tblc3_4.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc3_4='" & cus_tblc3_4.value.Replace("'", "''").replace(",", "") & "'"
                End If

                If cus_tblc1_5.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc1_5='" & cus_tblc1_5.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_tblc2_5.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc2_5='" & cus_tblc2_5.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_tblc3_5.Enabled = True Then
                    insertvalues = insertvalues & ",cus_tblc3_5='" & cus_tblc3_5.value.Replace("'", "''").replace(",", "") & "'"
                End If

                If cus_payment1.Enabled = True Then
                    insertvalues = insertvalues & ",cus_payment1=" & WebLib.BooleanToBit(cus_payment1.Checked)
                End If
                If cus_payment2.Enabled = True Then
                    insertvalues = insertvalues & ",cus_payment2=" & WebLib.BooleanToBit(cus_payment2.Checked)
                End If
                If cus_payment3.Enabled = True Then
                    insertvalues = insertvalues & ",cus_payment3=" & WebLib.BooleanToBit(cus_payment3.Checked)
                End If
                If cus_payment4.Enabled = True Then
                    insertvalues = insertvalues & ",cus_payment4=" & WebLib.BooleanToBit(cus_payment4.Checked)
                End If
                If cus_payment5.Enabled = True Then
                    insertvalues = insertvalues & ",cus_payment5=" & WebLib.BooleanToBit(cus_payment5.Checked)
                End If


                '****** GROUP EXPOSURE ******
                If cus_groupexposure.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupexposure='" & lcus_groupexposure & "'"
                End If

                If cus_groupex10.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex10='" & cus_groupex10.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex11.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex11='" & cus_groupex11.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex12.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex12='" & cus_groupex12.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex13.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex13='" & cus_groupex13.value & "'"
                End If

                If cus_groupex20.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex20='" & cus_groupex20.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex21.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex21='" & cus_groupex21.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex22.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex22='" & cus_groupex22.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex23.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex23='" & cus_groupex23.value & "'"
                End If

                If cus_groupex30.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex30='" & cus_groupex30.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex31.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex31='" & cus_groupex31.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex32.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex32='" & cus_groupex32.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex33.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex33='" & cus_groupex33.value & "'"
                End If

                If cus_groupex40.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex40='" & cus_groupex40.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex41.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex41='" & cus_groupex41.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex42.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex42='" & cus_groupex42.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex43.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex43='" & cus_groupex43.value & "'"
                End If

                If cus_groupex50.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex50='" & cus_groupex50.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex51.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex51='" & cus_groupex51.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex52.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex52='" & cus_groupex52.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex53.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex53='" & cus_groupex53.value & "'"
                End If

                If cus_groupex60.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex60='" & cus_groupex60.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex61.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex61='" & cus_groupex61.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex62.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex62='" & cus_groupex62.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex63.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex63='" & cus_groupex63.value & "'"
                End If

                If cus_groupex70.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex70='" & cus_groupex70.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex71.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex71='" & cus_groupex71.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex72.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex72='" & cus_groupex72.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex73.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex73='" & cus_groupex73.value & "'"
                End If

                If cus_groupex80.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex80='" & cus_groupex80.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex81.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex81='" & cus_groupex81.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex82.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex82='" & cus_groupex82.Text.Replace("'", "''").Replace(",", "") & "'"
                End If
                If cus_groupex83.Enabled = True Then
                    insertvalues = insertvalues & ",cus_groupex83='" & cus_groupex83.value & "'"
                End If

                '*****************************

                If legalwind.Enabled = True Then
                    insertvalues = insertvalues & ",legalwind='" & llegalwind & "'"
                End If
                If legalbackcruptcy.Enabled = True Then
                    insertvalues = insertvalues & ",legalbackcruptcy='" & llegalbackcruptcy & "'"
                End If
                If cus_accountholder.Enabled = True Then
                    insertvalues = insertvalues & ",cus_accountholder='" & cus_accountholder.SelectedValue & "'"
                End If
            End If

            Dim lsqlcom As String = ""
            lsqlcom = lsqlcom & "'" & WebLib.LoginUser.replace("'", "''") & "'"
            'lsqlcom = lsqlcom & ",'" & IIf(cus_remarks.Text = "", "[Please refer to above section.]", cus_remarks.Text.Replace("'", "''")) & "'"
            lsqlcom = lsqlcom & ",'" & cus_remarks.Text.Replace("'", "''") & "'"
            lsqlcom = lsqlcom & ",getdate()"

            wfb_bar.postComments(lsqlcom, TableName, pWorkflowAction)

            If savedata(insertfields, insertvalues, True, lsql) = True Then
                If pType = "" Then
                    pType = "route"
                End If
                If pWorkflowAction = True Then
                    If wfb_bar.notifyusers(pType) = False Then
                    End If
                End If
                Response.Redirect("~/" & Redirector.Redirect(NmSpace, ucode.Value, False))
            Else
                lblMessage.Text = WebLib.getAlertMessageStyle("There is an error while saving. Please retry")
            End If
        Catch Err As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(Err.Message)
        Finally
        End Try

    End Sub

    Public Sub savepage(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Call savedatadata(False, "")
    End Sub

    Protected Sub wfb_bar_OnApproveEvent(ByVal sender As Object, ByVal e As EventArgs) Handles wfb_bar.OnApproveEvent
        Call savedatadata(True, "Approve")
    End Sub

    Protected Sub wfb_bar_OnRejectEvent(ByVal sender As Object, ByVal e As EventArgs) Handles wfb_bar.OnRejectEvent
        Call savedatadata(True, "Reject")
    End Sub

    Protected Sub wfb_bar_OnCancelEvent(ByVal sender As Object, ByVal e As EventArgs) Handles wfb_bar.OnCancelEvent
        Call savedatadata(True, "Cancel")
    End Sub

    Protected Sub rep_ItemDataBound(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.RepeaterItemEventArgs) Handles rep.ItemDataBound
        Dim drv As DataRowView
        drv = e.Item.DataItem

        Dim objdata As Literal
        Dim objdata2 As TextBox
        Dim objdataDD As Object
        Dim lsubtotal As String
        Dim lGST As String
        Dim lLess As String
        Dim lTotal As String
        Dim templi As ListItem

        If IsNumeric(littotal1.Text) = False Then
            littotal1.Text = "0"
        End If
        If IsNumeric(littotal2.Text) = False Then
            littotal2.Text = "0"
        End If
        If IsNumeric(littotal3.Text) = False Then
            littotal3.Text = "0"
        End If

        If cansaveitems() = True Then
            objdata = e.Item.FindControl("litparam1")
            If Not objdata Is Nothing Then
                objdata.Visible = False
            End If
            objdata = e.Item.FindControl("litparam2")
            If Not objdata Is Nothing Then
                objdata.Visible = False
            End If
            objdata = e.Item.FindControl("litparam3")
            If Not objdata Is Nothing Then
                objdata.Visible = False
            End If
            objdata = e.Item.FindControl("litparam4")
            If Not objdata Is Nothing Then
                objdata.Visible = False
            End If
            objdata = e.Item.FindControl("litparam5")
            If Not objdata Is Nothing Then
                objdata.Visible = False
            End If

            objdata2 = e.Item.FindControl("txtparam1")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = True
                objdata2.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
            End If
            objdata2 = e.Item.FindControl("txtparam2")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = True
                objdata2.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
            End If
            objdata2 = e.Item.FindControl("txtparam3")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = True
                objdata2.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
            End If
            objdata2 = e.Item.FindControl("txtparam4")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = True
                objdata2.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
            End If
            objdata2 = e.Item.FindControl("txtparam5")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = True
                objdata2.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
            End If

        Else
            objdata = e.Item.FindControl("litparam1")
            If Not objdata Is Nothing Then
                objdata.Visible = True
            End If
            objdata = e.Item.FindControl("litparam2")
            If Not objdata Is Nothing Then
                objdata.Visible = True
            End If
            objdata = e.Item.FindControl("litparam3")
            If Not objdata Is Nothing Then
                objdata.Visible = True
            End If
            objdata = e.Item.FindControl("litparam4")
            If Not objdata Is Nothing Then
                objdata.Visible = True
            End If
            objdata = e.Item.FindControl("litparam5")
            If Not objdata Is Nothing Then
                objdata.Visible = True
            End If

            objdata2 = e.Item.FindControl("txtparam1")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = False
                objdata2.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
            End If
            objdata2 = e.Item.FindControl("txtparam2")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = False
                objdata2.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
            End If
            objdata2 = e.Item.FindControl("txtparam3")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = False
                objdata2.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
            End If
            objdata2 = e.Item.FindControl("txtparam4")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = False
                objdata2.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
            End If
            objdata2 = e.Item.FindControl("txtparam5")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = False
                objdata2.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
            End If
        End If

        If IsNumeric(drv.Row("cus_param2").ToString & "") Then
            objdata2 = e.Item.FindControl("txtparam2")
            If Not objdata2 Is Nothing Then
                objdata2.Text = WebLib.formatthenumber(CDbl(drv.Row("cus_param2").ToString & ""), _l_format)
                objdata2.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
                If IsNumeric(objdata2.Text) = True Then
                    littotal1.Text = WebLib.formatthenumber(CDbl(littotal1.Text) + CDbl(objdata2.Text), _l_format)
                End If
            End If

            objdata = e.Item.FindControl("litparam2")
            If Not objdata Is Nothing Then
                objdata.Text = WebLib.formatthenumber(CDbl(drv.Row("cus_param2").ToString & ""), _l_format)
            End If
        End If

        If IsNumeric(drv.Row("cus_param3").ToString & "") Then
            objdata2 = e.Item.FindControl("txtparam3")
            If Not objdata2 Is Nothing Then
                objdata2.Text = WebLib.formatthenumber(CDbl(drv.Row("cus_param3").ToString & ""), _l_format)
                objdata2.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
                If IsNumeric(objdata2.Text) = True Then
                    littotal2.Text = WebLib.formatthenumber(CDbl(littotal2.Text) + CDbl(objdata2.Text), _l_format)
                End If
            End If

            objdata = e.Item.FindControl("litparam3")
            If Not objdata Is Nothing Then
                objdata.Text = WebLib.formatthenumber(CDbl(drv.Row("cus_param3").ToString & ""), _l_format)
            End If
        End If

        If IsNumeric(drv.Row("cus_param4").ToString & "") Then
            objdata2 = e.Item.FindControl("txtparam4")
            If Not objdata2 Is Nothing Then
                objdata2.Text = WebLib.formatthenumber(CDbl(drv.Row("cus_param4").ToString & ""), _l_format)
                objdata2.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
                If IsNumeric(objdata2.Text) = True Then
                    littotal3.Text = WebLib.formatthenumber(CDbl(littotal3.Text) + CDbl(objdata2.Text), _l_format)
                End If
            End If

            objdata = e.Item.FindControl("litparam4")
            If Not objdata Is Nothing Then
                objdata.Text = WebLib.formatthenumber(CDbl(drv.Row("cus_param4").ToString & ""), _l_format)
            End If
        End If
    End Sub

    Public Function GetBalanceSheetByCustomer_DS(ByVal custcode As String, ByVal topN As Integer, ByVal fromtopyear As Integer) As DataSet
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow
        Dim comList As New ArrayList()

        Try
            cmd.CommandText = "select top " & topN.ToString & " Key2 as custcode,Key3 as [datayear],date01 as datadate, Number24 as currentasset, Number25 as currentliabilities, Number21 as nettworkingcapital,Number26 as otherassets,Number27 as paidupcapital, Number28 as networth,Number22 as longtermdebts, Number29 as tradecreditors, number09 as pnlsales,Number10 as pnlprofitbeforetax, number13 as ratiocurrent,number14 as ratiodebt,number18 as ratiocreditor,number01 as DSO from UD04 inner join UD04_ud on UD04.sysrowid = UD04_ud.foreignsysrowid where Key2='" & custcode & "' and key3<='" & fromtopyear.ToString & "' order by Key3 desc"
            cmd.Connection = cn
            ad.SelectCommand = cmd
            ad.Fill(ds, "datarecords")

            Return ds

            cn.Close()
            cmd.Dispose()
            cn.Dispose()
        Catch ex As Exception
            lblMessage.Text = ex.Message
        End Try

        Return ds

    End Function

    Public Sub loadpr()
        Try
            rep_comment.DataSource = wfb_bar.getComments2()
            rep_comment.DataBind()
            rep_audit.DataSource = wfb_bar.GetAuditLogsDs2()
            rep_audit.DataBind()
        Catch ex As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
        End Try
    End Sub

    Public Sub loaddraft()
        Try
            cus_remarks.Text = wfb_bar.getDraft2()
        Catch ex As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
        End Try
    End Sub

    Public Sub RefreshCreditDetails(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Call LoadCreditDetails()
    End Sub

End Class

