Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.OleDb
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls

Partial Public Class cusCCRS_list_class
    Inherits listpage
    'Generated by VI FEANDI SOFTLABS FORM GENERATOR (http://www.vifeandi.net) VER 2014.1
    Private FORMCODE As String = "CCRS"  'Hardcoded for customised form

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        _searchkeystr = "cus_distributor;Distributor Name;S|cus_customer;Customer Name;S|cus_uno;Document Ref No.;S|usr_name;Submitted By;S|cus_createdt;Submission Date;D"

        listingpage = ""
        _FormsName = "Customer Complaint Report (CCR) - Service"
        'columnscount = "10"
        TableName = "zcustom_ccr"
        DetailPage = ""
        IDPField = ""
        IDField = "cus_id"
        AppIDField = ""
        MerchantIDField = ""
        FilterField = "cus_filter"
        Orderby = " order by cus_createdt desc "
        '_pagesize = 20
        APPCode = "WORKFLOW" '"SMS"
        AddRights = "" '"SM0001"
        DelRights = "" ' "SM0003"
        ModRights = "" '"SM0002"
        ViewRights = "" '"SM0004"
        FullRights = "PS0005"
        NmSpace = "zcustom_ccrs"

        pFieldNames = " workflowstatus.*,zcustom_ccr.*,usr_name,ApprovalLevelName = (" & clsWorkflow.getLevelNameSQL("wst_workflowid", "wst_level") & ") "
        pJoinFields = " inner join workflowstatus on cus_ucode = wst_ucode left outer join secuserinfo on cus_createby = usr_loginid "

        If Page.IsPostBack = False Then
            bid.value = Request("ba")

            wfid.value = WebLib.GetValue("Workflowlink", "wfl_wflowid", "wfl_subcode", "'" & FORMCODE & "'", "", "")
            '_searchfilter = " wst_status='Pending' and (cus_createby='" & WebLib.LoginUser & "' or '" & WebLib.LoginUser & "' in (" & clsWorkflow.getUserCodebyWorkFlowSQL("wst_workflowid", "wst_level") & ")) "
            _searchfilter = " isnull(cus_uno,'') <>'' and cus_type='" & FORMCODE & "' and wst_status='Pending' and (cus_createby='" & WebLib.LoginUser & "' or '" & WebLib.LoginUser & "' in (" & clsWorkflow.getUserCodebyWorkFlowSQL("wst_workflowid", "wst_level") & ")) "

        Else
            _searchfilter = " isnull(cus_uno,'') <>'' and cus_type='" & FORMCODE & "' "
        End If
        bid.value = "zcustom_ccrs"

        Call InitLoad()

        btnback.visible = False
        Redirector.PrevURL1 = "modules/custom/cusccr_listS.aspx"
        btnadd.Visible = True

        Call LoadFilterButtons()
    End Sub

    Protected Sub rep_ItemCommand(ByVal source As Object, ByVal e As System.Web.UI.WebControls.RepeaterCommandEventArgs) Handles rep.ItemCommand
    End Sub

    Protected Sub rep_ItemDataBound(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.RepeaterItemEventArgs) Handles rep.ItemDataBound
        Dim drv As DataRowView
        drv = e.Item.DataItem

        redirecttoformcode.Value = FORMCODE

        Dim objdata As Literal = e.Item.FindControl("litimage")
        If Not objdata Is Nothing Then
            'objdata.Text = "<img src=""" & WebLib.ClientURL("graphics/workflow/paper.png") & """ width=""48"">"
            objdata.Text = "<a href=""" & WebLib.ClientURL(Redirector.Redirect(drv.Row("wst_module").ToString.Trim, drv.Row("wst_ucode").ToString.Trim, False, redirecttoformcode.Value)) & """><img src=""" & WebLib.ClientURL("graphics/workflow/paper.png") & """ width=""48""></a>"

        End If

        Dim objdata2 As Literal = e.Item.FindControl("litView")
        If Not objdata2 Is Nothing Then
            objdata2.Text = "<a href=""" & WebLib.ClientURL(Redirector.Redirect(drv.Row("wst_module").ToString.Trim, drv.Row("wst_ucode").ToString.Trim, False, redirecttoformcode.Value)) & """>View Document</a>"
        End If
    End Sub

    Public Sub shortcut1(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Call loaddata(" wst_status='Pending' ")
    End Sub

    Private Sub LoadFilterButtons()
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow
        Dim lsql As String = ""

        Dim lwfid As String = wfid.value
        lsql = clsWorkflow.getLevelsbyWorkflowID(lwfid)

        Dim obj As Object
        obj = Page.FindControl("phFilters")

        If Not obj Is Nothing Then
            Try
                cn.Open()
                cmd.CommandText = lsql
                cmd.Connection = cn
                ad.SelectCommand = cmd
                ad.Fill(ds, "datarecords")
                For Each dr In ds.Tables("datarecords").Rows
                    counter = counter + 1
                    Dim obj1 As New Button
                    obj1.ID = "ID" & dr("recno")
                    obj1.Style.Add("width", "160px")
                    obj1.Text = dr("wui_name")
                    obj1.CssClass = "btn btn-secondary btn-sm w-100 m-1"
                    '                    obj1.Style.Add("height", "20")
                    'word-wrap:break-word;
                    obj1.Style.Add("display", "inline")
                    obj1.Style.Add("white-space", "normal")

                    obj1.Style.Add("word-wrap", "break-word")
                    obj1.Style.Add("text-align", "left")

                    AddHandler obj1.Click, AddressOf Me.filterclick
                    obj.Controls.Add(obj1)
                Next
                cn.Close()
                cmd.Dispose()
                cn.Dispose()
            Catch ex As Exception
            End Try
        End If
    End Sub

    Public Sub filterclick(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Dim lLevel As String
        lLevel = sender.id.ToString.Replace("ID", "")

        If isnumeric(lLevel) = False Then
            lLevel = 0
        End If
        filterhead.text = "Filter : <b>" & sender.Text & "</b>"
        Call loaddata(" wst_status='Pending' and wst_level=" & lLevel)
    End Sub

    Public Sub shortcutmy(ByVal sender As System.Object, ByVal e As System.EventArgs)
        filterhead.text = "Filter : <b>" & sender.Text & "</b>"
        Call loaddata(" wst_status='Pending' and ('" & WebLib.LoginUser & "' in (" & clsWorkflow.getUserCodebyWorkFlowSQL("wst_workflowid", "wst_level") & ")) ")
    End Sub

    Public Sub shortcut2(ByVal sender As System.Object, ByVal e As System.EventArgs)
        filterhead.text = "Filter : <b>" & sender.Text & "</b>"
        Call loaddata(" wst_status='Approved' ")
    End Sub

    Public Sub AddEventAdd(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Response.Redirect("~/" & Redirector.Redirect(bid.Value, "", True, FORMCODE))
    End Sub

    Public Sub shortcut3(ByVal sender As System.Object, ByVal e As System.EventArgs)
        filterhead.text = "Filter : <b>" & sender.Text & "</b>"
        Call loaddata(" wst_status='Cancelled' ")
    End Sub

    Public Sub shortcut4(ByVal sender As System.Object, ByVal e As System.EventArgs)
        filterhead.text = "Filter : <b>" & sender.Text & "</b>"
        Call loaddata(" wst_status='Rejected' ")
    End Sub

End Class

