Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.OleDb
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls

Partial Public Class dn3_class
    Inherits detailspage
    Private FORMCODE As String = "DN3"  'Hardcoded for customised form

    Private fsubtotal As Double = 0
    Private fless As Double = 0
    Private fgst As Double = 0
    Private fgranttotal As Double = 0
    Private ftotalqty As Double = 0
    Private ftotaldiff As Double = 0

    Private fDescription As String = ";;Prompt Payment Incentive;;Early Payment Incentive;;Special Incentive;;Volume Incentive;;Loyalty Incentive;;Elite Club Incentive;;Quality;;BG Support;;Refund;;Panda Green Pallet;;Panda Green Loose;;Panda Blue Pallet;;Panda Blue Loose;;Panda Red Pallet;;Panda Red Loose;;Panda Yellow Pallet;;Panda Yellow Loose;;OPC Bulk;;GGBS;;Clinker"
    Private fUOM As String = ";;Bags;;Tonne;;N/A"

    Private NmSpaceDocNo As String = ""

    'Generated by VI FEANDI SOFTLABS FORM GENERATOR (http://www.vifeandi.net) VER 2014.1

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        listingpage = "wlist.aspx"
        _FormsName = "DEBIT NOTE REQUISITION FORM"
        TableName = "[zcustom_dncn]"
        IDPField = ""
        IDField = "cus_id"
        AppIDField = ""
        MerchantIDField = "cus_merchantid"
        FilterField = "cus_filter"
        APPCode = "WORKFLOW"
        AddRights = ""
        DelRights = ""
        ModRights = ""
        ViewRights = ""
        FullRights = "DN0005"
        NmSpace = "zcustom_dn3"
        NmSpaceDocNo = "zcustom_dn"

        wfb_bar.workflownamespace = NmSpace
        wfb_bar.custommode = True
        wfb_bar.overridemode = True
        wfb_bar.attachmentbycreatoronly = True
        cus_custype.Enabled = False

        If Page.IsPostBack = False Then
            lblrefno.Text = "<b>Auto Generated</b>"

            cus_refno.Text = Request("rc") & ""

            WebLib.SetListItems(cus_cndnmth, Vifeandi.General.GetMonthString(True, "", True))
            WebLib.SetListItems(cus_cndnyear, Vifeandi.General.GetYearString(True, "", 2012, 0, DateTime.Today.Year - 2012))

            If (Request("wp2") & "").Trim <> "" Then '2 always use for custcode
                Dim obj As New RuntimeCustomer
                Call obj.getInfo((Request("wp2") & "").Trim)
                ccode.Value = (Request("wp2") & "").Trim
                cus_company.Text = obj.CustName & ""
                obj = Nothing
            Else
            End If

            cus_accountholder.DataSource = backend.GetAccountHolders(WebLib.LoginUserCompanySelected)
            cus_accountholder.DataValueField = "salesrepcode"
            cus_accountholder.DataTextField = "usr_name"
            cus_accountholder.DataBind()
            cus_accountholder.Items.Insert(0, New ListItem("Please Select", ""))

            assigngstratevalues(System.DateTime.Today)

        End If

        createdt.Value = DateTime.Now
        cus_refno.ReadOnly = True

        Call InitLoad()
        Call enabledisablecustomer()

        wfb_bar.parentobj = mp

        Call assigninitvalues()

        If (wfb_bar.canAction()) Then
            lvlvalid.Value = "True"
        Else
            lvlvalid.Value = "False"
        End If

        If (WebLib.LoginIsFullAdmin = True And wfb_bar.Workflowended = False) Or (IsNumeric(rid.Value) = False And cus_accountholder.SelectedValue = "") Then
            cus_accountholder.Enabled = True
        Else
            cus_accountholder.Enabled = False
        End If

        cus_remarks.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"

        If wfb_bar.wlevelAPget().tostring.trim = "2" Then
            cus_justification.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
            cus_workings.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
            cus_documents.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"
        End If

        loadpr()

    End Sub

    Private Sub enabledisablecustomer()
        cus_company.Enabled = False
    End Sub

    Private Function ValidateForm()
        lblMessage.Text = ""

        If cus_cndnamt.Enabled = True Then
            If IsNumeric(cus_cndnamt.Text) = False Then
                lblMessage.Text = WebLib.getAlertMessageStyle("Please Enter Valid Amount")
                Return False
            End If
        End If

        Return True
    End Function

    Private Sub assigngstratevalues(ByVal thedate As Date)
        If thedate > New System.DateTime(2018, 5, 31) Then
            litgstrate.Text = "0"
            isgst.Value = ""
        Else
            litgstrate.Text = "6"
            isgst.Value = "Y"
        End If

        If thedate >= New System.DateTime(2018, 9, 1) Then
            rwgst.Visible = False
            rwsubtotal.Visible = False
        Else
            rwgst.Visible = True
            rwsubtotal.Visible = True
        End If
    End Sub

    Private Sub loadworkings()
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow

        Call updatetotals(True)

        cn.Open()
        cmd.CommandText = "Select * from zcustom_docitems where cus_uid='" & ucode.Value & "' and cus_type='" & FORMCODE & "'"
        cmd.Connection = cn
        ad.SelectCommand = cmd
        ad.Fill(ds, "datarecords")

        Dim dt As DataTable = ds.Tables("datarecords")
        Dim dv As New DataView(dt)
        Dim lcount As Integer = dt.Rows.Count

        If lcount < 10 Then
            If cansaveitems() = True Then
                For counter = 1 To 10 - lcount
                    dr = dt.NewRow()
                    dt.Rows.Add(dr)
                Next
            End If
        Else
            If cansaveitems() = True Then
                dr = dt.NewRow()
                dt.Rows.Add(dr)
            End If
            'Dont need to do anutjing
        End If

        Dim pgitems As New PagedDataSource()
        pgitems.DataSource = dv
        rep.DataSource = pgitems
        rep.DataBind()

    End Sub

    Private Function SaveItems(ByVal pucode As String) As String
        Dim lseq As Integer = 0
        Dim lcus_invno As String = ""
        Dim lcus_rebate As String = ""
        Dim lcus_rebateactual As String = ""
        Dim lcus_itemcode As String = ""
        Dim lcus_itemdesc As String = ""
        Dim lcus_qty As String = ""
        Dim lcus_amount As String = ""
        Dim lcus_rebatediff As String = ""
        Dim lcus_uid As String = ""
        Dim lcus_uom As String = ""
        Dim lcus_type As String = FORMCODE
        Dim lsql As String = ""
        Dim myObject As Object
        Dim myObjectdd As Object

        lsql = "Delete from zcustom_docitems where cus_uid='" & pucode & "' and cus_type='" & FORMCODE & "'"

        For Each item In rep.Items
            lseq = lseq + 1

            myObject = item.FindControl("txtinvno")
            If Not myObject Is Nothing Then
                lcus_invno = myObject.Text
            End If

            myObjectdd = item.FindControl("txtproduct")
            If Not myObjectdd Is Nothing Then
                If myObjectdd.selectedindex < 0 Then
                    lcus_itemdesc = ""
                Else
                    lcus_itemdesc = myObjectdd.SelectedItem.Value
                End If
            End If

            myObject = item.FindControl("txtrebate")
            If Not myObject Is Nothing Then
                lcus_rebate = myObject.Text.replace(",", "")
            End If

            myObject = item.FindControl("txtrebateactual")
            If Not myObject Is Nothing Then
                lcus_rebateactual = myObject.Text
            End If

            myObject = item.FindControl("txtqty")
            If Not myObject Is Nothing Then

                If IsNumeric(myObject.Text) = True Then
                    lcus_qty = CDbl(myObject.Text)
                Else
                    lcus_qty = myObject.Text
                End If
            End If

            myObjectdd = item.FindControl("txtuom")
            If Not myObjectdd Is Nothing Then
                If myObjectdd.selectedindex < 0 Then
                    lcus_uom = ""
                Else
                    lcus_uom = myObjectdd.SelectedItem.Value
                End If
            End If

            If IsNumeric(lcus_rebateactual) = False Then
                lcus_rebateactual = 0
            End If

            If IsNumeric(lcus_rebate) = False Then
                lcus_rebate = 0
            End If

            If IsNumeric(lcus_qty) = False Then
                lcus_qty = 0
            End If

            lcus_rebatediff = CDbl(lcus_rebate)
            lcus_amount = CDbl(lcus_qty) * CDbl(lcus_rebatediff)

            If lcus_invno.Trim = "" Or lcus_itemdesc.Trim = "" Then
            Else
                lsql = lsql & ";Insert into zcustom_docitems ([cus_invno],[cus_rebate],[cus_rebateactual],[cus_itemdesc],[cus_uom],[cus_qty],[cus_amount],[cus_rebatediff],[cus_uid],[cus_type],cus_seq) Values (" &
                "'" & lcus_invno.Replace("'", "''") & "'," & lcus_rebate & "," & lcus_rebateactual & ",'" & lcus_itemdesc.Replace("'", "''") & "','" & lcus_uom.Replace("'", "''") & "'," &
                lcus_qty & "," & lcus_amount & "," & lcus_rebatediff & ",'" & pucode & "','" & lcus_type & "'," & lseq & ")"
            End If
        Next

        Return lsql

    End Function

    Private Function cansaveitems() As Boolean
        'If wfb_bar.wlevel.value = "1" Or wfb_bar.wlevel.value = "2" Or wfb_bar.wlevel.value = "3" Or wfb_bar.wlevel.value = "0" Or wfb_bar.wlevel.value = "" Then
        If wfb_bar.wlevelAget().tostring.trim = "1" Or wfb_bar.wlevelAget().tostring.trim = "2" Or wfb_bar.wlevelAget().tostring.trim = "3" Or wfb_bar.wlevelAget().tostring.trim = "0" Or wfb_bar.wlevelAget().tostring.trim = "" Then
            Return True
        Else
            Return False
        End If
    End Function

    Protected Sub rep_ItemDataBound(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.RepeaterItemEventArgs) Handles rep.ItemDataBound
        Dim drv As DataRowView
        drv = e.Item.DataItem
        Dim objdata As Literal
        Dim objdata2 As TextBox
        Dim objdataDD As Object

        Dim lsubtotal As String
        Dim lGST As String
        Dim lLess As String
        Dim lTotal As String

        Dim templi As ListItem

        If cansaveitems() = True Then
            objdata = e.Item.FindControl("litinvno")
            If Not objdata Is Nothing Then
                objdata.Visible = False
            End If
            objdata = e.Item.FindControl("litproduct")
            If Not objdata Is Nothing Then
                objdata.Visible = False
            End If
            objdata = e.Item.FindControl("litrebate")
            If Not objdata Is Nothing Then
                objdata.Visible = False
            End If
            objdata = e.Item.FindControl("litrebateactual")
            If Not objdata Is Nothing Then
                objdata.Visible = False
            End If
            objdata = e.Item.FindControl("litqty")
            If Not objdata Is Nothing Then
                objdata.Visible = False
            End If
            objdata = e.Item.FindControl("lituom")
            If Not objdata Is Nothing Then
                objdata.Visible = False
            End If

            objdata2 = e.Item.FindControl("txtinvno")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = True
            End If

            objdataDD = e.Item.FindControl("txtproduct")
            If Not objdataDD Is Nothing Then
                objdataDD.Visible = True
                WebLib.SetListItems(objdataDD, fDescription)
            End If

            objdata2 = e.Item.FindControl("txtrebate")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = True
            End If
            objdata2 = e.Item.FindControl("txtrebateactual")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = True
            End If
            objdata2 = e.Item.FindControl("txtqty")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = True
            End If

            objdataDD = e.Item.FindControl("txtuom")
            If Not objdataDD Is Nothing Then
                objdataDD.Visible = True
                WebLib.SetListItems(objdataDD, fUOM)
            End If
        Else
            objdata = e.Item.FindControl("litinvno")
            If Not objdata Is Nothing Then
                objdata.Visible = True
            End If
            objdata = e.Item.FindControl("litproduct")
            If Not objdata Is Nothing Then
                objdata.Visible = True
            End If
            objdata = e.Item.FindControl("litrebate")
            If Not objdata Is Nothing Then
                objdata.Visible = True
            End If
            objdata = e.Item.FindControl("litrebateactual")
            If Not objdata Is Nothing Then
                objdata.Visible = True
            End If
            objdata = e.Item.FindControl("litqty")
            If Not objdata Is Nothing Then
                objdata.Visible = True
            End If
            objdata = e.Item.FindControl("lituom")
            If Not objdata Is Nothing Then
                objdata.Visible = True
            End If

            objdata2 = e.Item.FindControl("txtinvno")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = False
            End If

            objdataDD = e.Item.FindControl("txtproduct")
            If Not objdataDD Is Nothing Then
                objdataDD.Visible = False
                WebLib.SetListItems(objdataDD, fDescription)
            End If

            objdata2 = e.Item.FindControl("txtrebate")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = False
            End If
            objdata2 = e.Item.FindControl("txtrebateactual")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = False
            End If
            objdata2 = e.Item.FindControl("txtqty")
            If Not objdata2 Is Nothing Then
                objdata2.Visible = False
            End If

            objdataDD = e.Item.FindControl("txtuom")
            If Not objdataDD Is Nothing Then
                objdataDD.Visible = False
                WebLib.SetListItems(objdataDD, fUOM)
            End If
        End If

        Dim lQty As String = "0"
        Dim lDiff As String = "0"
        Dim isvalid As Boolean = True

        If IsNumeric(drv.Row("cus_rebateactual").ToString & "") Then
            objdata2 = e.Item.FindControl("txtrebateactual")
            If Not objdata2 Is Nothing Then
                objdata2.Text = WebLib.formatthemoney(drv.Row("cus_rebateactual").ToString & "")
            End If

            objdata = e.Item.FindControl("litrebateactual")
            If Not objdata Is Nothing Then
                objdata.Text = WebLib.formatthemoney(drv.Row("cus_rebateactual").ToString & "")
            End If
        End If

        If IsNumeric(drv.Row("cus_rebate").ToString & "") Then
            objdata2 = e.Item.FindControl("txtrebate")
            If Not objdata2 Is Nothing Then
                objdata2.Text = WebLib.formatthemoney(drv.Row("cus_rebate").ToString & "")
            End If

            objdata = e.Item.FindControl("litrebate")
            If Not objdata Is Nothing Then
                objdata.Text = WebLib.formatthemoney(drv.Row("cus_rebate").ToString & "")
            End If
        End If

        If IsNumeric(drv.Row("cus_qty").ToString & "") Then
            lQty = drv.Row("cus_qty").ToString & ""

            objdata2 = e.Item.FindControl("txtqty")
            If Not objdata2 Is Nothing Then
                objdata2.Text = WebLib.formatthemoney(lQty)
            End If
            ftotalqty = ftotalqty + CDbl(lQty)
        Else
            isvalid = False
        End If

        If IsNumeric(drv.Row("cus_rebatediff").ToString & "") Then
            lDiff = drv.Row("cus_rebatediff").ToString & ""
            objdata = e.Item.FindControl("litrebatediff")
            If Not objdata Is Nothing Then
                objdata.Text = WebLib.formatthemoney(lDiff)
            End If
            ftotaldiff = ftotaldiff + CDbl(lDiff)
        Else
            isvalid = False
        End If

        objdataDD = e.Item.FindControl("txtuom")
        If Not objdataDD Is Nothing Then
            templi = objdataDD.Items.FindByValue(drv.Row("cus_uom").ToString & "")
            objdataDD.SelectedIndex = objdataDD.Items.IndexOf(templi)
        End If

        objdataDD = e.Item.FindControl("txtproduct")
        If Not objdataDD Is Nothing Then
            templi = objdataDD.Items.FindByValue(drv.Row("cus_itemdesc").ToString & "")
            objdataDD.SelectedIndex = objdataDD.Items.IndexOf(templi)
        End If

        Dim llinetotal As String
        llinetotal = CDbl(lQty) * CDbl(lDiff)

        If isvalid = True Then
            objdata = e.Item.FindControl("litamt")
            If Not objdata Is Nothing Then
                objdata.Text = WebLib.formatthemoney(llinetotal)
                fsubtotal = fsubtotal + CDbl(llinetotal)
            End If
        End If

        'fgst = (fsubtotal * 6) / 100
        If isgst.Value <> "Y" Then
            fgst = (fsubtotal * 0) / 100
        Else
            fgst = (fsubtotal * 6) / 100
        End If
        fgranttotal = (CDbl(fsubtotal) + fgst) - fless

        Call updatetotals(False)

    End Sub

    Public Sub SetFieldRights()
        Call wfb_bar.EnableDisable(mp)
        Exit Sub
    End Sub

    Private Sub assigninitvalues()
    End Sub

    Public Sub backpagepage(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Response.Redirect(WebLib.ClientURL(Redirector.PrevURL1))
    End Sub

    Public Overrides Function LoadData() As Boolean
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow
        Dim templi As ListItem

        If IsNumeric(rid.Value) = False Then
            wfb_bar.uid = ""
            Call SetFieldRights()
            Call loadworkings()
            Call assigngstratevalues(System.DateTime.Today)
            cus_accountholder.SelectedValue = backend.GetAccountHolder((Request("wp2") & "").Trim)
            Exit Function
        End If

        Try
            cmd.CommandText = "Select * from " & TableName & " where cus_id=" & rid.Value & " and cus_type='" & FORMCODE & "'"
            cmd.Connection = cn
            ad.SelectCommand = cmd
            ad.Fill(ds, "datarecords")

            For Each dr In ds.Tables("datarecords").Rows
                counter = counter + 1
                '***** STANDARD *****
                cus_company.Text = dr("cus_company") & ""
                ccode.Value = dr("cus_custcode") & ""
                ucode.Value = dr("cus_ucode") & ""
                cus_refno.Text = dr("cus_refno") & ""
                lblrefno.Text = dr("cus_uno") & ""
                wfb_bar.uid = ucode.Value
                '********************

                cus_cndntype.Text = dr("cus_cndntype") & ""
                cus_cndnreason.Text = dr("cus_cndnreason") & ""

                templi = cus_cndnmth.Items.FindByValue(dr("cus_cndnmth") & "")
                cus_cndnmth.SelectedIndex = cus_cndnmth.Items.IndexOf(templi)
                templi = cus_cndnyear.Items.FindByValue(dr("cus_cndnyear") & "")
                cus_cndnyear.SelectedIndex = cus_cndnyear.Items.IndexOf(templi)

                cus_justification.Checked = WebLib.BitToBoolean(dr("cus_justification") & "")
                cus_workings.Checked = WebLib.BitToBoolean(dr("cus_workings") & "")
                cus_documents.Checked = WebLib.BitToBoolean(dr("cus_documents") & "")

                cus_doc1.Checked = WebLib.BitToBoolean(dr("cus_doc1") & "")
                cus_doc2.Checked = WebLib.BitToBoolean(dr("cus_doc2") & "")
                cus_doc3.Checked = WebLib.BitToBoolean(dr("cus_doc3") & "")
                cus_doc4.Checked = WebLib.BitToBoolean(dr("cus_doc4") & "")
                cus_doc5.Checked = WebLib.BitToBoolean(dr("cus_doc5") & "")
                cus_doc6.Checked = WebLib.BitToBoolean(dr("cus_doc6") & "")
                cus_doc7.Checked = WebLib.BitToBoolean(dr("cus_doc7") & "")
                cus_doc8.Checked = WebLib.BitToBoolean(dr("cus_doc8") & "")

                templi = cus_cndnmth.Items.FindByValue(dr("cus_cndnmth") & "")
                cus_cndnmth.SelectedIndex = cus_cndnmth.Items.IndexOf(templi)
                templi = cus_cndnyear.Items.FindByValue(dr("cus_cndnyear") & "")
                cus_cndnyear.SelectedIndex = cus_cndnyear.Items.IndexOf(templi)

                Try
                    cus_cndnamt.Text = dr("cus_cndnamt") & ""
                    If IsNumeric(cus_cndnamt.Text) = False Then
                        cus_cndnamt.Text = "0"
                    End If
                Catch ex As Exception
                End Try

                'cus_remarks1.Text = dr("cus_remarks1") & ""
                'cus_remarks2.Text = dr("cus_remarks2") & ""
                'cus_remarks3.Text = dr("cus_remarks3") & ""
                'cus_remarks4.Text = dr("cus_remarks4") & ""
                'cus_remarks5.Text = dr("cus_remarks5") & ""
                'cus_remarks6.Text = dr("cus_remarks6") & ""
                'cus_remarks7.Text = dr("cus_remarks7") & ""
                'cus_remarks8.Text = dr("cus_remarks8") & ""

                If IsNumeric(dr("cus_cndnyear") & "") = False Or IsNumeric(dr("cus_cndnmth") & "") = False Then
                    Call assigngstratevalues(dr("cus_createdt"))
                Else
                    Call assigngstratevalues(New Date(CInt(dr("cus_cndnyear")), CInt(dr("cus_cndnmth")), 1))
                End If
                cus_accountholder.SelectedValue = dr("cus_accountholder") & ""
                createdt.Value = dr("cus_createdt").ToString.Trim

                Exit For
            Next

            cn.Close()
            cmd.Dispose()
            cn.Dispose()

            If wfb_bar.Workflowended = True Then
                btnsave.enabled = False
            Else
                btnsave.enabled = True
            End If

            Call SetFieldRights()
            Call enabledisablecustomer()
            Call loadworkings()
            loaddraft()

        Catch ex As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
        End Try
    End Function

    Private Sub savedatadata(ByVal pWorkflowAction As Boolean, ByVal pType As String)
        Dim insertfields, insertvalues As String
        Dim lsrdesc As String = ""
        Dim lsql As String = ""
        insertfields = ""
        insertvalues = ""

        If ValidateForm() = False Then
            Exit Sub
        End If

        Dim lcus_cndnyear As String = ""
        If cus_cndnyear.SelectedIndex < 0 Then
            lcus_cndnyear = ""
        Else
            lcus_cndnyear = cus_cndnyear.SelectedItem.Value
        End If

        Dim lcus_cndnmth As String = ""
        If cus_cndnmth.SelectedIndex < 0 Then
            lcus_cndnmth = ""
        Else
            lcus_cndnmth = cus_cndnmth.SelectedItem.Value
        End If

        wfb_bar.DocumentAmt = cus_cndnamt.Text

        Try
            If rid.Value = "" Then
                '********************
                ucode.Value = WebLib.getUniqueKey
                Dim lID As String
                Dim lDocno As String = ""
                lDocno = WebLib.GetDocNo(NmSpaceDocNo, "cus_uno", APPCode) & ""
                If lDocno.Trim = "" Then
                    lblMessage.Text = WebLib.getAlertMessageStyle("Document No. Not Set")
                    Exit Sub
                End If

                lID = WebLib.GetValue("Workflowlink", "wfl_wflowid", "wfl_subcode", "'" & FORMCODE & "'", "", "")
                If IsNumeric(lID) = False Or (lID & "").Trim = "0" Then
                    lblMessage.Text = WebLib.getAlertMessageStyle("No Workflow Assign for this form")
                    Exit Sub
                End If

                lsql = wfb_bar.GetWorkFlowSaveSQL(lID, ucode.Value, True, cus_refno.Text, NmSpace, _FormsName, cus_company.Text, lDocno)
                '*********************

                '**** CUSTOMISED ******'

                If cansaveitems() = True Then
                    If (lsql & "").Trim <> "" Then
                        lsql = lsql & ";"
                    End If
                    lsql = lsql & SaveItems(ucode.Value)
                    '*****
                End If

                insertfields = insertfields & "cus_merchantid"
                insertvalues = insertvalues & "'" & ccode.Value.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_uno"
                insertvalues = insertvalues & ",'" & lDocno & "'"
                insertfields = insertfields & ",cus_filter"
                insertvalues = insertvalues & ",'" & WebLib.FilterCode.replace("'", "''") & "'"
                insertfields = insertfields & ",cus_ucode"
                insertvalues = insertvalues & ",'" & ucode.Value & "'"
                insertfields = insertfields & ",cus_custcode"
                insertvalues = insertvalues & ",'" & ccode.Value.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_company"
                insertvalues = insertvalues & ",'" & cus_company.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_refno"
                insertvalues = insertvalues & ",'" & cus_refno.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks1"
                'insertvalues = insertvalues & ",'" & cus_remarks2.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks2"
                'insertvalues = insertvalues & ",'" & cus_remarks2.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks3"
                'insertvalues = insertvalues & ",'" & cus_remarks3.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks4"
                'insertvalues = insertvalues & ",'" & cus_remarks4.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks5"
                'insertvalues = insertvalues & ",'" & cus_remarks5.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks6"
                'insertvalues = insertvalues & ",'" & cus_remarks6.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks7"
                'insertvalues = insertvalues & ",'" & cus_remarks7.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks8"
                'insertvalues = insertvalues & ",'" & cus_remarks8.Text.Replace("'", "''") & "'"


                '*** custom ***************************
                insertfields = insertfields & ",cus_type"
                insertvalues = insertvalues & ",'" & FORMCODE & "'"
                insertfields = insertfields & ",cus_cndnamt"
                insertvalues = insertvalues & "," & cus_cndnamt.Text.Replace("'", "''") & ""
                insertfields = insertfields & ",cus_doc1"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_doc1.Checked) & ""
                insertfields = insertfields & ",cus_doc2"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_doc2.Checked) & ""
                insertfields = insertfields & ",cus_doc3"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_doc3.Checked) & ""
                insertfields = insertfields & ",cus_doc4"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_doc4.Checked) & ""
                insertfields = insertfields & ",cus_doc5"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_doc5.Checked) & ""
                insertfields = insertfields & ",cus_doc6"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_doc6.Checked) & ""
                insertfields = insertfields & ",cus_doc7"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_doc7.Checked) & ""
                insertfields = insertfields & ",cus_doc8"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_doc8.Checked) & ""
                insertfields = insertfields & ",cus_workings"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_workings.Checked) & ""
                insertfields = insertfields & ",cus_documents"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_documents.Checked) & ""
                insertfields = insertfields & ",cus_justification"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_justification.Checked) & ""
                insertfields = insertfields & ",cus_cndntype"
                insertvalues = insertvalues & ",'" & cus_cndntype.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_cndnreason"
                insertvalues = insertvalues & ",'" & cus_cndnreason.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_cndnmth"
                insertvalues = insertvalues & ",'" & lcus_cndnmth & "'"
                insertfields = insertfields & ",cus_cndnyear"
                insertvalues = insertvalues & "," & lcus_cndnyear & ""

                '*******************************

                insertfields = insertfields & ",cus_createby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",cus_createdt"
                insertvalues = insertvalues & ",getdate()"
                insertfields = insertfields & ",cus_updateby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",cus_updatedt"
                insertvalues = insertvalues & ",getdate()"
                insertfields = insertfields & ",cus_accountholder"
                insertvalues = insertvalues & ",'" & cus_accountholder.SelectedValue & "'"

            Else
                If pWorkflowAction = True Then
                    lsql = wfb_bar.getapprovesql(pType)
                End If

                If cansaveitems() = True Then
                    If (lsql & "").Trim <> "" Then
                        lsql = lsql & ";"
                    End If
                    lsql = lsql & SaveItems(ucode.Value)
                    '*****
                End If

                insertvalues = insertvalues & "cus_updateby='" & WebLib.LoginUser.replace("'", "''") & "'"
                insertvalues = insertvalues & ",cus_updatedt=getdate()"
                If cus_company.Enabled = True Then
                    insertvalues = insertvalues & ",cus_company='" & cus_company.Text.Replace("'", "''") & "'"
                End If
                'If cus_remarks1.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks1='" & cus_remarks1.Text.Replace("'", "''") & "'"
                'End If
                'If cus_remarks2.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks2='" & cus_remarks2.Text.Replace("'", "''") & "'"
                'End If
                'If cus_remarks3.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks3='" & cus_remarks3.Text.Replace("'", "''") & "'"
                'End If
                'If cus_remarks4.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks4='" & cus_remarks4.Text.Replace("'", "''") & "'"
                'End If
                'If cus_remarks5.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks5='" & cus_remarks5.Text.Replace("'", "''") & "'"
                'End If
                'If cus_remarks6.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks6='" & cus_remarks6.Text.Replace("'", "''") & "'"
                'End If
                'If cus_remarks7.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks7='" & cus_remarks7.Text.Replace("'", "''") & "'"
                'End If
                'If cus_remarks8.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks8='" & cus_remarks8.Text.Replace("'", "''") & "'"
                'End If

                '********** CUSTOM ***************

                If cus_cndnamt.Enabled = True Then
                    insertvalues = insertvalues & ",cus_cndnamt=" & cus_cndnamt.Text.Replace("'", "''") & ""
                End If
                If cus_doc1.Enabled = True Then
                    insertvalues = insertvalues & ",cus_doc1=" & WebLib.BooleanToBit(cus_doc1.Checked) & ""
                End If
                If cus_doc2.Enabled = True Then
                    insertvalues = insertvalues & ",cus_doc2=" & WebLib.BooleanToBit(cus_doc2.Checked) & ""
                End If
                If cus_doc3.Enabled = True Then
                    insertvalues = insertvalues & ",cus_doc3=" & WebLib.BooleanToBit(cus_doc3.Checked) & ""
                End If
                If cus_doc4.Enabled = True Then
                    insertvalues = insertvalues & ",cus_doc4=" & WebLib.BooleanToBit(cus_doc4.Checked) & ""
                End If
                If cus_doc5.Enabled = True Then
                    insertvalues = insertvalues & ",cus_doc5=" & WebLib.BooleanToBit(cus_doc5.Checked) & ""
                End If
                If cus_doc6.Enabled = True Then
                    insertvalues = insertvalues & ",cus_doc6=" & WebLib.BooleanToBit(cus_doc6.Checked) & ""
                End If
                If cus_doc7.Enabled = True Then
                    insertvalues = insertvalues & ",cus_doc7=" & WebLib.BooleanToBit(cus_doc7.Checked) & ""
                End If
                If cus_doc8.Enabled = True Then
                    insertvalues = insertvalues & ",cus_doc8=" & WebLib.BooleanToBit(cus_doc8.Checked) & ""
                End If
                If cus_workings.Enabled = True Then
                    insertvalues = insertvalues & ",cus_workings=" & WebLib.BooleanToBit(cus_workings.Checked) & ""
                End If
                If cus_documents.Enabled = True Then
                    insertvalues = insertvalues & ",cus_documents=" & WebLib.BooleanToBit(cus_documents.Checked) & ""
                End If
                If cus_justification.Enabled = True Then
                    insertvalues = insertvalues & ",cus_justification=" & WebLib.BooleanToBit(cus_justification.Checked) & ""
                End If
                If cus_cndntype.Enabled = True Then
                    insertvalues = insertvalues & ",cus_cndntype='" & cus_cndntype.Text.Replace("'", "''") & "'"
                End If
                If cus_cndnreason.Enabled = True Then
                    insertvalues = insertvalues & ",cus_cndnreason='" & cus_cndnreason.Text.Replace("'", "''") & "'"
                End If
                If cus_cndnyear.Enabled = True Then
                    insertvalues = insertvalues & ",cus_cndnyear=" & lcus_cndnyear
                End If
                If cus_cndnmth.Enabled = True Then
                    insertvalues = insertvalues & ",cus_cndnmth='" & lcus_cndnmth & "'"
                End If
                If cus_accountholder.Enabled = True Then
                    insertvalues = insertvalues & ",cus_accountholder='" & cus_accountholder.SelectedValue & "'"
                End If
                '********************************
            End If

            Dim lsqlcom As String = ""
            lsqlcom = lsqlcom & "'" & WebLib.LoginUser.replace("'", "''") & "'"

            If pWorkflowAction Then
                Select Case wfb_bar.wlevelAPget().tostring.trim
                    Case "2"
                        Dim str As String = ""
                        If cus_justification.Checked = True Then
                            str = str & " Justification "
                        End If
                        If cus_workings.Checked = True Then
                            If str <> "" Then
                                str = str & " & "
                            End If
                            str = str & " Workings "
                        End If
                        If cus_documents.Checked = True Then
                            If str <> "" Then
                                str = str & " & "
                            End If
                            str = str & " Documents "
                        End If
                        If str <> "" Then
                            lsqlcom = lsqlcom & ", 'Validation - " & str & "'"
                        Else
                            lsqlcom = lsqlcom & ",'No Validation'"
                        End If
                    Case Else
                        lsqlcom = lsqlcom & ",'" & IIf(cus_remarks.Text = "", "[Please refer to above section.]", cus_remarks.Text.Replace("'", "''")) & "'"
                End Select
            Else
                lsqlcom = lsqlcom & ",'" & IIf(cus_remarks.Text = "", "[Please refer to above section.]", cus_remarks.Text.Replace("'", "''")) & "'"
            End If

            lsqlcom = lsqlcom & ",getdate()"

            wfb_bar.postComments(lsqlcom, TableName, pWorkflowAction)


            If savedata(insertfields, insertvalues, True, lsql) = True Then
                If pType = "" Then
                    pType = "route"
                End If

                If pWorkflowAction = True Then
                    If wfb_bar.notifyusers(pType) = False Then

                    End If
                End If
                Response.Redirect("~/" & Redirector.Redirect(NmSpace, ucode.Value, False))
            Else
                'Response.Write(WebLib.ErrorTrap)
                lblMessage.Text = WebLib.getAlertMessageStyle("There is an error while saving. Please retry")
            End If
        Catch Err As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(Err.Message)
        Finally
        End Try
    End Sub

    Private Sub updatetotals(ByVal pReset As Boolean)
        Try
            If pReset = True Then
                fsubtotal = 0
                fgranttotal = 0
                fless = 0
                fgst = 0
                ftotalqty = 0
                ftotaldiff = 0
            End If

            Dim objdata As Literal
            objdata = Page.FindControl("litgst")
            If Not objdata Is Nothing Then
                objdata.Text = WebLib.formatthemoney(fgst)
            End If

            objdata = Page.FindControl("littotal")
            If Not objdata Is Nothing Then
                objdata.Text = WebLib.formatthemoney(fgranttotal)
            End If

            objdata = Page.FindControl("litsubtotal")
            If Not objdata Is Nothing Then
                objdata.Text = WebLib.formatthemoney(fsubtotal)
            End If

            objdata = Page.FindControl("littotalqty")
            If Not objdata Is Nothing Then
                objdata.Text = WebLib.formatthemoney(ftotalqty)
            End If

            objdata = Page.FindControl("littotaldiff")
            If Not objdata Is Nothing Then
                objdata.Text = WebLib.formatthemoney(ftotaldiff)
            End If

            cus_cndnamt.Text = WebLib.formatthemoney(fgranttotal)
            cus_cndnamt.Enabled = False

        Catch ex As Exception
        End Try
    End Sub

    Public Sub savepage(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Call savedatadata(False, "")
    End Sub

    Protected Sub wfb_bar_OnApproveEvent(ByVal sender As Object, ByVal e As EventArgs) Handles wfb_bar.OnApproveEvent
        Call savedatadata(True, "Approve")
    End Sub

    Protected Sub wfb_bar_OnRejectEvent(ByVal sender As Object, ByVal e As EventArgs) Handles wfb_bar.OnRejectEvent
        Call savedatadata(True, "Reject")
    End Sub

    Protected Sub wfb_bar_OnCancelEvent(ByVal sender As Object, ByVal e As EventArgs) Handles wfb_bar.OnCancelEvent
        Call savedatadata(True, "Cancel")
    End Sub

    Public Sub loadpr()
        Try
            rep_comment.DataSource = wfb_bar.getComments2()
            rep_comment.DataBind()
            rep_audit.DataSource = wfb_bar.GetAuditLogsDs2()
            rep_audit.DataBind()
        Catch ex As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
        End Try
    End Sub

    Public Sub loaddraft()
        Try
            cus_remarks.Text = wfb_bar.getDraft2()
        Catch ex As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
        End Try
    End Sub

End Class

