<%@ Page Language="VB" AutoEventWireup="false" EnableViewState="True" CodeFile="stS_list.aspx.vb" Inherits="stS_list_class" %>

<%@ Register Src="~/UserControls/DatePicker.ascx" TagPrefix="uc" TagName="DatePicker" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <!--Generated by ViSoftLabs Forms Generator (http:// www.vifeandi.net)-->
    <meta content="" charset="utf-8"/>
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
    <!--#include File="../../topinitdetail.aspx"-->
    <!--#include File="../../topmobilecss.aspx"-->
    <script type="">
        $(function () {
            $("input[type=submit], button")
            .button()
            var div1 = $("#divnavi").accordion({ collapsible: false, heightStyle: "content", active: 0 });
            var div2 = $("#divsearch").accordion({ collapsible: false, heightStyle: "content", active: 0 });
            var div3 = $("#divdata");
            div1.show();
            div2.show();
            div3.show();
        });
    </script>
    <!--#include File="../../topscriptdetail.aspx"-->
</head>
<body>
    <form id="frmform" runat="server">
        <!--#include File="../../include/FormHeader1.aspx"-->

        <div class=" container-fluid bg-light" style="font-size: 1rem;">
            <div class="row listpage">
                <div class="col-md-2 bg-light ">
                    <div style="padding-top: 1em; font-size: 0.8rem; text-align: left;">
                        <div class="card">
                            <div class="card-header">
                                <h6>
                                    <a data-toggle="collapse" href="#opt" aria-expanded="false" aria-controls="opt">
                                        <i class="fa fa-ellipsis-v"></i> Options Menu
                                    </a>
                                </h6>
                            </div>
                            <div id="opt" class="collapse">
                                <div class="card-body">
                                    <asp:Button ID="btnadd" CssClass="btn btn-info btn-sm w-100" Text="Add New Record" runat="server" OnClick="addeventadd" Style="width: 160px" Enabled="false"/><br />
                                    <br />

                                    <b>View Document by Status:-</b><br />
                                    <asp:Button ID="btnmy" CssClass="btn btn-info btn-sm w-100" Text="My Action Inbox" runat="server" OnClick="shortcutmy" Style="width: 160px" CausesValidation="false" /><br />
                                    <hr class="cssdivider" style="width: 100%" />
                                    <asp:PlaceHolder ID="phFilters" runat="server"></asp:PlaceHolder>

                                    <hr class="cssdivider" style="width: 100%" />
                                    <asp:Button ID="btn1" CssClass="btn btn-info btn-sm w-100 m-1" Text="Pending" runat="server" OnClick="shortcut1" Style="width: 160px" CausesValidation="false" />
                                    <asp:Button ID="btn2" CssClass="btn btn-info btn-sm w-100 m-1" Text="Approved" runat="server" OnClick="shortcut2" Style="width: 160px" CausesValidation="false" />

                                    <asp:Button ID="btn3" CssClass="btn btn-info btn-sm w-100 m-1" Text="Cancelled" runat="server" OnClick="shortcut3" Style="width: 160px" CausesValidation="false" />

                                    <asp:Button ID="btn5" CssClass="btn btn-info btn-sm w-100 m-1" Text="Rejected" runat="server" OnClick="shortcut4" Style="width: 160px" CausesValidation="false" />


                                    <asp:Button ID="btnback" CssClass="btn btn-info btn-sm w-100" Text="Back to Listing" runat="server" OnClick="backpage" Style="width: 160px" CausesValidation="false" />
                                    <br />
                                    <b>Messages:</b><br />
                                    <asp:Label ID="lblMessage" runat="server" class="cssrequired"></asp:Label>
                                </div>
                            </div>

                        </div>
                    </div>
                    <br class="adddet" />
                    <div style="text-align: left; font-size: 0.8rem;">
                        <div class="card">
                            <div class="card-header">
                                <h6>
                                    <a data-toggle="collapse" href="#search" aria-expanded="false" aria-controls="search">
                                        <i class="fa fa-search-plus"></i> Search Menu
                                    </a>
                                </h6>
                            </div>
                            <div id="search" class="collapse">
                                <div class="card-body">
                                    <b>Please enter search key:</b><br />
                                    <asp:TextBox ID="search_key1" runat="server" Columns="23" MaxLength="50" Width="100%"></asp:TextBox><br />
                                    Search Field:<br />
                                    <asp:PlaceHolder ID="phSearchFields" runat="server"></asp:PlaceHolder>

                                    <hr class="cssdivider" width="100%" runat="server" id="hrdate" />

                                    <uc:datepicker ID="uc_from" runat="server" AllowNull="false" Width="72px" PlaceHolder="From Date" />
                                    <uc:datepicker ID="uc_to" runat="server" AllowNull="false" Width="72px" PlaceHolder="To Date" />
                                    <br />
                                    <asp:PlaceHolder ID="phSearchDate" runat="server"></asp:PlaceHolder>

                                    <asp:Button ID="btnsearch" CssClass="btn btn-sm btn-info w-100" Text="Search" runat="server" OnClick="SearchStr" Style="width: 150px" />
                                    <br />
                                    <br />
                                    <%--<asp:Button ID="btnadvsearch" CssClass="btn btn-sm btn-info w-100" Text="Advance Search" runat="server" OnClick="triggersearch" Style="width: 150px" />--%>
                                    <button id="btnadvsearch" type="button" class="btn btn-sm btn-info w-100" data-toggle="modal" data-target="#advsearch">Advance Search</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-md-10 bg-white">
                    <asp:Literal ID="filterhead" runat="server"></asp:Literal>
                    <div style="padding-top: 1em;">
                        <div class="ui-widget-header alert p-1 form-fonts w-100  bg-header " role="alert" style="text-align: left; padding-left: 1em!important; margin-bottom: 1em!important">
                            <%=_formsname%>
                        </div>
                    </div>
                    <table id="table_listing" class="table table-borderless dt-responsive nowrap" width="100%" style="height: 100%; font-size: 0.8rem;" cellpadding="2" cellspacing="1">
                        <thead>
                            <tr>
                                <%--<th class="cssdetail" data-priority="1">&nbsp;</th>
                                <th class="cssdetail">Distributor</th>
                                <th class="cssdetail"><b>Customer</b></th>
                                <th class="cssdetail">Doc Type</th>
                                <th class="cssdetail" data-priority="2">Doc Ref</th>
                                <th class="cssdetail">Created By</th>
                                <th class="cssdetail" data-priority="3">Status</th>
                                <th class="cssdetail">Last Action On</th>
                                <th class="cssdetail"></th>--%>

                                <th class="cssdetail" data-priority="1">&nbsp;</th>
                                <th class="cssdetail">Task Number</th>
                                <th class="cssdetail">Support Ticket Number</th>
                                <th class="cssdetail">Issue Type</th>
                                <th class="cssdetail" data-priority="2">Priority</th>
                                <th class="cssdetail">Testing Status</th>
                                <th class="cssdetail">Created By</th>
                                <th class="cssdetail" data-priority="3">Status</th>
                                <th class="cssdetail">Last Action On</th>
                                <th class="cssdetail"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <asp:Repeater ID="rep" runat="server" OnItemCommand="rep_ItemCommand">
                                <ItemTemplate>
                                    <tr id="trRow" class="ui-widget-content" runat="server">
                                        <td align="center" class="cssdetail" width="48px" style="border-bottom: solid 1px silver" valign="top">
                                            <asp:Literal ID="litimage" runat="server"></asp:Literal>
                                        </td>
                                        <td class="cssdetail" style="border-bottom: solid 1px silver">
                                            <asp:Literal ID="taskno" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "cus_taskno")%>'></asp:Literal>
                                        </td>
                                        <td class="cssdetail" style="border-bottom: solid 1px silver">
                                            <asp:Literal ID="stno" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "cus_stno")%>'></asp:Literal>
                                        </td>
                                        <td class="cssdetail" style="border-bottom: solid 1px silver">
                                            <asp:Literal ID="issuetype" runat="server" Text='<%# "<b>" + DataBinder.Eval(Container.DataItem, "cus_issuetype") + " </b>" %>'></asp:Literal>
                                        </td>
                                        <td class="cssdetail" style="border-bottom: solid 1px silver">
                                            <asp:Literal ID="priority" runat="server" Text='<%# "<b>" + DataBinder.Eval(Container.DataItem, "cus_priority") + " </b>" %>'></asp:Literal>
                                        </td>
                                        <td class="cssdetail" style="border-bottom: solid 1px silver">
                                             <asp:Literal ID="testingstatus" runat="server" Text='<%# "<b>" + DataBinder.Eval(Container.DataItem, "cus_testingstatus") + " </b>" %>'></asp:Literal>
                                        </td>
                                       <%-- <td class="cssdetail" style="border-bottom: solid 1px silver">
                                            <asp:Literal ID="Literal2" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "cus_uno") + If(DataBinder.Eval(Container.DataItem, "wst_refno").ToString() = "", "", "<br/>( Ticket No. " + DataBinder.Eval(Container.DataItem, "wst_refno") + " )")%>'></asp:Literal>
                                        </td>--%>
                                        <td class="cssdetail" style="border-bottom: solid 1px silver">
                                            <asp:Literal ID="Literal3" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "usr_name") + " " + DataBinder.Eval(Container.DataItem, "wst_createon")%>'></asp:Literal>
                                        </td>
                                        <td class="cssdetail" style="border-bottom: solid 1px silver">
                                            <asp:Literal ID="Literal5" runat="server" Text=' <%# "<b>" + If(Eval("wst_status").ToString() = "Pending", "Pending <b>" + DataBinder.Eval(Container.DataItem, "ApprovalLevelName") + "</b>", DataBinder.Eval(Container.DataItem, "wst_status")) + " </b>" %>'></asp:Literal>
                                        </td>
                                        <td class="cssdetail" style="border-bottom: solid 1px silver">
                                            <asp:Literal ID="Literal4" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "wst_lastupdateon")%>'></asp:Literal>
                                        </td>
                                        <td class="cssdetail" style="border-bottom: solid 1px silver">
                                            <a href='<%# WebLib.ClientURL(Redirector.Redirect(DataBinder.Eval(Container.DataItem, "wst_module"), DataBinder.Eval(Container.DataItem, "wst_ucode"))) %>'>View Document</a>
                                        </td>
                                    </tr>
                                </ItemTemplate>
                            </asp:Repeater>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="advsearch" role="dialog">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4>Advance Search</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <p>CR / Issue Task no.</p>
                        <asp:TextBox ID="docno" runat="server" type="text" Style="width: 100%" MaxLength="50"></asp:TextBox>
                        <br />
                        <br />
                        <p>Support Ticket no.</p>
                        <asp:TextBox ID="stno" runat="server" type="text" Style="width: 100%" MaxLength="50"></asp:TextBox>
                        <br />
                        <br />
                        <p>Title</p>
                        <asp:TextBox ID="requestTitle" runat="server" type="text" Style="width: 100%" MaxLength="50"></asp:TextBox>
                        <br />
                        <br />
                        <p>Department</p>
                        <asp:DropDownList ID="dept" runat="server" Style="width: 100%" MaxLength="50"></asp:DropDownList>
                        <br />
                        <br />
                        <p>1st level Category</p>
                        <asp:DropDownList ID="category" runat="server" Style="width: 100%" MaxLength="50"></asp:DropDownList>
                        <br />
                        <br />
                        <p>2nd level Module</p>
                        <asp:DropDownList ID="module1" runat="server" Style="width: 100%" MaxLength="50"></asp:DropDownList>
                        <br />
                        <br />
                        <p>Customer</p>
                        <asp:DropDownList ID="customer" runat="server" Style="width: 100%" MaxLength="50"></asp:DropDownList>
                        <br />
                        <br />
                        <p>Priority</p>
                        <asp:DropDownList ID="priority1" runat="server" Style="width: 100%" MaxLength="50"></asp:DropDownList>
                        <br />
                        <br />
                        <p>Technical Requirement</p>
                        <asp:TextBox ID="techReq" runat="server" type="text" TextMode="MultiLine" Style="width: 100%; height: 100px" MaxLength="500"></asp:TextBox>
                        <br />
                        <br />
                        <p>Tags</p>
                        <asp:CheckBoxList runat="server" ID="tags" RepeatDirection="Horizontal" />
                        <br />

                        <p>Status</p>
                        <asp:DropDownList ID="status" runat="server" Style="width: 100%" MaxLength="50">
                            <asp:ListItem Value="" Text="Please Select" ></asp:ListItem>
                            <asp:ListItem Value="Pending" Text="Pending" ></asp:ListItem>
                            <asp:ListItem Value="Approved" Text="Approved" ></asp:ListItem>
                            <asp:ListItem Value="Cancelled" Text="Cancelled" ></asp:ListItem>
                            <asp:ListItem Value="Rejected" Text="Rejected" ></asp:ListItem>
                        </asp:DropDownList>                        <br />
                        <br />
                        <p>Pending on level?</p>
                        <asp:DropDownList ID="pendinglevel" runat="server" Style="width: 100%" MaxLength="50"></asp:DropDownList>
                        <br />
                        <br />
                        <p>Pending on who?</p>
                        <asp:DropDownList ID="pendingperson" runat="server" Style="width: 100%" MaxLength="50"></asp:DropDownList>
                        <br />
                        <br />
                        <br />
                        <uc:DatePicker ID="fromdate" runat="server" AllowNull="false" Width="380px" PlaceHolder="From Date" />
                        <uc:DatePicker ID="todate" runat="server" AllowNull="false" Width="380px" PlaceHolder="To Date" />
                    </div>
                    <div class="modal-footer">
                        <asp:Button ID="Button1" class="btn btn-default" Text="Search" runat="server" OnClick="SearchtheData" Style="width: 100px" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <input type="hidden" runat="server" id="wfid" name="wfid" />
        <input type="hidden" runat="server" id="rid" name="rid" />
        <input type="hidden" runat="server" id="bid" name="bid" />
        <!--#include File="../../include/FormFooter1.aspx"-->
        <hr width="100%" />
    </form>
    <!--#include File="../../include/footerscript.aspx"-->

    <script type="text/javascript">
        $(document).ready(function () {
            $('#table_listing').DataTable({
                responsive: true,
                "info": true,
                "bFilter": false
            });
        });
    </script>
</body>
</html>

