Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.OleDb
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls

Partial Public Class tempcl_class
    Inherits detailspage
    Private FORMCODE As String = "TEMPCL"  'Hardcoded for customised form
    Private f_size As String
    Private f_securities As String = String.Empty & "|-Please Select-;;BG|BG;;CG|CG;;PG|PG"
    Private f_custype As String = "1|New;;2|Existing"


    'Generated by VI FEANDI SOFTLABS FORM GENERATOR (http://www.vifeandi.net) VER 2014.1

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        listingpage = "wlist.aspx"
        _FormsName = "Application for Temporary Credit Limit"
        TableName = "[zcustom_tempcl]"
        IDPField = ""
        IDField = "cus_id"
        AppIDField = ""
        MerchantIDField = "cus_merchantid"
        FilterField = "cus_filter"
        APPCode = "WORKFLOW"
        AddRights = ""
        DelRights = ""
        ModRights = ""
        ViewRights = ""
        FullRights = "TC0005"
        NmSpace = "zcustom_tempcl"

        wfb_bar.workflownamespace = NmSpace
        wfb_bar.custommode = True
        wfb_bar.overridemode = True
        wfb_bar.attachmentbycreatoronly = True
        cus_custype.Enabled = False

        If Page.IsPostBack = False Then
            cus_creditfile.Checked = True
            lblrefno.Text = "<b>Auto Generated</b>"

            cus_refno.Text = Request("rc") & ""
            WebLib.SetListItems(cus_custype, f_custype)

            If (Request("wp2") & "").Trim <> "" Then '2 always use for custcode
                Dim obj As New RuntimeCustomer
                Call obj.getInfo((Request("wp2") & "").Trim)
                ccode.Value = (Request("wp2") & "").Trim
                cus_company.Text = obj.CustName & ""
                Dim templi As ListItem
                templi = cus_custype.Items.FindByValue(2)
                cus_custype.SelectedIndex = cus_custype.Items.IndexOf(templi)
                obj = Nothing
            Else
                Dim templi As ListItem
                templi = cus_custype.Items.FindByValue(1)
                cus_custype.SelectedIndex = cus_custype.Items.IndexOf(templi)

                'New customer got no customer credit limit
                cus_amt.Enabled = False
                cus_amt.Text = "0.00"
            End If

            cus_accountholder.DataSource = backend.GetAccountHolders(WebLib.LoginUserCompanySelected)
            cus_accountholder.DataValueField = "salesrepcode"
            cus_accountholder.DataTextField = "usr_name"
            cus_accountholder.DataBind()
            cus_accountholder.Items.Insert(0, New ListItem("Please Select", ""))
        End If

        createdt.Value = DateTime.Now
        cus_refno.ReadOnly = True

        Call InitLoad()
        Call enabledisablecustomer()

        wfb_bar.parentobj = mp

        Call assigninitvalues()

        If (wfb_bar.canAction()) Then
            lvlvalid.Value = "True"
        Else
            lvlvalid.Value = "False"
        End If

        If (WebLib.LoginIsFullAdmin = True And wfb_bar.Workflowended = False) Or (IsNumeric(rid.Value) = False And cus_accountholder.SelectedValue = "") Then
            cus_accountholder.Enabled = True
        Else
            cus_accountholder.Enabled = False
        End If

        loadpr()
    End Sub

    Private Sub enabledisablecustomer()
        If cus_company.Enabled = True Then
            If cus_custype.SelectedIndex >= 0 Then
                If cus_custype.SelectedItem.Value = 1 Then
                    cus_company.Enabled = True
                    cus_amt.Enabled = False
                    If IsNumeric(cus_amt.Text) = False Then
                        cus_amt.Text = "0.00"
                    End If
                Else
                    cus_company.Enabled = False
                    cus_amt.Enabled = True
                End If
            End If
        End If
    End Sub

    Private Function ValidateForm()
        lblMessage.Text = ""

        If cus_custype.SelectedIndex < 0 Then
            lblMessage.Text = WebLib.getAlertMessageStyle(" New/Existing Customer Not Defined")
            Return False
        End If

        If cus_cgname.Text.Trim = "" Then
            '   cus_cgname.text = "Nil"
        Else
            If cus_cgpaidup.Enabled = True Then
                If IsNumeric(cus_cgpaidup.Text) = False Then
                    lblMessage.Text = WebLib.getAlertMessageStyle("Please Enter Corporate Guarantor Paid Up Capital")
                    Return False
                End If
            End If
            If cus_cgnettworth.Enabled = True Then
                If IsNumeric(cus_cgnettworth.Text) = False Then
                    lblMessage.Text = WebLib.getAlertMessageStyle("Please Enter Corporate Guarantor Nett Worth")
                    Return False
                End If
            End If
            If cus_cgasat.enabled = True Then
                If cus_cgasat.datevalue = New DateTime(1991, 1, 1) Then
                    lblMessage.Text = WebLib.getAlertMessageStyle("Please Enter Valid Corporate Guarantor Nett Worth As At")
                    Return False
                End If
            End If
        End If

        If cus_asat.enabled = True Then
            If (cus_asat.textdmy) <> "" Then
                If cus_asat.datevalue = New DateTime(1991, 1, 1) Then
                    lblMessage.Text = WebLib.getAlertMessageStyle("Please Enter Valid Nett Worth As At")
                    Return False
                End If
            End If
        End If

        If cus_cgasat.enabled = True Then
            If (cus_cgasat.textdmy) <> "" Then
                If cus_cgasat.datevalue = New DateTime(1991, 1, 1) Then
                    lblMessage.Text = WebLib.getAlertMessageStyle("Please Enter Valid Corporate Guarantor Nett Worth As At")
                    Return False
                End If
            End If
        End If

        Return True
    End Function

    Public Sub SetFieldRights()
        Call wfb_bar.EnableDisable(mp)
        Exit Sub
    End Sub

    Private Sub assigninitvalues()
        If cus_cgname.Enabled = False And (cus_cgname.Text & "").Trim = "" Then
            cus_cgname.Text = "Nil"
        End If
        If cus_cgpaidup.Enabled = False And (cus_cgpaidup.Text & "").Trim = "" Then
            cus_cgpaidup.Text = "Nil"
        End If
        If cus_cgnettworth.Enabled = False And (cus_cgnettworth.Text & "").Trim = "" Then
            cus_cgnettworth.Text = "Nil"
        End If
        If cus_cgasat.enabled = False And (cus_cgasat.value & "").trim = "" Then
            cus_cgasat.textdmy = ""
        End If
    End Sub

    Public Sub backpagepage(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Response.Redirect(WebLib.ClientURL(Redirector.PrevURL1))
    End Sub

    Public Overrides Function LoadData() As Boolean
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow
        Dim templi As ListItem

        If IsNumeric(rid.Value) = False Then
            wfb_bar.uid = ""
            Call SetFieldRights()
            cus_accountholder.SelectedValue = backend.GetAccountHolder((Request("wp2") & "").Trim)
            Exit Function
        End If

        Try
            cmd.CommandText = "Select * from zcustom_tempcl where cus_id=" & rid.Value
            cmd.Connection = cn
            ad.SelectCommand = cmd
            ad.Fill(ds, "datarecords")

            For Each dr In ds.Tables("datarecords").Rows
                counter = counter + 1
                cus_company.Text = dr("cus_company") & ""

                Try
                    cus_amt.Text = WebLib.formatthemoney(CDbl(dr("cus_amt") & ""))
                Catch ex As Exception
                End Try
                Try
                    cus_amttemp.Text = WebLib.formatthemoney(CDbl(dr("cus_amttemp") & ""))
                Catch ex As Exception
                End Try
                Try
                    cus_paidup.Text = WebLib.formatthemoney(CDbl(dr("cus_paidup") & ""))
                Catch ex As Exception
                End Try
                Try
                    cus_amtapply.Text = WebLib.formatthemoney(CDbl(dr("cus_amtapply") & ""))
                Catch ex As Exception
                End Try

                ccode.Value = dr("cus_custcode") & ""
                cus_paymentterms.Text = dr("cus_paymentterms") & ""
                ucode.Value = dr("cus_ucode") & ""

                cus_refno.Text = dr("cus_refno") & ""
                lblrefno.Text = dr("cus_uno") & ""
                cus_creditfile.Checked = WebLib.BitToBoolean(dr("cus_creditfile") & "")
                templi = cus_custype.Items.FindByValue(dr("cus_custype") & "")
                cus_custype.SelectedIndex = cus_custype.Items.IndexOf(templi)

                Try
                    cus_nettworth.Text = WebLib.formatthemoney(CDbl(dr("cus_nettworth") & ""))
                Catch ex As Exception
                End Try
                Try
                    cus_asat.Textdmy = dr("cus_asat") & ""
                Catch ex As Exception
                End Try

                cus_cg.Text = dr("cus_cg") & ""

                Try
                    cus_cgnettworth.Text = WebLib.formatthemoney(CDbl(dr("cus_cgnettworth") & ""))
                Catch ex As Exception
                End Try
                Try
                    cus_cgpaidup.Text = WebLib.formatthemoney(CDbl(dr("cus_cgpaidup") & ""))
                Catch ex As Exception
                End Try
                Try
                    cus_cgasat.Textdmy = dr("cus_cgasat") & ""
                Catch ex As Exception
                End Try

                cus_cgname.Text = dr("cus_cgname") & ""
                wfb_bar.uid = ucode.Value
                createdt.Value = dr("cus_createdt").ToString.Trim
                cus_accountholder.SelectedValue = dr("cus_accountholder") & ""

                Exit For
            Next

            cn.Close()
            cmd.Dispose()
            cn.Dispose()

            If wfb_bar.Workflowended = True Then
                btnsave.enabled = False
            Else
                btnsave.enabled = True
            End If

            Call SetFieldRights()
            Call enabledisablecustomer()

            loaddraft()

        Catch ex As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
        End Try
    End Function

    Private Sub savedatadata(ByVal pWorkflowAction As Boolean, ByVal pType As String, Optional ByVal cancelled As Boolean = False)
        Dim insertfields, insertvalues As String
        Dim newform As Boolean = False
        Dim savedDraft As String = ""
        Dim lsrdesc As String = ""
        Dim lsql As String = ""
        insertfields = ""
        insertvalues = ""

        If ValidateForm() = False Then
            Exit Sub
        End If

        Dim lcgNett As String
        If IsNumeric(cus_cgnettworth.Text) = False Then
            lcgNett = "NULL"
        Else
            lcgNett = CDbl(cus_cgnettworth.Text)
        End If

        Dim lcgPaidUp As String
        If IsNumeric(cus_cgpaidup.Text) = False Then
            lcgPaidUp = "NULL"
        Else
            lcgPaidUp = CDbl(cus_cgpaidup.Text)
        End If

        Dim lcgAsAt As String = ""
        If cus_cgasat.enabled = True Then
            If cus_cgasat.datevalue = New DateTime(1991, 1, 1) Then
                lcgAsAt = "NULL"
            Else
                lcgAsAt = "'" & WebLib.formatthedate(cus_cgasat.datevalue) & "'"
            End If
        End If

        Dim lAsAt As String = ""
        If cus_asat.enabled = True Then
            If cus_asat.datevalue = New DateTime(1991, 1, 1) Then
                lAsAt = "NULL"
            Else
                lAsAt = "'" & WebLib.formatthedate(cus_asat.datevalue) & "'"
            End If
        End If

        If IIf(createdt.Value = "", Today.Date, createdt.Value) >= New DateTime(2021, 12, 1) Then
            If cus_custype.SelectedItem.Text = "New" Then
                If wfb_bar.wlevelAget() <> "" Then
                    If wfb_bar.wlevelNameget() = "Intermediate Group President" Then
                        wfb_bar.wfAppLimit = "800000.00"
                    End If
                End If
                wfb_bar.DocumentAmt = cus_amttemp.Text

            ElseIf cus_custype.SelectedItem.Text = "Existing" Then
                Dim calculatedCL As Double
                calculatedCL = CDbl(cus_amt.Text) * CDbl(ConfigurationManager.AppSettings("WfTCLPtg"))

                If wfb_bar.wlevelAget() <> "" And wfb_bar.wfAppLimit <> "" Then
                    If CDbl(cus_amttemp.Text) > CDbl(calculatedCL) Then ' excess TCL Ptg 20%
                        wfb_bar.DocumentAmt = CDbl(cus_amt.Text) + CDbl(cus_amttemp.Text)
                    Else ' within TCL Ptg 20%
                        wfb_bar.DocumentAmt = CDbl(cus_amttemp.Text)
                    End If
                End If
            End If
        Else
            wfb_bar.DocumentAmt = cus_amttemp.Text
        End If

        Try
            If rid.Value = "" Then
                ucode.Value = WebLib.getUniqueKey

                Dim lID As String
                Dim lDocno As String = ""
                lDocno = WebLib.GetDocNo(NmSpace, "cus_uno", APPCode) & ""
                If lDocno.Trim = "" Then
                    lblMessage.Text = WebLib.getAlertMessageStyle("Document No. Not Set")
                    Exit Sub
                End If

                lID = WebLib.GetValue("Workflowlink", "wfl_wflowid", "wfl_subcode", "'" & FORMCODE & "'", "", "")

                If IsNumeric(lID) = False Or (lID & "").Trim = "0" Then
                    lblMessage.Text = WebLib.getAlertMessageStyle("No Workflow Assign for this form")
                    Exit Sub
                End If

                lsql = wfb_bar.GetWorkFlowSaveSQL(lID, ucode.Value, True, cus_refno.Text, NmSpace, "Application for Temporary Credit Limit", cus_company.Text, lDocno)

                insertfields = insertfields & "cus_merchantid"
                insertvalues = insertvalues & "'" & ccode.Value.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_uno"
                insertvalues = insertvalues & ",'" & lDocno & "'"
                insertfields = insertfields & ",cus_amtapply"
                insertvalues = insertvalues & "," & CDbl(cus_amtapply.Text.Replace("'", "''")) & ""
                insertfields = insertfields & ",cus_filter"
                insertvalues = insertvalues & ",'" & WebLib.FilterCode.replace("'", "''") & "'"
                insertfields = insertfields & ",cus_ucode"
                insertvalues = insertvalues & ",'" & ucode.Value & "'"
                insertfields = insertfields & ",cus_custype"
                insertvalues = insertvalues & ",'" & cus_custype.SelectedItem.Value & "'"
                insertfields = insertfields & ",cus_custcode"
                insertvalues = insertvalues & ",'" & ccode.Value.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_company"
                insertvalues = insertvalues & ",'" & cus_company.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_amt"
                insertvalues = insertvalues & "," & CDbl(cus_amt.Text.Replace("'", "''")) & ""
                insertfields = insertfields & ",cus_amttemp"
                insertvalues = insertvalues & "," & CDbl(cus_amttemp.Text.Replace("'", "''")) & ""
                insertfields = insertfields & ",cus_refno"
                insertvalues = insertvalues & ",'" & cus_refno.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_paidup"
                insertvalues = insertvalues & "," & CDbl(cus_paidup.Text.Replace("'", "''")) & ""
                insertfields = insertfields & ",cus_paymentterms"
                insertvalues = insertvalues & ",'" & cus_paymentterms.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_creditfile"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(cus_creditfile.Checked) & ""
                insertfields = insertfields & ",cus_nettworth"
                insertvalues = insertvalues & "," & CDbl(cus_nettworth.Text.Replace("'", "''")) & ""
                insertfields = insertfields & ",cus_asat"
                insertvalues = insertvalues & "," & lAsAt & ""
                insertfields = insertfields & ",cus_cg"
                insertvalues = insertvalues & ",'" & cus_cg.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_cgnettworth"
                insertvalues = insertvalues & "," & lcgNett & ""
                insertfields = insertfields & ",cus_cgasat"
                insertvalues = insertvalues & "," & lcgAsAt & ""
                insertfields = insertfields & ",cus_cgpaidup"
                insertvalues = insertvalues & "," & lcgPaidUp & ""
                insertfields = insertfields & ",cus_cgname"
                insertvalues = insertvalues & ",'" & cus_cgname.Text.Replace("'", "''") & "'"

                insertfields = insertfields & ",cus_createby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",cus_createdt"
                insertvalues = insertvalues & ",getdate()"
                insertfields = insertfields & ",cus_updateby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",cus_updatedt"
                insertvalues = insertvalues & ",getdate()"
                insertfields = insertfields & ",cus_accountholder"
                insertvalues = insertvalues & ",'" & cus_accountholder.SelectedValue & "'"

            Else
                If pWorkflowAction = True Then
                    lsql = wfb_bar.getapprovesql(pType)
                Else
                    savedDraft = "saved"
                    newform = True
                End If

                insertvalues = insertvalues & "cus_updateby='" & WebLib.LoginUser.replace("'", "''") & "'"
                insertvalues = insertvalues & ",cus_updatedt=getdate()"

                If cus_company.Enabled = True Then
                    insertvalues = insertvalues & ",cus_company='" & cus_company.Text.Replace("'", "''") & "'"
                End If
                If cus_amt.Enabled = True Then
                    insertvalues = insertvalues & ",cus_amt=" & CDbl(cus_amt.Text.Replace("'", "''")) & ""
                End If
                If cus_amttemp.Enabled = True Then
                    insertvalues = insertvalues & ",cus_amttemp=" & CDbl(cus_amttemp.Text.Replace("'", "''")) & ""
                End If
                If cus_amtapply.Enabled = True Then
                    insertvalues = insertvalues & ",cus_amtapply=" & CDbl(cus_amtapply.Text.Replace("'", "''")) & ""
                End If
                If cus_paidup.Enabled = True Then
                    insertvalues = insertvalues & ",cus_paidup=" & CDbl(cus_paidup.Text.Replace("'", "''")) & ""
                End If
                If cus_paymentterms.Enabled = True Then
                    insertvalues = insertvalues & ",cus_paymentterms='" & cus_paymentterms.Text.Replace("'", "''") & "'"
                End If
                If cus_creditfile.Enabled = True Then
                    insertvalues = insertvalues & ",cus_creditfile=" & WebLib.BooleanToBit(cus_creditfile.Checked) & ""
                End If
                If cus_nettworth.Enabled = True Then
                    insertvalues = insertvalues & ",cus_nettworth=" & CDbl(cus_nettworth.Text.Replace("'", "''")) & ""
                End If
                If cus_asat.Enabled = True Then
                    insertvalues = insertvalues & ",cus_asat=" & lAsAt & ""
                End If
                If cus_cg.Enabled = True Then
                    insertvalues = insertvalues & ",cus_cg='" & cus_cg.Text.Replace("'", "''") & "'"
                End If
                If cus_cgname.Enabled = True Then
                    insertvalues = insertvalues & ",cus_cgname='" & cus_cgname.Text.Replace("'", "''") & "'"
                End If
                If cus_cgnettworth.Enabled = True Then
                    insertvalues = insertvalues & ",cus_cgnettworth=" & lcgNett & ""
                End If
                If cus_cgasat.Enabled = True Then
                    insertvalues = insertvalues & ",cus_cgasat=" & lcgAsAt & ""
                End If
                If cus_cgpaidup.Enabled = True Then
                    insertvalues = insertvalues & ",cus_cgpaidup=" & lcgPaidUp & ""
                End If
                If cus_accountholder.Enabled = True Then
                    insertvalues = insertvalues & ",cus_accountholder='" & cus_accountholder.SelectedValue & "'"
                End If
            End If

            Dim lsqlcom As String = ""
            lsqlcom = lsqlcom & "'" & WebLib.LoginUser.replace("'", "''") & "'"
            lsqlcom = lsqlcom & ",'" & IIf(cus_remarks.Text = "", "[Please refer to above section.]", cus_remarks.Text.Replace("'", "''")) & "'"
            lsqlcom = lsqlcom & ",getdate()"

            wfb_bar.postComments(lsqlcom, TableName, pWorkflowAction)

            If savedata(insertfields, insertvalues, True, lsql) = True Then
                If pType = "" Then
                    pType = "route"
                End If

                If pWorkflowAction = True Then
                    If wfb_bar.notifyusers(pType) = False Then
                    End If
                End If

                Response.Redirect("~/" & Redirector.Redirect(NmSpace, ucode.Value, False))
            Else
                lblMessage.Text = WebLib.getAlertMessageStyle("There is an error while saving. Please retry")
            End If

        Catch Err As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(Err.Message)
        Finally
        End Try
    End Sub

    Public Sub savepage(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Call savedatadata(False, "")
    End Sub

    Protected Sub wfb_bar_OnApproveEvent(ByVal sender As Object, ByVal e As EventArgs) Handles wfb_bar.OnApproveEvent
        Call savedatadata(True, "Approve")
    End Sub

    Protected Sub wfb_bar_OnRejectEvent(ByVal sender As Object, ByVal e As EventArgs) Handles wfb_bar.OnRejectEvent
        Call savedatadata(True, "Reject")
    End Sub

    Protected Sub wfb_bar_OnCancelEvent(ByVal sender As Object, ByVal e As EventArgs) Handles wfb_bar.OnCancelEvent
        Call savedatadata(True, "Cancel")
    End Sub

    Public Sub loadpr()
        Try
            rep_comment.DataSource = wfb_bar.getComments2()
            rep_comment.DataBind()
            rep_audit.DataSource = wfb_bar.GetAuditLogsDs2()
            rep_audit.DataBind()
        Catch ex As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
        End Try
    End Sub

    Public Sub loaddraft()
        Try
            cus_remarks.Text = wfb_bar.getDraft2()
        Catch ex As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
        End Try
    End Sub

End Class

