Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.OleDb
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls

Partial Public Class unblockacct_class
    Inherits detailspage
    Private FORMCODE As String = "UNBLOCKACCT"  'Hardcoded for customised form
    Private f_size As String

    'Generated by VI FEANDI SOFTLABS FORM GENERATOR (http://www.vifeandi.net) VER 2014.1

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        listingpage = "wlist.aspx"
        _FormsName = "Requisition for unblock account"
        TableName = "[zcustom_unblockacct]"
        IDPField = ""
        IDField = "cus_id"
        AppIDField = ""
        MerchantIDField = "cus_merchantid"
        FilterField = "cus_filter"
        APPCode = "WORKFLOW"
        AddRights = "" '"SM0001"
        DelRights = "" '"SM0003"
        ModRights = "" '"SM0002"
        ViewRights = "" '"SM0004"
        FullRights = "UA0005"
        NmSpace = "zcustom_unblockacct"

        wfb_bar.workflownamespace = NmSpace
        wfb_bar.custommode = True
        wfb_bar.overridemode = True

        wfb_bar.attachmentbycreatoronly = True

        If Page.IsPostBack = False Then
            lblrefno.Text = "<b>Auto Generated</b>"
            cus_refno.Text = Request("rc") & ""

            If (Request("wp2") & "").Trim <> "" Then '2 always use for custcode
                Dim obj As New RuntimeCustomer
                Call obj.getInfo((Request("wp2") & "").Trim)
                ccode.Value = (Request("wp2") & "").Trim
                cus_company.Text = obj.CustName & ""
                obj = Nothing
            Else
            End If

            cus_accountholder.DataSource = backend.GetAccountHolders(WebLib.LoginUserCompanySelected)
            cus_accountholder.DataValueField = "salesrepcode"
            cus_accountholder.DataTextField = "usr_name"
            cus_accountholder.DataBind()
            cus_accountholder.Items.Insert(0, New ListItem("Please Select", ""))
        End If
        createdt.Value = DateTime.Now

        cus_refno.ReadOnly = True

        Call InitLoad()
        Call enabledisablecustomer()

        wfb_bar.parentobj = mp

        Call assigninitvalues()

        If (wfb_bar.canAction()) Then
            lvlvalid.Value = "True"
        Else
            lvlvalid.Value = "False"
        End If

        If (WebLib.LoginIsFullAdmin = True And wfb_bar.Workflowended = False) Or (IsNumeric(rid.Value) = False And cus_accountholder.SelectedValue = "") Then
            cus_accountholder.Enabled = True
        Else
            cus_accountholder.Enabled = False
        End If

        cus_remarks.ValidationGroup = wfb_bar.wlevelAget().tostring.trim & "-"

        loadpr()

    End Sub

    Private Sub enabledisablecustomer()
        cus_company.Enabled = False
    End Sub

    Private Function ValidateForm()
        lblMessage.Text = ""
        Return True
    End Function

    Public Sub SetFieldRights()
        Call wfb_bar.EnableDisable(mp)
        Exit Sub
    End Sub

    Private Sub assigninitvalues()
    End Sub

    Public Sub backpagepage(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Response.Redirect(WebLib.ClientURL(Redirector.PrevURL1))
    End Sub

    Public Overrides Function LoadData() As Boolean
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow
        Dim templi As ListItem

        If IsNumeric(rid.Value) = False Then
            wfb_bar.uid = ""
            Call SetFieldRights()
            'visibleControl(False)
            cus_accountholder.SelectedValue = backend.GetAccountHolder((Request("wp2") & "").Trim)
            Exit Function
        End If

        Try
            cmd.CommandText = "Select * from " & TableName & " where cus_id=" & rid.Value
            cmd.Connection = cn
            ad.SelectCommand = cmd
            ad.Fill(ds, "datarecords")

            For Each dr In ds.Tables("datarecords").Rows
                counter = counter + 1
                cus_company.Text = dr("cus_company") & ""
                ccode.Value = dr("cus_custcode") & ""
                ucode.Value = dr("cus_ucode") & ""

                Try
                    cus_overdueasat.Textdmy = dr("cus_overdueasat") & ""
                Catch ex As Exception
                End Try

                Try
                    If IsNumeric(dr("cus_overdue") & "") = True Then
                        cus_overdue.Text = WebLib.formatthemoney(CDbl(dr("cus_overdue") & ""))
                    Else
                        cus_overdue.Text = dr("cus_overdue") & ""
                    End If
                Catch ex As Exception
                End Try

                Try
                    cus_committedbydate.Textdmy = dr("cus_committedbydate") & ""
                Catch ex As Exception
                End Try

                Try
                    If IsNumeric(dr("cus_committed") & "") = True Then
                        cus_committed.Text = WebLib.formatthemoney(CDbl(dr("cus_committed") & ""))
                    Else
                        cus_committed.Text = dr("cus_committed") & ""
                    End If
                Catch ex As Exception
                End Try

                Try
                    cus_cnbydate.Textdmy = dr("cus_cnbydate") & ""
                Catch ex As Exception
                End Try

                Try
                    If IsNumeric(dr("cus_cnamt") & "") = True Then
                        cus_cnamt.Text = WebLib.formatthemoney(CDbl(dr("cus_cnamt") & ""))
                    Else
                        cus_cnamt.Text = dr("cus_cnamt") & ""
                    End If
                Catch ex As Exception
                End Try

                'cus_remarks1.Text = dr("cus_remarks1") & ""
                'cus_remarks2.Text = dr("cus_remarks2") & ""
                'cus_remarks3.Text = dr("cus_remarks3") & ""
                'cus_remarks4.Text = dr("cus_remarks4") & ""
                'cus_remarks5.Text = dr("cus_remarks5") & ""
                'cus_remarks6.Text = dr("cus_remarks6") & ""
                'cus_remarks7.Text = dr("cus_remarks7") & ""
                '                cus_remarks8.Text = dr("cus_remarks8") & ""

                cus_refno.Text = dr("cus_refno") & ""
                lblrefno.Text = dr("cus_uno") & ""

                wfb_bar.uid = ucode.Value
                cus_accountholder.SelectedValue = dr("cus_accountholder") & ""
                createdt.Value = dr("cus_createdt").ToString.Trim

                'If dr("cus_updatedt").ToString.Trim >= New DateTime(2019, 5, 28, 0, 0, 0) Or wfb_bar.wstatus.value = "Pending" Then 'Or drv.Row("wst_status").ToString.Trim = "Pending"
                '    visibleControl(False)
                'End If

                Exit For
            Next

            cn.Close()
            cmd.Dispose()
            cn.Dispose()

            If wfb_bar.Workflowended = True Then
                btnsave.enabled = False
            Else
                btnsave.enabled = True
            End If

            Call SetFieldRights()
            Call enabledisablecustomer()

            loaddraft()

        Catch ex As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
        End Try

    End Function

    Private Sub savedatadata(ByVal pWorkflowAction As Boolean, ByVal pType As String)
        Dim insertfields, insertvalues As String
        Dim lsrdesc As String = ""
        Dim lsql As String = ""

        insertfields = ""
        insertvalues = ""

        If ValidateForm() = False Then
            Exit Sub
        End If

        Dim loverduedate As String = ""
        If cus_overdueasat.datevalue = New DateTime(1991, 1, 1) Then
            loverduedate = "NULL"
        Else
            loverduedate = "'" & WebLib.formatthedate(cus_overdueasat.datevalue) & "'"
        End If

        Dim lcommitteddate As String = ""
        If cus_committedbydate.datevalue = New DateTime(1991, 1, 1) Then
            lcommitteddate = "NULL"
        Else
            lcommitteddate = "'" & WebLib.formatthedate(cus_committedbydate.datevalue) & "'"
        End If

        Dim lcndate As String = ""
        If cus_cnbydate.datevalue = New DateTime(1991, 1, 1) Then
            lcndate = "NULL"
        Else
            lcndate = "'" & WebLib.formatthedate(cus_cnbydate.datevalue) & "'"
        End If

        Try
            If rid.Value = "" Then
                ucode.Value = WebLib.getUniqueKey
                Dim lID As String
                Dim lDocno As String = ""
                lDocno = WebLib.GetDocNo(NmSpace, "cus_uno", APPCode) & ""
                If lDocno.Trim = "" Then
                    lblMessage.Text = WebLib.getAlertMessageStyle("Document No. Not Set")
                    Exit Sub
                End If

                lID = WebLib.GetValue("Workflowlink", "wfl_wflowid", "wfl_subcode", "'" & FORMCODE & "'", "", "")
                If IsNumeric(lID) = False Or (lID & "").Trim = "0" Then
                    lblMessage.Text = WebLib.getAlertMessageStyle("No Workflow Assign for this form")
                    Exit Sub
                End If

                lsql = wfb_bar.GetWorkFlowSaveSQL(lID, ucode.Value, True, cus_refno.Text, NmSpace, _FormsName, cus_company.Text, lDocno)

                insertfields = insertfields & "cus_merchantid"
                insertvalues = insertvalues & "'" & ccode.Value.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_uno"
                insertvalues = insertvalues & ",'" & lDocno & "'"
                insertfields = insertfields & ",cus_filter"
                insertvalues = insertvalues & ",'" & WebLib.FilterCode.replace("'", "''") & "'"
                insertfields = insertfields & ",cus_ucode"
                insertvalues = insertvalues & ",'" & ucode.Value & "'"
                insertfields = insertfields & ",cus_custcode"
                insertvalues = insertvalues & ",'" & ccode.Value.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_company"
                insertvalues = insertvalues & ",'" & cus_company.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_refno"
                insertvalues = insertvalues & ",'" & cus_refno.Text.Replace("'", "''") & "'"


                '************************************
                '  insertfields = insertfields & ",cus_remarks1"
                ' insertvalues = insertvalues & ",'" & cus_remarks1.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks2"
                'insertvalues = insertvalues & ",'" & cus_remarks2.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks3"
                'insertvalues = insertvalues & ",'" & cus_remarks3.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks4"
                'insertvalues = insertvalues & ",'" & cus_remarks4.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks5"
                'insertvalues = insertvalues & ",'" & cus_remarks5.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks6"
                'insertvalues = insertvalues & ",'" & cus_remarks6.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",cus_remarks7"
                'insertvalues = insertvalues & ",'" & cus_remarks7.Text.Replace("'", "''") & "'"
                '                insertfields = insertfields & ",cus_remarks8"
                '               insertvalues = insertvalues & ",'" & cus_remarks8.Text.Replace("'", "''") & "'"


                insertfields = insertfields & ",cus_overdueasat"
                insertvalues = insertvalues & "," & loverduedate & ""
                insertfields = insertfields & ",cus_overdue"
                insertvalues = insertvalues & ",'" & cus_overdue.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_committedbydate"
                insertvalues = insertvalues & "," & lcommitteddate & ""
                insertfields = insertfields & ",cus_committed"
                insertvalues = insertvalues & ",'" & cus_committed.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cus_cnbydate"
                insertvalues = insertvalues & "," & lcndate & ""
                insertfields = insertfields & ",cus_cnamt"
                insertvalues = insertvalues & ",'" & cus_cnamt.Text.Replace("'", "''") & "'"

                insertfields = insertfields & ",cus_createby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",cus_createdt"
                insertvalues = insertvalues & ",getdate()"
                insertfields = insertfields & ",cus_updateby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",cus_updatedt"
                insertvalues = insertvalues & ",getdate()"
                insertfields = insertfields & ",cus_accountholder"
                insertvalues = insertvalues & ",'" & cus_accountholder.SelectedValue & "'"

            Else
                If pWorkflowAction = True Then
                    lsql = wfb_bar.getapprovesql(pType)
                End If

                insertvalues = insertvalues & "cus_updateby='" & WebLib.LoginUser.replace("'", "''") & "'"
                insertvalues = insertvalues & ",cus_updatedt=getdate()"

                If cus_company.Enabled = True Then
                    insertvalues = insertvalues & ",cus_company='" & cus_company.Text.Replace("'", "''") & "'"
                End If

                '   If cus_remarks1.Enabled = True Then
                '       insertvalues = insertvalues & ",cus_remarks1='" & cus_remarks1.Text.Replace("'", "''") & "'"
                '    End If
                'If cus_remarks2.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks2='" & cus_remarks2.Text.Replace("'", "''") & "'"
                'End If
                'If cus_remarks3.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks3='" & cus_remarks3.Text.Replace("'", "''") & "'"
                'End If
                'If cus_remarks4.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks4='" & cus_remarks4.Text.Replace("'", "''") & "'"
                'End If
                'If cus_remarks5.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks5='" & cus_remarks5.Text.Replace("'", "''") & "'"
                'End If
                'If cus_remarks6.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks6='" & cus_remarks6.Text.Replace("'", "''") & "'"
                'End If
                'If cus_remarks7.Enabled = True Then
                '    insertvalues = insertvalues & ",cus_remarks7='" & cus_remarks7.Text.Replace("'", "''") & "'"
                'End If
                '                If cus_remarks8.Enabled = True Then
                'insertvalues = insertvalues & ",cus_remarks8='" & cus_remarks7.Text.Replace("'", "''") & "'"
                '            End If

                If cus_overdueasat.Enabled = True Then
                    insertvalues = insertvalues & ",cus_overdueasat=" & loverduedate & ""
                End If
                If cus_overdue.Enabled = True Then
                    insertvalues = insertvalues & ",cus_overdue='" & cus_overdue.Text.Replace("'", "''") & "'"
                End If
                If cus_committedbydate.Enabled = True Then
                    insertvalues = insertvalues & ",cus_committedbydate=" & lcommitteddate & ""
                End If
                If cus_committed.Enabled = True Then
                    insertvalues = insertvalues & ",cus_committed='" & cus_committed.Text.Replace("'", "''") & "'"
                End If
                If cus_cnbydate.Enabled = True Then
                    insertvalues = insertvalues & ",cus_cnbydate=" & lcndate & ""
                End If
                If cus_cnamt.Enabled = True Then
                    insertvalues = insertvalues & ",cus_cnamt='" & cus_cnamt.Text.Replace("'", "''") & "'"
                End If
                If cus_accountholder.Enabled = True Then
                    insertvalues = insertvalues & ",cus_accountholder='" & cus_accountholder.SelectedValue & "'"
                End If
            End If

            Dim lsqlcom As String = ""
            lsqlcom = lsqlcom & "'" & WebLib.LoginUser.replace("'", "''") & "'"
            lsqlcom = lsqlcom & ",'" & IIf(cus_remarks.Text = "", "[Please refer to above section.]", cus_remarks.Text.Replace("'", "''")) & "'"
            lsqlcom = lsqlcom & ",getdate()"

            wfb_bar.postComments(lsqlcom, TableName, pWorkflowAction)

            If savedata(insertfields, insertvalues, True, lsql) = True Then
                If pType = "" Then
                    pType = "route"
                End If
                If pWorkflowAction = True Then
                    If wfb_bar.notifyusers(pType) = False Then

                    End If
                End If
                Response.Redirect("~/" & Redirector.Redirect(NmSpace, ucode.Value, False))
            Else
                Response.Write(WebLib.ErrorTrap)
                lblMessage.Text = WebLib.getAlertMessageStyle("There is an error while saving. Please retry")
            End If

        Catch Err As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(Err.Message)
        Finally
        End Try

    End Sub

    Public Sub savepage(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Call savedatadata(False, "")
    End Sub

    Protected Sub wfb_bar_OnApproveEvent(ByVal sender As Object, ByVal e As EventArgs) Handles wfb_bar.OnApproveEvent
        Call savedatadata(True, "Approve")
    End Sub

    Protected Sub wfb_bar_OnRejectEvent(ByVal sender As Object, ByVal e As EventArgs) Handles wfb_bar.OnRejectEvent
        Call savedatadata(True, "Reject")
    End Sub

    Protected Sub wfb_bar_OnCancelEvent(ByVal sender As Object, ByVal e As EventArgs) Handles wfb_bar.OnCancelEvent
        Call savedatadata(True, "Cancel")
    End Sub

    'Private Function visibleControl(ByVal bvisible As Boolean)
    '    trcus_remarks7.Visible = bvisible
    '    cus_remarks7.Visible = bvisible
    'End Function

    Public Sub loadpr()
        Try
            rep_comment.DataSource = wfb_bar.getComments2()
            rep_comment.DataBind()
            rep_audit.DataSource = wfb_bar.GetAuditLogsDs2()
            rep_audit.DataBind()
        Catch ex As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
        End Try
    End Sub

    Public Sub loaddraft()
        Try
            cus_remarks.Text = wfb_bar.getDraft2()
        Catch ex As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
        End Try
    End Sub

End Class

