Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.OleDb
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls
Partial Public Class codemaster_class

    Inherits detailspage

    Private f_size As String
    'Generated by VI FEANDI SOFTLABS FORM GENERATOR (http://www.vifeandi.net) VER 2014.1
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        listingpage = "codemstrlist.aspx"
        _FormsName = "Codemaster Details"
        TableName = "codemaster"
        IDPField = ""
        IDField = "cm_id"
        AppIDField = ""
        MerchantIDField = ""
        FilterField = "cm_filter"
        APPCode = ""
        AddRights = "" '"SM0001"
        DelRights = "" '"SM0003"
        ModRights = "" '"SM0002"
        ViewRights = "" '"SM0004"
        FullRights = ""
        NmSpace = "mstrcategory"

        Dim obj As New ViFeandi.General
        f_size = obj.GetPageSizeString(True, "")
        obj = Nothing

        If Page.IsPostBack = False Then
            'Call WebLib.SetListItems(wf_classification, WebLib.ClassificationString)
            codegroup.Value = Request("la") & ""

        End If

        Call InitLoad()

    End Sub
    Private Function ValidateForm()
        lblMessage.Text = ""
        If cm_code.Text.Trim = "" Then
            lblMessage.Text = WebLib.getAlertMessageStyle("Code is Mandatory")
            Return False
            Exit Function
        End If

        If cm_description.Text.Trim = "" Then
            lblMessage.Text = WebLib.getAlertMessageStyle("Description is Mandatory")
            Return False
            Exit Function
        End If

        If WebLib.CodeExists(cm_code.Text, "cm_code", TableName, IDField, rid.Value, IDPField, bid.Value, AppIDField, MerchantIDField, FilterField) = True Then
            lblMessage.Text = "This Code Already Exist"
            Return False
            Exit Function
        End If



        Return True
    End Function
    Public Overrides Function LoadData() As Boolean
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow
        Dim templi As ListItem
        If IsNumeric(rid.Value) = False Then
            Exit Function
        End If

        Try
            cmd.CommandText = "Select * from codemaster where cm_id=" & rid.Value
            LogtheAudit(cmd.CommandText)
            cmd.Connection = cn
            ad.SelectCommand = cmd
            ad.Fill(ds, "datarecords")
            For Each dr In ds.Tables("datarecords").Rows

                counter = counter + 1

                cm_code.Text = dr("cm_code") & ""
                cm_description.Text = dr("cm_description") & ""

                'templi = wf_classification.Items.FindByValue(dr("wf_classification") & "")
                'wf_classification.SelectedIndex = wf_classification.Items.IndexOf(templi)

                Exit For
            Next
            cn.Close()
            cmd.Dispose()
            cn.Dispose()

            Return True

        Catch ex As Exception
            LogtheAudit(ex.Message)
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
            Return False
        End Try
    End Function

    Public Sub savepage(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Dim insertfields, insertvalues As String
        Dim lsrdesc As String = ""
        insertfields = ""
        insertvalues = ""
        If ValidateForm() = False Then
            Exit Sub
        End If

        Dim lwf_class As String = ""
        'If wf_classification.SelectedIndex < 0 Then
        '    lwf_class = ""
        'Else
        '    lwf_class = wf_classification.SelectedItem.Value
        'End If

        Try
            If rid.Value = "" Then
                uid.Value = WebLib.getUniqueKey

                insertfields = insertfields & "cm_merchantid"
                insertvalues = insertvalues & "'" & WebLib.MerchantID.replace("'", "''") & "'"
                insertfields = insertfields & ",cm_filter"
                insertvalues = insertvalues & ",'" & WebLib.FilterCode.replace("'", "''") & "'"
                insertfields = insertfields & ",cm_uid"
                insertvalues = insertvalues & ",'" & uid.Value & "'"
                insertfields = insertfields & ",cm_code"
                insertvalues = insertvalues & ",'" & cm_code.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cm_description"
                insertvalues = insertvalues & ",'" & cm_description.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cm_fieldname"
                insertvalues = insertvalues & ",'" & codegroup.Value.Replace("'", "''") & "'"
                'insertfields = insertfields & ",wf_classification"
                'insertvalues = insertvalues & ",'" & lwf_class.Replace("'", "''") & "'"
                insertfields = insertfields & ",cm_createby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",cm_createdt"
                insertvalues = insertvalues & ",getdate()"
                insertfields = insertfields & ",cm_updateby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",cm_updatedt"
                insertvalues = insertvalues & ",getdate()"

            Else
                insertvalues = insertvalues & "cm_description='" & cm_description.Text.Replace("'", "''") & "'"
                insertvalues = insertvalues & ",cm_code='" & cm_code.Text.Replace("'", "''") & "'"
                'insertvalues = insertvalues & ",wf_classification='" & lwf_class.Replace("'", "''") & "'"
                insertvalues = insertvalues & ",cm_updateby='" & WebLib.LoginUser.replace("'", "''") & "'"
                insertvalues = insertvalues & ",cm_updatedt=getdate()"

            End If

            If savedata(insertfields, insertvalues) = True Then
                Call gotoback()
            End If
        Catch Err As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(Err.Message)
        Finally

        End Try
    End Sub

End Class

