Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.OleDb
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls
Partial Public Class customer_class
    Inherits detailspage


    Private f_size As String
    'Generated by VI FEANDI SOFTLABS FORM GENERATOR (http://www.vifeandi.net) VER 2014.1
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        listingpage = "custlist.aspx"
        _FormsName = "Customer Details"
        TableName = "customer"
        IDPField = ""
        IDField = "cu_id"
        AppIDField = ""
        MerchantIDField = ""
        FilterField = "cu_filter"
        APPCode = "SALES"
        AddRights = "SE0001" '"SM0001"
        DelRights = "SE0002" '"SM0003"
        ModRights = "SE0003" '"SM0002"
        ViewRights = "SE0004" '"SM0004"
        FullRights = "SE0005"
        NmSpace = "salescustmaintenance"

        Dim obj As New ViFeandi.General
        f_size = obj.GetPageSizeString(True, "")
        obj = Nothing

        If Page.IsPostBack = False Then
            'Call WebLib.SetListItems(wf_classification, WebLib.ClassificationString)
        End If
        Call InitLoad()
    End Sub
    Private Function ValidateForm()
        lblMessage.Text = ""
        If cu_code.Text.Trim = "" Then
            lblMessage.Text = WebLib.getAlertMessageStyle("Customer Code is Mandatory")
            Return False
            Exit Function
        End If

        If cu_name.Text.Trim = "" Then
            lblMessage.Text = WebLib.getAlertMessageStyle("Customer Name is Mandatory")
            Return False
            Exit Function
        End If

        If WebLib.CodeExists(cu_code.Text, "cu_code", TableName, IDField, rid.Value, IDPField, bid.Value, AppIDField, MerchantIDField, FilterField) = True Then
            lblMessage.Text = "This Customer Code Already Exist"
            Return False
            Exit Function
        End If



        Return True
    End Function
    Public Overrides Function LoadData() As Boolean
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow
        Dim templi As ListItem
        If IsNumeric(rid.Value) = False Then
            Exit Function
        End If

        Try
            cmd.CommandText = "Select * from customer where cu_id=" & rid.Value
            LogtheAudit(cmd.CommandText)
            cmd.Connection = cn
            ad.SelectCommand = cmd
            ad.Fill(ds, "datarecords")
            For Each dr In ds.Tables("datarecords").Rows

                counter = counter + 1

                cu_code.Text = dr("cu_code") & ""
                cu_name.Text = dr("cu_name") & ""
                cu_attention.Text = dr("cu_attention") & ""
                cu_email.Text = dr("cu_email") & ""
                cu_telno.Text = dr("cu_telno") & ""
                cu_faxno.Text = dr("cu_faxno") & ""

                'templi = wf_classification.Items.FindByValue(dr("wf_classification") & "")
                'wf_classification.SelectedIndex = wf_classification.Items.IndexOf(templi)

                Exit For
            Next
            cn.Close()
            cmd.Dispose()
            cn.Dispose()

            Return True

        Catch ex As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(ex.Message)
            Return False
        End Try
    End Function

    Public Sub savepage(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Dim insertfields, insertvalues As String
        Dim lsrdesc As String = ""
        insertfields = ""
        insertvalues = ""
        If ValidateForm() = False Then
            Exit Sub
        End If

        Dim lwf_class As String = ""
        'If wf_classification.SelectedIndex < 0 Then
        '    lwf_class = ""
        'Else
        '    lwf_class = wf_classification.SelectedItem.Value
        'End If

        Try
            If rid.Value = "" Then
                uid.Value = WebLib.getUniqueKey

                insertfields = insertfields & "cu_merchantid"
                insertvalues = insertvalues & "'" & WebLib.MerchantID.replace("'", "''") & "'"
                insertfields = insertfields & ",cu_filter"
                insertvalues = insertvalues & ",'" & WebLib.FilterCode.replace("'", "''") & "'"
                insertfields = insertfields & ",cu_uid"
                insertvalues = insertvalues & ",'" & uid.Value & "'"
                insertfields = insertfields & ",cu_code"
                insertvalues = insertvalues & ",'" & cu_code.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cu_name"
                insertvalues = insertvalues & ",'" & cu_name.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cu_attention"
                insertvalues = insertvalues & ",'" & cu_attention.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cu_email"
                insertvalues = insertvalues & ",'" & cu_email.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cu_telno"
                insertvalues = insertvalues & ",'" & cu_telno.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",cu_faxno"
                insertvalues = insertvalues & ",'" & cu_faxno.Text.Replace("'", "''") & "'"
                'insertfields = insertfields & ",wf_classification"
                'insertvalues = insertvalues & ",'" & lwf_class.Replace("'", "''") & "'"
                insertfields = insertfields & ",cu_createby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",cu_createdt"
                insertvalues = insertvalues & ",getdate()"
                insertfields = insertfields & ",cu_updateby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",cu_updatedt"
                insertvalues = insertvalues & ",getdate()"

            Else
                insertvalues = insertvalues & "cu_name='" & cu_name.Text.Replace("'", "''") & "'"
                insertvalues = insertvalues & ",cu_code='" & cu_code.Text.Replace("'", "''") & "'"
                insertvalues = insertvalues & "cu_attention='" & cu_attention.Text.Replace("'", "''") & "'"
                insertvalues = insertvalues & ",cu_email='" & cu_email.Text.Replace("'", "''") & "'"
                insertvalues = insertvalues & "cu_telno='" & cu_telno.Text.Replace("'", "''") & "'"
                insertvalues = insertvalues & ",cu_faxno='" & cu_faxno.Text.Replace("'", "''") & "'"
                'insertvalues = insertvalues & ",wf_classification='" & lwf_class.Replace("'", "''") & "'"
                insertvalues = insertvalues & ",cu_updateby='" & WebLib.LoginUser.replace("'", "''") & "'"
                insertvalues = insertvalues & ",cu_updatedt=getdate()"

            End If

            If savedata(insertfields, insertvalues) = True Then
                Call gotoback()
            End If
        Catch Err As Exception
            lblMessage.Text = WebLib.getAlertMessageStyle(Err.Message)
        Finally

        End Try
    End Sub
End Class

