<%@ Page Language="VB" AutoEventWireup="false" EnableViewState="True" CodeFile="downloaddocs.aspx.vb" Inherits="downloaddocs_list_class" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
<!--Generated by ViSoftLabs Forms Generator (http://www.vifeandi.net)-->
<meta charset="utf-8">
<title>eDocument </title>
<!--#include File="topinitdetail.aspx"-->
<!--#include File="topscriptdetail.aspx"-->
</head>
<body>
<center>
<form id="frmform" runat="server">
<table width="100%">
<tr><td class="cssdetail">Download Files</td></tr>
<tr><td align="left" width="100%" class="cssdetail">
<asp:PlaceHolder ID="phListFiles" runat="server" ></asp:PlaceHolder>
</td></tr>
</table>

<input type="hidden" runat="server" id="company" name="company">
<input type="hidden" runat="server" id="docno" name="docno">

</form>
</center>
</body>
</html>

