<%@ Page Language="VB" AutoEventWireup="false" EnableViewState="True" CodeFile="edocStatelist.aspx.vb" Inherits="edocstate_list_class" %>

<%@ Register Src="UserControls/DatePicker.ascx" TagPrefix="uc" TagName="DatePicker" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <!--Generated by ViSoftLabs Forms Generator (http:// www.vifeandi.net)-->
    <meta charset="utf-8">
    <title><%=_FormsName%></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!--#include File="topinitdetail.aspx"-->
    <!--#include File="topmobilecss.aspx"-->
    <!--#include File="topscriptdetail.aspx"-->
    <script>
        $(function () {
            $("input[type=submit], button")
            .button()
            var div1 = $("#divnavi").accordion({ collapsible: false, heightStyle: "content", active: 0 });
            var div2 = $("#divsearch").accordion({ collapsible: false, heightStyle: "content", active: 0 });
            div2.show();
        });
    </script>
</head>
<body>
    <form id="frmform" runat="server">
        <!--#include File="include/FormHeader1.aspx"-->

        <div class=" container-fluid bg-light" style="font-size: 1rem; min-height: 100vh;">
            <div class="row listpage">
                <div class="col-md-2 bg-light ">
                    <div style="padding-top: 1em; font-size: 0.8rem; text-align: left; display: none;">
                        <div>
                            <asp:Button ID="btnadd" CssClass="btn btn-sm btn-info w-100" Text="Save Details" runat="server" OnClick="AddEvent" />
                            <br />
                            <hr />
                            <asp:Button ID="btnback" CssClass="btn btn-sm btn-info w-100" Text="Back to Listing" runat="server" OnClick="backpage" CausesValidation="false" OnClientClick="jQuery('#frmform').validationEngine('detach');" />
                            <br />
                            <b>Messages:</b><br />
                            <asp:Label ID="lblMessage2" runat="server" class="cssrequired"></asp:Label>
                            <br />
                            <br />
                        </div>
                    </div>
                    <br />
                    <div style="text-align: left; font-size: 0.8rem;">
                        <div class="card">
                            <div class="card-header">
                                <h6>
                                    <a data-toggle="collapse" href="#search" aria-expanded="false" aria-controls="search">
                                        <i class="fa fa-search-plus"></i> Search Menu
                                    </a>
                                </h6>
                            </div>
                            <div id="search" class="collapse">
                                <div class="card-body">
                                    <b>Filter by Branch (Wild Card Search):</b><br />
                                    <asp:TextBox placeholder="Search" ID="search_key1" runat="server" Columns="23" MaxLength="50"></asp:TextBox><br />
                                    <asp:PlaceHolder ID="phSearchFields" runat="server"></asp:PlaceHolder>
                                    <hr class="cssdivider" width="100%" runat="server" id="hr1" />
                                    <br />
                                    <b>Filter by Month/Year:</b><br />

                                    <asp:DropDownList ID="ddMonth" runat="server">
                                        <asp:ListItem Value="">Month</asp:ListItem>
                                        <asp:ListItem Value="01">Jan</asp:ListItem>
                                        <asp:ListItem Value="02">Feb</asp:ListItem>
                                        <asp:ListItem Value="03">Mar</asp:ListItem>
                                        <asp:ListItem Value="04">Apr</asp:ListItem>
                                        <asp:ListItem Value="05">May</asp:ListItem>
                                        <asp:ListItem Value="06">Jun</asp:ListItem>
                                        <asp:ListItem Value="07">Jul</asp:ListItem>
                                        <asp:ListItem Value="08">Aug</asp:ListItem>
                                        <asp:ListItem Value="09">Sept</asp:ListItem>
                                        <asp:ListItem Value="10">Oct</asp:ListItem>
                                        <asp:ListItem Value="11">Nov</asp:ListItem>
                                        <asp:ListItem Value="12">Dec</asp:ListItem>
                                    </asp:DropDownList>
                                    <asp:DropDownList ID="ddYear" runat="server">
                                    </asp:DropDownList>

                                    <hr class="cssdivider" width="100%" runat="server" id="hrdate" />
                                    <br />
                                    <uc:datepicker ID="uc_from" runat="server" AllowNull="false" Width="100%" PlaceHolder="From Date" />
                                    <uc:datepicker ID="uc_to" runat="server" AllowNull="false" Width="100%" PlaceHolder="To Date" />
                                    <asp:PlaceHolder ID="phSearchDate" runat="server"></asp:PlaceHolder>
                                    <br />
                                    <br />
                                    <asp:Button ID="btnsearch" CssClass="btn btn-sm btn-info w-100" Text="Search" runat="server" OnClick="SearchStrM" Style="width: 150px" />
                                    <br />
                                    <b>Messages:</b><br />
                                    <asp:Label ID="lblMessage" runat="server" class="cssrequired"></asp:Label>
                                    <br />
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-md-10 bg-white">
                    <div style="padding-top: 1em;">
                        <div class="ui-widget-header alert p-1 form-fonts w-100  bg-header " role="alert" style="text-align: left; padding-left: 1em!important; margin-bottom: 1em!important">
                            <%=_FormsName%>
                        </div>
                        <table id="table_listing" class="table table-borderless dt-responsive nowrap" width="100%" style="height: 100%; font-size: 0.8rem;" cellpadding="2" cellspacing="1">
                            <thead>
                                <tr class="ui-widget-header" style="height: 25px">
                                    <th class="cssdetail" width="5%"><b>No.</b></th>
                                    <th class="cssdetail" data-priority="1"></th>
                                    <th class="cssdetail" width="10%">File type</th>
                                    <th class="cssdetail" width="10%" align="center" data-priority="2">Month</th>
                                    <th class="cssdetail" width="10%" align="center" data-priority="3">Year</th>
                                    <th class="cssdetail" width="10%">Branch</th>

                                    <th class="cssdetail"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <asp:Repeater ID="rep" runat="server" OnItemCommand="rep_ItemCommand">
                                    <ItemTemplate>
                                        <tr id="trRow" class="ui-widget-content" runat="server">
                                            <td align="center" class="cssdetail">
                                                <asp:Literal ID="litNo" runat="server" Text='<%# Container.ItemIndex + 1 %>'></asp:Literal>
                                                <asp:Literal ID="litfilename" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "Text")%>'></asp:Literal>
                                            </td>
                                            <td align="center" class="cssdetail" width="50px">
                                                <asp:Literal ID="litimage" runat="server"></asp:Literal>
                                            </td>
                                            <td class="cssdetail">
                                                <asp:Literal ID="littype" runat="server"></asp:Literal>
                                            </td>
                                            <td class="cssdetail" align="center">
                                                <asp:Literal ID="litmonth" runat="server"></asp:Literal></td>
                                            <td class="cssdetail" align="center">
                                                <asp:Literal ID="lityear" runat="server"></asp:Literal></td>
                                            <td class="cssdetail">
                                                <asp:Literal ID="litbranch" runat="server"></asp:Literal></td>
                                            <td class="cssdetail">
                                                <asp:LinkButton ID="lnkEdit" runat="server" CommandArgument='<%#DataBinder.Eval(Container.DataItem, "Text")%>' CommandName="Download">Download</asp:LinkButton>
                                            </td>
                                        </tr>
                                    </ItemTemplate>
                                </asp:Repeater>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <input type="hidden" runat="server" id="rid" name="rid" />
        <input type="hidden" runat="server" id="bid" name="bid" />
        <hr width="100%" />
        <!--#include File="include/FormFooter1.aspx"-->
    </form>
    <!--#include File="include/footerscript.aspx"-->

    <script type="text/javascript">
        $(document).ready(function () {
            $('#table_listing').DataTable({
                responsive: true,
                "info": true,
                "bFilter": false
            });
        });
    </script>
</body>
</html>

