Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.OleDb
Imports System.Data.Odbc

Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls
Imports System.Windows.Forms
Partial Public Class home_class
    Inherits stdpage

    'Generated by VI SOFTLABS FORM GENERATOR (http://www.vifeandi.net) VER 2014.1
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        listingpage = ""
        _FormsName = ""
        TableName = ""
        IDPField = ""
        IDField = ""
        AppIDField = ""
        MerchantIDField = ""
        FilterField = ""

    End Sub

End Class

