<%@ Page Language="VB" AutoEventWireup="false" EnableViewState="True" CodeFile="loginbranch.aspx.vb" Inherits="loginbranch_class" %>
<%@ Register Src="UserControls/DatePicker.ascx" TagPrefix="uc" TagName="DatePicker" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
<!--Generated by ViSoftLabs Forms Generator (http://www.vifeandi.net)-->
<meta charset="utf-8">
<title></title>
<script src="jquery/js/jquery.js"></script>
<script src="jquery/js/jquery-ui.js"></script>
<link rel="stylesheet" href="jquery/css/default/jquery.default.css">
<link rel="stylesheet" href="Styles/cssdefault.css">
<script>
   $(function() {
   $( "input[type=submit], button" )
   .button()
   });
</script>
</head>
<body>
<center>
<form id="frmform" runat="server">
<table width="500px">
<tr><td align="left" width="100%">
<table class="ui-widget-header ui-corner-all"><tr><td width="10px"><span class="ui-icon ui-icon-triangle-1-e"></span></td><td width="100%"><span class="ui-widget"><b>Please select branch to access</b></span></td></tr></table>
</td></tr>
<tr><td valign="top" width="100%">

<table  width="100%"  style="height:80%; background-color:Gainsboro;" cellpadding="2" cellspacing="1">
<asp:Repeater ID="rep" runat="server"  >
<ItemTemplate>
<tr id="trRow" class="ui-widget-content" runat="server">
<td align="center" class="cssdetail">
<asp:Literal ID="litNo" runat="server" Text='<%# Container.ItemIndex + 1 %>'></asp:Literal>
<asp:HiddenField ID="br_code" runat="server" Value='<%#DataBinder.Eval(Container.DataItem, "br_code")%>' />
<asp:HiddenField ID="br_id" runat="server" Value='<%#DataBinder.Eval(Container.DataItem, "br_id")%>' />
</td>
<td class="cssdetail"><asp:Literal ID="litbr_name" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "br_name")%>'></asp:Literal></td>
<td class="cssdetail" width="110px"><asp:Button runat="server" style="width:100px;height:40px" Text="SELECT" CommandArgument='<%#DataBinder.Eval(Container.DataItem, "br_id")%>' CommandName="Select" /></td>
</tr>
</ItemTemplate>
</asp:Repeater>
</table>
<br />
<asp:Button ID="BackButton" Text="BACK TO LOGIN PAGE" Runat="server" OnClick="backpage" style="width:100%;height:40px" CausesValidation="false" OnClientClick="jQuery('#frmform').validationEngine('detach');"  /> <br />
<asp:Label ID="lblMessage" runat="server" class="cssrequired"></asp:Label>

</td></tr>
</table>
</form>
</center>
</body>
</html>

