<%@ Page Language="VB" AutoEventWireup="false" EnableViewState="True" CodeFile="secfunctionlist.aspx.vb" Inherits="secfun_list_class" %>
<%@ Register Src="UserControls/DatePicker.ascx" TagPrefix="uc" TagName="DatePicker" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
<!--Generated by ViSoftLabs Forms Generator (http://www.vifeandi.net)-->
<meta charset="utf-8">
<title>Security Center - Function Code</title>
<!--#include File="topinit.aspx"-->
<script>
   $(function() {
   $( "input[type=submit], button" )
   .button()
   var div1 = $( "#divnavi" ).accordion({collapsible: false,heightStyle: "content",active: 0});
   var div2 = $( "#divsearch" ).accordion({collapsible: false,heightStyle: "content",active: 0});
   var div3 = $( "#divdata" );
   div1.show();
   div2.show();
   div3.show();
   });
</script>
<!--#include File="topscript.aspx"-->
</head>
<body>
<form id="frmform" runat="server">
<!--#include File="include/FormHeader1.aspx"-->
<table width="100%">
<tr><td align="left" width="100%">
<table class="ui-widget-header ui-corner-all"><tr><td width="10px"><span class="ui-icon ui-icon-triangle-1-e"></span></td><td width="100%"><span class="ui-widget"><b><%=_formsname%></b></span></td></tr></table>
</td></tr>
<tr><td valign="top" width="100%">
<table width="100%" cellpadding="0" cellspacing="2"><tr><td width="220px" valign="top">
<div id="divnavi" style="display:none">
<h3>Options Menu</h3>
<div style="text-align:left">
<asp:Button ID="btnadd" Text="Add New Record" Runat="server"  OnClick="AddEvent" style="width:160px"   /><br /><br />
<asp:Button ID="btnback" Text="Back to Listing" Runat="server" OnClick="backpage" style="width:160px" CausesValidation="false" /> 
<br /><br />
<b>Messages:</b><br />
<asp:Label ID="lblMessage" runat="server" class="cssrequired"></asp:Label>
<br /><br /><br />
</div>
</div>
<div id="divsearch" style="display:none">
<h3>Search Menu</h3>
<div style="text-align:left">
<b>Please enter search key:</b><br />
<asp:TextBox ID="search_key1" runat="server" Columns="23" Maxlength="50"></asp:TextBox><br />
Search Field:<br />
<asp:PlaceHolder ID="phSearchFields" runat="server" ></asp:PlaceHolder>
<br />
<hr class="cssdivider" width="100%" runat="server" id="hrdate" /><br />
<uc:datepicker ID="uc_from" runat="server" AllowNull="false" Width="72px" PlaceHolder="From Date" />
<uc:datepicker ID="uc_to" runat="server" AllowNull="false" Width="72px" PlaceHolder="To Date" />
<asp:PlaceHolder ID="phSearchDate" runat="server" ></asp:PlaceHolder>
<br /><br />
<asp:Button ID="btnsearch" Text="Search" Runat="server"  OnClick="SearchStr" style="width:150px" /> 
</div>
</div>
</td>
<td  valign="top" width="100%" > 

<div id="divdata" style="display:none">
<table  width="100%"  style="height:80%; background-color:Gainsboro;" cellpadding="2" cellspacing="1">
<tr class="ui-widget-header" style="height:25px">
<td  class="cssdetail"><b>No.</b></td>
<td class="cssdetail" >Application ID</td>
<td class="cssdetail"  width="100px">Function code</td>
<td class="cssdetail"  width="200px">Function name</td>
<td class="cssdetail"  width="100px">Add</td>
<td class="cssdetail"  width="100px">Edit</td>
<td class="cssdetail"  width="100px">Delete</td>
<td class="cssdetail"  width="100px">View</td>
<td class="cssdetail"  width="100px">Full</td>
<td class="cssdetail" >Create by</td>
<td class="cssdetail" >Last update by</td>

<td class="cssdetail"></td>
</tr>
<asp:Repeater ID="rep" runat="server"  OnItemCommand="rep_ItemCommand" >
<ItemTemplate>
<tr id="trRow" class="ui-widget-content" runat="server">
<td align="center" class="cssdetail">
<asp:Literal ID="litNo" runat="server" Text='<%# Container.ItemIndex + 1 %>'></asp:Literal>
</td>
<td class="cssdetail"><asp:Literal ID="litssf_appid" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "ssf_appid")%>'></asp:Literal></td>
<td class="cssdetail"><asp:Literal ID="litssf_code" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "ssf_code")%>'></asp:Literal></td>
<td class="cssdetail"><asp:Literal ID="litssf_name" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "ssf_name")%>'></asp:Literal></td>
<td class="cssdetail"><asp:Literal ID="litssf_add" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "ssf_add")%>'></asp:Literal></td>
<td class="cssdetail"><asp:Literal ID="litssf_edit" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "ssf_edit")%>'></asp:Literal></td>
<td class="cssdetail"><asp:Literal ID="litssf_del" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "ssf_del")%>'></asp:Literal></td>
<td class="cssdetail"><asp:Literal ID="litssf_view" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "ssf_view")%>'></asp:Literal></td>
<td class="cssdetail"><asp:Literal ID="litssf_gotrights" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "ssf_gotrights")%>'></asp:Literal></td>
<td class="cssdetail"><asp:Literal ID="litssf_createby" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "ssf_createby")%>'></asp:Literal></td>
<td class="cssdetail"><asp:Literal ID="litssf_updateby" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "ssf_updateby")%>'></asp:Literal></td>

<td align="center" class="cssdetail">
<asp:LinkButton ID="lnkEdit" runat="server" CommandArgument='<%#DataBinder.Eval(Container.DataItem, "ssf_id")%>' CommandName="Edit">Edit</asp:LinkButton>
<asp:Literal ID="litSepDel" runat="server">|</asp:Literal>
<asp:LinkButton ID="lnkDelete" runat="server" CommandArgument='<%#DataBinder.Eval(Container.DataItem, "ssf_id")%>' CommandName="Del"  OnClientClick="return confirm('Are you sure want to delete this record?')">Del.</asp:LinkButton>
</td>
</tr>
</ItemTemplate>
</asp:Repeater>
<tr class="ui-widget-content">
<td colspan="<%=columnscount%>" align="center" class="cssdetail">
<asp:Literal ID="litspacing" runat="server"></asp:Literal>
</td>
</tr>
<tr class="ui-widget-header"><td colspan="<%=columnscount%>" align="center" class="cssdetail" style="height:20px"><asp:label id="lblCurrentPage" runat="server"></asp:label>
</td></tr>
</table>
</div>
<!--#include File="PageControl.aspx"-->
</td></tr></table>
</td>
</tr>
</table>
<input type="hidden" runat="server" id="rid" name="rid">
<input type="hidden" runat="server" id="bid" name="bid">
<hr width="100%" />
<!--#include File="include/FormFooter1.aspx"-->
</form>
</body>
</html>

