Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.OleDb
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls
Imports System.Collections.Generic

Partial Public Class secuse_class
    Inherits detailspage
    'Generated by VI SOFTLABS FORM GENERATOR (http://www.vifeandi.net) VER 2014.1

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        listingpage = "secuserinfolist.aspx"
        _FormsName = "Security Center - User Info "
        TableName = "secuserinfo"
        IDPField = ""
        IDField = "usr_id"
        AppIDField = ""
        MerchantIDField = "usr_merchantid"
        FilterField = "usr_filter"
        APPCode = "GENERAL"
        AddRights = "SU0001"
        DelRights = "SU0003"
        ModRights = "SU0002"
        ViewRights = "SU0004"
        FullRights = ""
        NmSpace = "secuse"
        lblMessage.Text = ""

        If Page.IsPostBack = False Then
            Call WebLib.setListItemsTable(usr_profile, "pf_name", "pf_id", "secuserprofile", "pf_name", "pf_appid", "", "")
            Call WebLib.setListItemsTable(usr_department, "de_name", "de_id", "Department", "de_name", "", "", "")
            ' CR 20
            'Call WebLib.setListItemsTable(usr_branch, "br_name", "br_id", "Branch", "br_name", "", "", "", " br_id in (6,7) ")
            Call WebLib.setListItemsTable(usr_branch, "br_name", "br_code", "Branch", "br_name", "", "", "", " br_merchantid in ('company') ")

            Call WebLib.setListItemsTable(usr_firstscreen, "app_name", "app_code", "sysApplication", "app_name", "", "", "", " isnull(app_startup,0) = 1")
            Call WebLib.setListItemsTable(usr_smp, "sp_name", "sp_id", "salesperson", "sp_name", "", "sp_merchantid", "sp_filter")
            Call WebLib.setListItemsTable(usr_matrixlevel, "ml_name", "ml_code", "mstrmatrixlevel", "ml_name", "", "", "", " ml_active ='Yes' group by ml_code, ml_name")
            usr_pin.Visible = False
        End If

        Call InitLoad()
        usr_isad_CheckedChanged(Me, EventArgs.Empty)

        If Page.IsPostBack = False Then
            Call loaddatagrid("")
        End If
    End Sub

    Private Function ValidateForm()
        lblMessage.Text = ""
        If usr_code.Text.Trim = "" Then
            lblMessage.Text = "User Code is Mandatory"
            Return False
            Exit Function
        End If
        If usr_name.Text.Trim = "" Then
            lblMessage.Text = "User Name is Mandatory"
            Return False
            Exit Function
        End If
        If usr_profile.SelectedIndex < 0 Then
            lblMessage.Text = "User profile is Mandatory"
            Return False
            Exit Function
        End If
        If (usr_expiry.value & "").trim = "" Then
            lblMessage.Text = "Expiry date is Mandatory"
            Return False
            Exit Function
        End If
        If usr_matrixlevel.ToString.Contains("L3") Then
            If usr_region.SelectedIndex < 0 Then
                lblMessage.Text = "Region is Mandatory"
                Return False
                Exit Function
            End If
        End If
        For Each item As ListItem In usr_matrixlevel.Items
            If item.Selected And item.Value = "L4" Then
                Dim SelState As Boolean = False
                For Each stateitem As ListItem In usr_state.Items
                    If stateitem.Selected Then
                        SelState = True
                        Exit For
                    End If
                Next
                If SelState = False Then
                    lblMessage.Text = "State is Mandatory"
                    Return False
                    Exit Function
                End If
            End If
        Next

        If WebLib.CodeExists(usr_code.Text, "usr_code", TableName, IDField, rid.Value, IDPField, bid.Value, "", "", "") = True Then
            lblMessage.Text = "This User Code Already Exist"
            Return False
            Exit Function
        End If
        If WebLib.CodeExists(usr_loginid.Text, "usr_loginid", TableName, IDField, rid.Value, IDPField, bid.Value, "", "", "") = True Then
            lblMessage.Text = "This User Login Already Exist"
            Return False
            Exit Function
        End If

        Return True
    End Function

    Public Overrides Function LoadData() As Boolean
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow
        Dim templi As ListItem

        If IsNumeric(rid.Value) = False Then
            Exit Function
        End If

        Try
            cmd.CommandText = "Select * from secuserinfo where usr_id=" & rid.Value
            cmd.Connection = cn
            ad.SelectCommand = cmd
            ad.Fill(ds, "datarecords")

            For Each dr In ds.Tables("datarecords").Rows
                counter = counter + 1
                usr_code.Text = dr("usr_code") & ""
                usr_name.Text = dr("usr_name") & ""
                templi = usr_profile.Items.FindByValue(dr("usr_profile") & "")
                usr_profile.SelectedIndex = usr_profile.Items.IndexOf(templi)
                templi = usr_department.Items.FindByValue(dr("usr_department") & "")
                usr_department.SelectedIndex = usr_department.Items.IndexOf(templi)

                Dim usr_branchstr As String = dr("usr_branch") & ""
                For Each item As ListItem In usr_branch.Items
                    If usr_branchstr.Contains(item.Value) Then
                        item.Selected = True
                    End If
                Next

                usr_loginid.Text = dr("usr_loginid") & ""
                usr_adlogin.Text = dr("usr_adlogin") & ""
                usr_password.Attributes.Add("value", dr("usr_password"))


                usr_pin.Text = dr("usr_pin") & ""
                usr_expiry.value = WebLib.formatthedate(dr("usr_expiry"))
                usr_disable.Checked = WebLib.BitToBoolean(dr("usr_disable") & "")
                litcreateby.Text = dr("usr_createby") & ""
                litcreateon.Text = dr("usr_createdt") & ""
                litupdateby.Text = dr("usr_updateby") & ""
                litupdateon.Text = dr("usr_updatedt") & ""

                usr_whereabout.Checked = WebLib.BitToBoolean(dr("usr_whereabout") & "")

                templi = usr_smp.Items.FindByValue(dr("usr_smp") & "")
                usr_smp.SelectedIndex = usr_smp.Items.IndexOf(templi)

                templi = usr_firstscreen.Items.FindByValue(dr("usr_firstscreen") & "")
                usr_firstscreen.SelectedIndex = usr_firstscreen.Items.IndexOf(templi)

                usr_email.Text = dr("usr_email") & ""

                usr_isad.Checked = WebLib.BitToBoolean(dr("usr_isad") & "")

                Dim usr_matrixlevelstr As String = dr("usr_matrixlevel") & ""

                For Each item As ListItem In usr_matrixlevel.Items
                    If usr_matrixlevelstr.Contains(item.Value) Then
                        item.Selected = True
                    End If
                Next

                If dr("usr_matrixlevel").ToString.Contains("L3") Then
                    trusr_region.Visible = True
                    Call WebLib.setListItemsTable(usr_region, "te_name", "te_code", "mstrterritory", "te_name", "", "", "", "")

                    Dim usr_regionstr As String = dr("usr_region") & ""

                    For Each item As ListItem In usr_region.Items
                        If usr_regionstr.Contains(item.Value) Then
                            item.Selected = True
                        End If
                    Next
                End If

                If dr("usr_matrixlevel").ToString.Contains("L4") Then
                    trusr_state.Visible = True
                    Call WebLib.setListItemsTable(usr_state, "state_name", "state_code", "mstrstate", "state_name", "", "", "", "")

                    Dim usr_statestr As String = dr("usr_state") & ""

                    For Each item As ListItem In usr_state.Items
                        If usr_statestr.Contains(item.Value) Then
                            item.Selected = True
                        End If
                    Next
                End If

                Exit For
            Next

            cn.Close()
            cmd.Dispose()
            cn.Dispose()
        Catch ex As Exception
            lblMessage.Text = ex.Message
        End Try
    End Function

    Public Sub savepage(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Dim insertfields, insertvalues As String
        insertfields = ""
        insertvalues = ""

        If ValidateForm() = False Then
            Exit Sub
        End If
        Dim lusr_profile As String = ""
        If usr_profile.SelectedIndex < 0 Then
            lusr_profile = ""
        Else
            lusr_profile = usr_profile.SelectedItem.Value
        End If
        Dim lusr_department As String = ""
        If usr_department.SelectedIndex < 0 Then
            lusr_department = ""
        Else
            lusr_department = usr_department.SelectedItem.Value
        End If

        Dim lusr_firstscreen As String = ""
        If usr_firstscreen.SelectedIndex < 0 Then
            lusr_firstscreen = ""
        Else
            lusr_firstscreen = usr_firstscreen.SelectedItem.Value
        End If
        Dim lusr_smp As String = ""
        If usr_smp.SelectedIndex < 0 Then
            lusr_smp = "0"
        Else
            lusr_smp = usr_smp.SelectedItem.Value
        End If
        Dim lusrpin As String
        If IsNumeric(usr_pin.Text.Replace("'", "''")) = False Then
            lusrpin = "NULL"
        Else
            lusrpin = usr_pin.Text.Replace("'", "''")
        End If
        Dim lusr_region As String = ""
        Dim usr_regionList As List(Of String) = New List(Of String)()
        For Each item As ListItem In usr_region.Items
            If item.Selected Then
                usr_regionList.Add(item.Value)
            Else
            End If
        Next
        lusr_region = String.Join(",", usr_regionList.ToArray())
        Dim lusr_state As String = ""
        Dim usr_stateList As List(Of String) = New List(Of String)()
        For Each item As ListItem In usr_state.Items
            If item.Selected Then
                usr_stateList.Add(item.Value)
            End If
        Next
        lusr_state = String.Join(",", usr_stateList.ToArray())
        Dim lusr_matrixlevel As String = ""
        Dim usr_matrixlevelList As List(Of String) = New List(Of String)()
        For Each item As ListItem In usr_matrixlevel.Items
            If item.Selected Then
                usr_matrixlevelList.Add(item.Value)
            Else
            End If
        Next
        lusr_matrixlevel = String.Join(",", usr_matrixlevelList.ToArray())

        Try
            If rid.Value = "" Then
                insertfields = insertfields & "usr_merchantid"
                insertvalues = insertvalues & "''"
                insertfields = insertfields & ",usr_filter"
                insertvalues = insertvalues & ",'" & WebLib.FilterCode.replace("'", "''") & "'"
                insertfields = insertfields & ",usr_code"
                insertvalues = insertvalues & ",'" & usr_code.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",usr_name"
                insertvalues = insertvalues & ",'" & usr_name.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",usr_profile"
                insertvalues = insertvalues & "," & lusr_profile & ""
                insertfields = insertfields & ",usr_department"
                insertvalues = insertvalues & "," & lusr_department & ""
                insertfields = insertfields & ",usr_branch"
                'insertvalues = insertvalues & ",'" & lusr_branch & "'"
                insertvalues = insertvalues & ",'" & WebLib.LoginUserCompanySelected.replace("'", "''") & "'"
                insertfields = insertfields & ",usr_loginid"
                insertvalues = insertvalues & ",'" & usr_loginid.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",usr_adlogin"
                insertvalues = insertvalues & ",'" & usr_adlogin.Text.Replace("'", "''") & "'"
                insertfields = insertfields & ",usr_password"
                insertvalues = insertvalues & ",'" & usr_password.Text.Replace("'", "''") & "'"

                insertfields = insertfields & ",usr_email"
                insertvalues = insertvalues & ",'" & usr_email.Text.Replace("'", "''") & "'"

                insertfields = insertfields & ",usr_pin"
                insertvalues = insertvalues & "," & lusrpin & ""
                insertfields = insertfields & ",usr_expiry"
                'insertvalues = insertvalues & ",'" & usr_expiry.Textdmy & "'"
                insertvalues = insertvalues & ",'" & WebLib.formatthedate(usr_expiry.datevalue, True) & "'"
                insertfields = insertfields & ",usr_firstscreen"
                insertvalues = insertvalues & ",'" & lusr_firstscreen & "'"
                insertfields = insertfields & ",usr_smp"
                insertvalues = insertvalues & "," & lusr_smp & ""


                insertfields = insertfields & ",usr_disable"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(usr_disable.Checked)

                insertfields = insertfields & ",usr_whereabout"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(usr_whereabout.Checked)
                insertfields = insertfields & ",usr_isad"
                insertvalues = insertvalues & "," & WebLib.BooleanToBit(usr_isad.Checked)
                insertfields = insertfields & ",usr_matrixlevel"
                insertvalues = insertvalues & ",'" & lusr_matrixlevel.Replace("'", "''") & "'"
                insertfields = insertfields & ",usr_region"
                insertvalues = insertvalues & ",'" & lusr_region.Replace("'", "''") & "'"
                insertfields = insertfields & ",usr_state"
                insertvalues = insertvalues & ",'" & lusr_state.Replace("'", "''") & "'"

                insertfields = insertfields & ",usr_company"
                insertvalues = insertvalues & ",'" & WebLib.LoginUserCompanySelected.replace("'", "''") & "'"
                insertfields = insertfields & ",usr_createby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",usr_createdt"
                insertvalues = insertvalues & ",getdate()"
                insertfields = insertfields & ",usr_updateby"
                insertvalues = insertvalues & ",'" & WebLib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",usr_updatedt"
                insertvalues = insertvalues & ",getdate()"

            Else
                insertvalues = insertvalues & "usr_code='" & usr_code.Text.Replace("'", "''") & "'"
                insertvalues = insertvalues & ",usr_name='" & usr_name.Text.Replace("'", "''") & "'"
                insertvalues = insertvalues & ",usr_email='" & usr_email.Text.Replace("'", "''") & "'"

                insertvalues = insertvalues & ",usr_profile=" & lusr_profile & ""
                insertvalues = insertvalues & ",usr_department=" & lusr_department & ""
                'insertvalues = insertvalues & ",usr_branch='" & lusr_branch & "'"
                insertvalues = insertvalues & ",usr_smp=" & lusr_smp & ""

                insertvalues = insertvalues & ",usr_loginid='" & usr_loginid.Text.Replace("'", "''") & "'"
                insertvalues = insertvalues & ",usr_adlogin='" & usr_adlogin.Text.Replace("'", "''") & "'"
                insertvalues = insertvalues & ",usr_password='" & usr_password.Text.Replace("'", "''") & "'"
                insertvalues = insertvalues & ",usr_firstscreen='" & lusr_firstscreen & "'"

                insertvalues = insertvalues & ",usr_pin=" & lusrpin & ""
                insertvalues = insertvalues & ",usr_expiry='" & WebLib.formatthedate(usr_expiry.datevalue, True) & "'"
                insertvalues = insertvalues & ",usr_disable=" & WebLib.BooleanToBit(usr_disable.Checked)

                insertvalues = insertvalues & ",usr_whereabout=" & WebLib.BooleanToBit(usr_whereabout.Checked)
                insertvalues = insertvalues & ",usr_isad=" & WebLib.BooleanToBit(usr_isad.Checked)
                insertvalues = insertvalues & ",usr_matrixlevel='" & lusr_matrixlevel.Replace("'", "''") & "'"
                insertvalues = insertvalues & ",usr_region='" & lusr_region.Replace("'", "''") & "'"
                insertvalues = insertvalues & ",usr_state='" & lusr_state.Replace("'", "''") & "'"

                insertvalues = insertvalues & ",usr_updateby='" & WebLib.LoginUser.replace("'", "''") & "'"
                insertvalues = insertvalues & ",usr_updatedt=getdate()"

            End If

            If savedata(insertfields, insertvalues, True) = True Then
                If savepageaccess1() = True Then
                    Call gotoback()
                Else
                    Exit Sub
                End If
            End If
        Catch Err As Exception
            lblMessage.Text = Err.Message
        Finally
        End Try
    End Sub

    Public Sub loaddatagrid(Optional ByVal _p_searchkey As String = "")
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow

        If _p_searchkey.Trim <> "" Then
            _p_searchkey = " and " & _p_searchkey
        End If

        'CR 20
        '_p_searchkey = " where br_id in (6,7) " & _p_searchkey
        _p_searchkey = " where br_merchantid in ('company') " & _p_searchkey

        cn.Open()
        'cmd.CommandText = "Select branch.*,UserBranchRights.* from branch left outer join UserBranchRights on br_merchantid = ub_merchantid and br_filter = ub_filter and br_code = ub_brcode and ub_usrcode='" & usr_code.Text.Replace("'", "''") & "' and br_id in (6,7)" & _p_searchkey & " order by br_name"
        cmd.CommandText = "Select branch.* from branch " & _p_searchkey & " order by br_name"

        LogtheAudit(cmd.CommandText)

        cmd.Connection = cn
        ad.SelectCommand = cmd
        ad.Fill(ds, "datarecords")

        Dim dt As DataTable = ds.Tables("datarecords")
        Dim dv As New DataView(dt)

        Dim pgitems As New PagedDataSource()
        pgitems.DataSource = dv

        rep.DataSource = pgitems
        rep.DataBind()
    End Sub

    Public Function savepageaccess() As Boolean
        Dim cn As New OleDbConnection(connectionstring)
        Dim itrans As OleDbTransaction
        Dim cmd As New OleDbCommand()
        Dim counter As Integer = 0
        Dim lSql As String = ""

        Return True

        cn.Open()
        cmd.Connection = cn

        Dim item As RepeaterItem
        For Each item In rep.Items
            lSql = ""

            Dim lBranchCode As String = ""
            Dim mtTextBox1 As HiddenField = item.FindControl("br_code")
            If Not mtTextBox1 Is Nothing Then
                lBranchCode = mtTextBox1.Value
            End If

            If lBranchCode.Trim = "" Then
                GoTo NextItem
            End If


            'lSql = "Delete from [UserBranchRights] where ub_merchantid='" & WebLib.MerchantID & "' and ub_filter='" & WebLib.FilterCode & "' and ub_brcode='" & lBranchCode & "' and ub_usrcode='" & usr_code.Text.Replace("'", "''") & "'"

            Dim myCheckBox5 As CheckBox = item.FindControl("chkfull")
            'If Not myCheckBox5 Is Nothing And myCheckBox5.Checked Then
            '    lSql = lSql & ";Insert into UserBranchRights (ub_brcode,ub_usrcode,ub_filter,ub_merchantid,ub_updateby,ub_updatedt) Values (" &
            '        "'" & lBranchCode & "','" & usr_code.Text.Replace("'", "''") & "','" & WebLib.FilterCode & "','" & WebLib.MerchantID & "','" & WebLib.LoginUser & "',getdate())"
            'End If

            Try
                itrans = cn.BeginTransaction()
                cmd.Transaction = itrans
                cmd.CommandText = lSql
                cmd.ExecuteNonQuery()
                itrans.Commit()

            Catch Err As Exception
                Try
                    itrans.Rollback()

                Catch ex As Exception

                End Try
                lblMessage.Text = Err.Message
                Return False
                Exit For
            End Try
NextItem:
        Next

        Return True
    End Function

    Protected Sub rep_ItemDataBound(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.RepeaterItemEventArgs) Handles rep.ItemDataBound
        Dim drv As DataRowView
        drv = e.Item.DataItem

        Dim myCheckBox As CheckBox = e.Item.FindControl("chkfull")
        If Not myCheckBox Is Nothing Then
            'If drv.Row("ub_id").ToString.Trim <> "" Then
            '    myCheckBox.Checked = True
            'Else
            '    myCheckBox.Checked = False
            'End If
        End If
    End Sub

    Private Sub usr_matrixlevel_SelectedIndexChanged(sender As Object, e As EventArgs) Handles usr_matrixlevel.SelectedIndexChanged
        For Each item As ListItem In usr_matrixlevel.Items
            If item.Value = "L3" Then
                If item.Selected Then
                    trusr_region.Visible = True
                    usr_region.Items.Clear()
                    Call WebLib.setListItemsTable(usr_region, "te_name", "te_code", "mstrterritory", "te_name", "", "", "")
                Else
                    trusr_region.Visible = False
                    usr_region.Items.Clear()
                End If
            End If
            If item.Value = "L4" Then
                If item.Selected Then
                    trusr_state.Visible = True
                    usr_state.Items.Clear()
                    Call WebLib.setListItemsTable(usr_state, "state_name", "state_code", "mstrstate", "state_name", "", "", "")
                Else
                    trusr_state.Visible = False
                    usr_state.Items.Clear()
                End If
            End If
        Next
    End Sub

    Private Sub usr_isad_CheckedChanged(sender As Object, e As EventArgs) Handles usr_isad.CheckedChanged
        If usr_isad.Checked = True Then
            usr_password.Enabled = False
            RegularExpressionValidator.Enabled = False
            usr_password.CssClass.Replace("validate[required]", "").Trim()
        Else
            usr_password.Enabled = True
            RegularExpressionValidator.Enabled = True
            usr_password.CssClass = "validate[required]"
        End If
    End Sub

    Public Function savepageaccess1() As Boolean
        Dim cn As New OleDbConnection(connectionstring)
        Dim itrans As OleDbTransaction
        Dim cmd As New OleDbCommand()
        Dim counter As Integer = 0
        Dim lSql As String = ""

        Return True

        cn.Open()
        cmd.Connection = cn

        'lSql = "Delete from [UserBranchRights] where ub_filter='" & WebLib.FilterCode & "' and ub_usrcode='" & usr_code.Text.Replace("'", "''") & "'"

        Dim lusr_company As String = WebLib.LoginUserCompanySelected
        'Dim usr_companyList As List(Of String) = New List(Of String)()
        'For Each item As ListItem In usr_company.Items
        '    If item.Selected Then

        'lSql = lSql & ";Insert into UserBranchRights (ub_brcode,ub_usrcode,ub_filter,ub_merchantid,ub_updateby,ub_updatedt) Values (" &
        '            "'" & lusr_company & "','" & usr_code.Text.Replace("'", "''") & "','" & WebLib.FilterCode & "','" & WebLib.MerchantID & "','" & WebLib.LoginUser & "',getdate())"

        Try
            itrans = cn.BeginTransaction()
            cmd.Transaction = itrans
            cmd.CommandText = lSql
            cmd.ExecuteNonQuery()
            itrans.Commit()
        Catch Err As Exception
            Try
                itrans.Rollback()
            Catch ex As Exception
            End Try
            lblMessage.Text = Err.Message
            Return False
            'Exit For
        End Try
        '    End If
        'Next
        Return True
    End Function

End Class

