Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.OleDb
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls
Imports System.Web.Services
Imports System.Collections.Generic

Partial Public Class selectcustomer_list_class
    Inherits listpage
    'Generated by VI FEANDI SOFTLABS FORM GENERATOR (http://www.vifeandi.net) VER 2014.1
    Dim portaldb As String = ConfigurationManager.AppSettings("ConnStrDB") & "dbo."

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        _searchkeystr = "sm_code;Merchant code;S|sm_name;Merchant name;S|"
        listingpage = ""
        _FormsName = "Select a Customer"
        _connection = "Epicor"
        columnscount = "9"
        TableName = portaldb & "sysMerchant"
        DetailPage = "sysMerchant.aspx"
        IDPField = ""
        IDField = "sm_id"
        AppIDField = ""
        MerchantIDField = ""
        FilterField = ""
        Orderby = " order by sm_name "
        '_pagesize = 20
        APPCode = "GENERAL"
        AddRights = ""
        DelRights = ""
        ModRights = ""
        ViewRights = ""
        FullRights = ""
        NmSpace = "selectcustomer"
        pFieldNames = "sm_code,sm_name"
        pJoinFields = " inner join Customer on sysMerchant.sm_code = Customer.CustID and Customer.Company = '" & WebLib.LoginUserCompanySelected & "' "

        If Session("LoginUserMatrixLevel").ToString <> "" Then

            If Session("LoginUserMatrixLevel").ToString.Contains("L2") Then
                _searchfilter = " SalesRepCode = '" & WebLib.LoginUser & "' "
            End If
            If Session("LoginUserMatrixLevel").ToString.Contains("L3") Then
                If (_searchfilter & "").Trim <> "" Then
                    _searchfilter = _searchfilter & " or "
                End If
                _searchfilter = _searchfilter & " sm_code in ( select distinct sa_merchantid from " & portaldb & "sales where sa_shiptoterritory in ( " &
                                " select tl_territorycode from " & portaldb & "mstrterritorylist where tl_regioncode IN ( " &
                                " SELECT ITEM FROM " & portaldb & "SplitString('" & Session("LoginUserRegion") & "', ',')))) "
            End If

            If Session("LoginUserMatrixLevel").ToString.Contains("L1") Then
                ' view all
                _searchfilter = ""
            End If
        End If

        btnback.Visible = False
        Call InitLoad()
    End Sub

    Protected Sub rep_ItemCommand(ByVal source As Object, ByVal e As System.Web.UI.WebControls.RepeaterCommandEventArgs) Handles rep.ItemCommand
        If e.CommandName = "Select" Then
            Call SelectCustomer((e.CommandArgument))
        End If
    End Sub

    Protected Sub rep_ItemDataBound(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.RepeaterItemEventArgs) Handles rep.ItemDataBound

    End Sub

    Private Sub SelectCustomer(ByVal pCustCode As String)
        Try
            WebLib.MerchantID = pCustCode
            Dim obj As New RuntimeCustomer
            Call obj.getInfo(WebLib.MerchantID)
            WebLib.CustNum = obj.CustNum
            WebLib.CustName = obj.CustName
            WebLib.CustBranchID = ""
            WebLib.CustBranchName = ""
            WebLib.CustBranchNum = "0"

            obj = Nothing

        Catch ex As Exception
            WebLib.ShowMessagePage(Response, "There Is an error logging into the selected customer instance", "login.aspx")
        End Try
    End Sub



    <WebMethod(EnableSession:=True)>
    Public Shared Function GetCustomers() As List(Of ListItem)
        Dim query As String = ""
        Dim queryfilter2 As String = ""
        Dim queryfilter3 As String = ""

        Dim queryselect As String = ""
        Dim queryselect2 As String = ""
        Dim queryfrom As String = ""
        Dim queryfilter As String = ""


        If WebLib.LoginUserMatrixLevel = "" Or WebLib.LoginUserMatrixLevel.ToString.Contains("L1") Then
            queryselect = "SELECT sm_code,sm_name, '' as custundermatrixlevel "

            queryfrom = "FROM " & ConfigurationManager.AppSettings("ConnStrDB") & "dbo." & "sysMerchant " &
                        " inner join Customer on sysMerchant.sm_code = Customer.CustID and Customer.Company = '" & WebLib.LoginUserCompanySelected & "' "
        Else
            ''If HttpContext.Current.Session("LoginUserMatrixLevel").ToString.Contains("L1") Then
            ''    ' view all
            ''End If
            'queryselect = "SELECT sm_code,sm_name "
            'queryfrom = "FROM " & ConfigurationManager.AppSettings("ConnStrDB") & "dbo." & "sysMerchant " &
            '            " inner join Customer on sysMerchant.sm_code = Customer.CustID and Customer.Company = '" & WebLib.LoginUserCompanySelected & "' "
            'If HttpContext.Current.Session("LoginUserMatrixLevel").ToString.Contains("L2") Then
            '    queryselect2 = ", 'L2' as custundermatrixlevel "
            '    queryfilter2 = " where SalesRepCode = '" & WebLib.LoginUser & "' "
            'End If
            'If HttpContext.Current.Session("LoginUserMatrixLevel").ToString.Contains("L3") Then
            '    If (queryfilter2 & "").Trim <> "" Then
            '        queryfilter3 = queryfilter3 & " union " & queryselect & ", 'L3' as custundermatrixlevel " & queryfrom & " where "
            '    Else
            '        queryfilter3 = queryfilter3 & " where "
            '    End If
            '    queryfilter3 = queryfilter3 & " sm_code in ( select distinct sa_merchantid from " & ConfigurationManager.AppSettings("ConnStrDB") & "dbo." & "sales where sa_shiptoterritory in ( " & backend.getTerritoryIDfromLoginUser() & ")) "
            '    If (queryfilter2 & "").Trim <> "" Then
            '        queryfilter3 = queryfilter3 & " and sm_code not in (select sm_code " & queryfrom & " " & queryfilter2 & " ) "
            '    End If
            'End If


            For Each item As String In WebLib.LoginUserMatrixLevel.ToString.Split(",")
                If (query & "").Trim <> "" Then
                    query = query & " union "
                End If

                query = query & "select sm_code,sm_name, '" & item & "' as custundermatrixlevel " &
                        "FROM " & ConfigurationManager.AppSettings("ConnStrDB") & "dbo." & "sysMerchant " &
                        "inner join Customer on sysMerchant.sm_code = Customer.CustID and Customer.Company = '" & WebLib.LoginUserCompanySelected & "' " &
                        "where sm_id is not null and " & backend.getMatrixValidation(item, "selCust")
                '"where sm_id is not null and " & WebLib.GetValue("mstrmatrixlevel", "ml_validation", "ml_code", "'" & item & "'", "", "", " ml_key = 'selCust' ")
            Next

        End If

        query = query & queryselect & queryselect2 & queryfrom & queryfilter2 & queryfilter3

        query = "select * from (" &
                "    select ROW_NUMBER() OVER(Partition by sm_code ORDER BY sm_code) AS ROW_NUMBER, * " &
                "    from (" & query & ") x " &
                "group by sm_code,sm_name,custundermatrixlevel) y " &
                "where row_number = '1' " &
                "order by sm_name"


        Dim cn As New Odbc.OdbcConnection(WebLib.ConnEpicor)
        Dim cmd As New Odbc.OdbcCommand()
        Dim ad As New Odbc.OdbcDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow

        cn.Open()
        cmd.CommandText = query
        cmd.Connection = cn
        ad.SelectCommand = cmd
        ad.Fill(ds, "datarecords")

        Dim customers As New List(Of ListItem)()

        If WebLib.MerchantID <> "" Then
            customers.Add(New ListItem() With {.Value = WebLib.MerchantID & "", .Text = WebLib.CustName & "", .Selected = True})
        End If

        customers.Add(New ListItem() With {.Value = "", .Text = "Please Select"})

        For Each dr In ds.Tables("datarecords").Rows
            customers.Add(New ListItem() With {
                    .Value = dr("sm_code").ToString.Trim & ";" & dr("custundermatrixlevel").ToString.Trim,
                    .Text = dr("sm_name").ToString.Trim & "" & "    " & ds.Tables("datarecords").Rows.Count})
        Next

        cn.Close()
        Return customers

    End Function


    <WebMethod()>
    Public Shared Function SelectCustomer2(ByVal pCustCode As String) As String '
        Try
            Dim CustCode() As String = Split(pCustCode & ";", ";")
            WebLib.MerchantID = CustCode(0).ToString
            WebLib.CustUnderLoginUserMatrixLevel = CustCode(1).ToString

            Dim obj As New RuntimeCustomer
            Call obj.getInfo(WebLib.MerchantID)
            WebLib.CustNum = obj.CustNum
            WebLib.CustName = obj.CustName
            WebLib.CustBranchID = ""
            WebLib.CustBranchName = ""
            WebLib.CustBranchNum = "0"

            obj = Nothing
            Return WebLib.MerchantID
        Catch ex As Exception
            'WebLib.ShowMessagePage(Response, "There Is an error logging into the selected customer instance", "login.aspx")
            Return WebLib.MerchantID
        End Try
    End Function

End Class

