<%@ Page Language="VB" AutoEventWireup="false" EnableViewState="True" CodeFile="selectcustomer.aspx.vb" Inherits="selectcustomer_list_class" %>

<%@ Register Src="UserControls/DatePicker.ascx" TagPrefix="uc" TagName="DatePicker" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <!--Generated by ViSoftLabs Forms Generator (http:// www.vifeandi.net)-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title><%=_formsname%></title>
    <!--#include File="topinitdetail.aspx"-->
    <!--#include File="topmobilecss.aspx"-->
    <script>
        $(function () {
            $("input[type=submit], button")
            .button()
            var div1 = $("#divnavi").accordion({ collapsible: false, heightStyle: "content", active: 0 });
            var div2 = $("#divsearch").accordion({ collapsible: false, heightStyle: "content", active: 0 });
            var div3 = $("#divdata");
            div2.show();
            div3.show();
        });
    </script>
    <!--#include File="topscriptdetail.aspx"-->
</head>
<body>
    <form id="frmform" runat="server">
        <!--#include File="include/FormHeader1.aspx"-->

        <div class=" container-fluid bg-light" style="font-size: 1rem;">
            <div class="row listpage">
                <div class="col-md-2 bg-light ">
                    <div style="padding-top: 1em; display: none; font-size: 0.8rem; text-align: left;">
                        <div class="card">
                            <div class="card-header">
                                <h6>
                                    <a data-toggle="collapse" href="#opt" aria-expanded="false" aria-controls="opt">
                                        <i class="fa fa-ellipsis-v"></i> Options Menu
                                    </a>
                                </h6>
                            </div>
                            <div id="opt" class="collapse show">
                                <div class="card-body">
                                    <asp:Button ID="btnadd" CssClass="btn btn-sm btn-info w-100" Text="Save Details" runat="server" OnClick="AddEvent" />
                                    <br />
                                    <hr />
                                    <asp:Button ID="btnback" CssClass="btn btn-sm btn-info w-100" Text="Back to Listing" runat="server" OnClick="backpage" CausesValidation="false" OnClientClick="jQuery('#frmform').validationEngine('detach');" />
                                    <br />
                                </div>
                                <div class="card-footer">
                                    <b>Messages:</b><br />
                                    <asp:Label ID="lblMessage" runat="server" class="cssrequired"></asp:Label>
                                    <br />
                                    <br />
                                </div>
                            </div>

                        </div>
                    </div>
                    <br class="adddet" />
                    <div style="text-align: left; font-size: 0.8rem;">
                        <div class="card">
                            <div class="card-header">
                                <h6>
                                    <a data-toggle="collapse" href="#search" aria-expanded="false" aria-controls="search">
                                        <i class="fa fa-search-plus"></i> Search Menu
                                    </a>
                                </h6>
                            </div>
                            <div id="search" class="collapse show">
                                <div class="card-body">
                                    <div style="text-align: left">
                                        <b>Please enter search key:</b>
                                    </div>
                                    <br />
                                    <asp:TextBox placeholder="Search" ID="search_key1" runat="server" Columns="23" MaxLength="50" CssClass="form-control"></asp:TextBox><br />
                                    Search Field:<br />
                                    <asp:PlaceHolder ID="phSearchFields" runat="server"></asp:PlaceHolder>
                                    <hr class="cssdivider" width="100%" runat="server" id="hrdate" />
                                    <br />
                                    <uc:datepicker ID="uc_from" runat="server" AllowNull="false" PlaceHolder="From Date" />
                                    <uc:datepicker ID="uc_to" runat="server" AllowNull="false" PlaceHolder="To Date" />
                                    <asp:PlaceHolder ID="phSearchDate" runat="server"></asp:PlaceHolder>
                                    <asp:Button ID="btnSearch" CssClass="btn btn-sm btn-info w-100" Text="Search" runat="server" OnClick="SearchStr" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-10 bg-white">
                    <div style="padding-top: 1em;">
                        <div class="ui-widget-header alert p-1 form-fonts w-100  bg-header " role="alert" style="text-align: left; padding-left: 1em!important; margin-bottom: 1em!important">
                            <%=_formsname%>
                        </div>
                        <table id="table_listing" class="table table-borderless dt-responsive nowrap" width="100%" style="height: 100%;" cellpadding="2" cellspacing="1">
                            <thead>
                                <tr class="ui-widget-header" style="height: 25px">
                                    <th class="cssdetail"><b>No.</b></th>
                                    <th class="cssdetail">Merchant code</th>
                                    <th class="cssdetail">Merchant name</th>
                                    <th class="cssdetail">Expiry</th>
                                    <th class="cssdetail">Active ?</th>
                                    <th class="cssdetail">Create by</th>
                                    <th class="cssdetail">Create on</th>
                                    <th class="cssdetail">Last update by</th>
                                    <th class="cssdetail">Last update on</th>
                                </tr>
                            </thead>
                            <tbody>
                                <asp:Repeater ID="rep" runat="server" OnItemCommand="rep_ItemCommand">
                                    <ItemTemplate>
                                        <tr id="trRow" class="ui-widget-content" runat="server">
                                            <td align="center" class="cssdetail">
                                                <asp:Literal ID="litNo" runat="server" Text='<%# Container.ItemIndex + 1 %>'></asp:Literal>
                                            </td>
                                            <td class="cssdetail">
                                                <asp:Literal ID="litsm_code" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "sm_code")%>'></asp:Literal></td>
                                            <td class="cssdetail">
                                                <b>
                                                    <asp:LinkButton ID="LinkButton1" runat="server" CommandArgument='<%#DataBinder.Eval(Container.DataItem, "sm_code")%>' CommandName="Select">
                                                        <font style="text-decoration:none;color:blue">
                                                                <%#DataBinder.Eval(Container.DataItem, "sm_name")%></font>
                                                    </asp:LinkButton>
                                                </b>
                                            </td>
                                            <td class="cssdetail">
                                                <asp:Literal ID="litsm_expiry" runat="server" Text='<%#Weblib.Formatthedate(DataBinder.Eval(Container.DataItem, "sm_expiry"))%>'></asp:Literal></td>
                                            <td class="cssdetail">
                                                <asp:Literal ID="litsm_active" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "sm_active")%>'></asp:Literal></td>
                                            <td class="cssdetail">
                                                <asp:Literal ID="litsm_createby" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "sm_createby")%>'></asp:Literal></td>
                                            <td class="cssdetail">
                                                <asp:Literal ID="litsm_createdt" runat="server" Text='<%#Weblib.Formatthedate(DataBinder.Eval(Container.DataItem, "sm_createdt"))%>'></asp:Literal></td>
                                            <td class="cssdetail">
                                                <asp:Literal ID="litsm_updateby" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "sm_updateby")%>'></asp:Literal></td>
                                            <td class="cssdetail">
                                                <asp:Literal ID="litsm_updatedt" runat="server" Text='<%#Weblib.Formatthedate(DataBinder.Eval(Container.DataItem, "sm_updatedt"))%>'></asp:Literal></td>
                                        </tr>
                                    </ItemTemplate>
                                </asp:Repeater>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <input type="hidden" runat="server" id="rid" name="rid" />
        <input type="hidden" runat="server" id="bid" name="bid" />
        <hr width="100%" />
        <!--#include File="include/FormFooter1.aspx"-->
    </form>
    <!--#include File="include/footerscript.aspx"-->

    <script type="text/javascript">
        $(document).ready(function () {
            $('#table_listing').DataTable({
                responsive: true,
                "info": true,
                "bFilter": false
            });
        });
    </script>
</body>
</html>

