Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.OleDb
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls
Partial Public Class so_class
    Inherits detailspage
    'Generated by VI SOFTLABS FORM GENERATOR (http://www.vifeandi.net) VER 2014.1
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        listingpage = "solist.aspx"
        _FormsName = "Sales Order Enquiry"
        TableName = "pub.orderhed"
        NmSpace = "salesorder"
        IDPField = ""
        IDField = "ordernum"
        APPIDField = ""
        MerchantIDField = ""
        FilterField = ""
        APPCode = "SALES"
        '                lAdditionalParam = ",Name as param1,Address1 as param2,Address2 as param3, Address3 as param4,City as param5,State as param6,Zip as param7,Country as param8,'' as param9,'' as param10"
        rwshipto4.visible = False
        sa_shiptocode.AdditioanalParam = "sa_shiptoname|sa_shiptoadd1|sa_shiptoadd2|sa_shiptoadd3|sa_shiptocity|sa_shiptostate|sa_shiptopostcode|sa_shiptocountry"
        If SOSettings.InitRuntimeObject = False Then
            WebLib.ShowMessagePage(response, "Error in Sales Order Initialization", "main.aspx")
        End If

        If (weblib.CustNum & "").trim = "" Then
            If (request("de") & "") = "7" And weblib.isstaff = True Then


            Else

                Weblib.ShowMEssagePAge(response, "You are required to select a customer instance", "main.aspx")
            End If

        End If


        If Page.IsPostBack = False Then
            lblstatus.text = " - Not Available -"
            lblapproved.text = " - Not Available -"
            '            If (Weblib.MerchantID & "").trim <> "" Then
            sa_custcode.text = Weblib.MerchantID
            sa_custcode.enabled = False
            '        End If
            Call WebLib.setListItemsTable(sa_shiptocountry, "country_name", "country_code", "mstrcountry", "country_name", "", "", "country_filter")
            '            Call WebLib.setListItemsTable(sa_shiptoterritory, "te_name", "te_code", "mstrterritory", "te_name", "", "", "te_filter")
            Call WebLib.setListItemsTable(sa_custsmp, "sp_name", "sp_id", "salesperson", "sp_name", "", "sp_merchantid", "sp_filter")
            Call WebLib.setListItemsTable(sa_shiptostate, "state_name", "state_code", "mstrstate", "state_name", "", "", "")


            Call showdate()
            Call loadcustomerdata(Weblib.MerchantID)

        End If



        Call initLoad()

    End Sub
    Private Sub loadcustomerdata(ByVal pCustCode As String)
        If pCustCode.trim = "" Then
            Exit Sub
        End If

        Dim obj As New RuntimeCustomer
        Call obj.getinfo(pCustCode)

        sa_soldtoname.text = obj.CustName
        sa_soldtoadd1.text = obj.Address1
        sa_soldtoadd2.text = obj.Address2
        sa_soldtoadd3.text = obj.Address3
        sa_soldtoadd4.text = ""
        sa_soldtocity.text = obj.City
        sa_soldtostate.text = obj.State
        sa_soldtopostcode.text = obj.PostCode
        obj = Nothing
    End Sub
    Private Function CutOfftimereach() As Boolean
        Dim startDate As Date = Date.Now
        Dim endDate As Date = System.DateTime.Today.AddHours(weblib.GetTime(SOSettings.OrderCutOffTime, "hour"))  'add 3 days to startDate
        endDate = endDate.AddMinutes(weblib.GetTime(SOSettings.OrderCutOffTime, "minute"))
        Dim timeSpan As TimeSpan = endDate.Subtract(startDate)

        If timeSpan.hours * 60 + timeSpan.minutes > 0 Then
            Return False
        Else
            Return True
        End If

    End Function
    Private Function getOrderDate() As Date
        If CutOfftimereach() = False Then
            Return datetime.today
        Else
            If dateadd("d", 1, datetime.today).DayOfWeek.ToString().tolower = "sunday" Then
                Return dateadd("d", 2, datetime.today)
            Else
                Return dateadd("d", 1, datetime.today)
            End If
        End If

    End Function
    Private Sub showdate()

        lblorderdate.text = Weblib.Formatthedate(getOrderDate)
        sa_needdate.value = Weblib.Formatthedate(dateadd("d", SOSettings.NeedDateMinDays, getorderdate))

    End Sub
    Private Function ValidateForm()
        lblmessage.text = ""

        If weblib.MerchantID.trim = "" Then
            lblmessage.text = Weblib.getAlertMessageStyle("Merchant ID is Mandatory")
            Return False
            Exit Function
        End If

        If sa_custcode.text.trim = "" Then
            lblmessage.text = Weblib.getAlertMessageStyle("Customer code is Mandatory")
            Return False
            Exit Function
        End If

        If sa_pono.text.trim = "" Then
            lblmessage.text = Weblib.getAlertMessageStyle("P/O Number is Mandatory")
            Return False
            Exit Function
        End If

        If (sa_needdate.value).trim = "" Then
            lblmessage.text = Weblib.getAlertMessageStyle("Need date is Mandatory")
            Return False
            Exit Function
        End If

        If sa_destinationcode.text.trim = "" Then
            lblmessage.text = Weblib.getAlertMessageStyle("Destination code is Mandatory")
            Return False
            Exit Function
        End If

        If sa_shiptoname.text.trim = "" Then
            lblmessage.text = Weblib.getAlertMessageStyle("Ship to name is Mandatory")
            Return False
            Exit Function
        End If

        If sa_shiptoadd1.text.trim = "" Then
            lblmessage.text = Weblib.getAlertMessageStyle("Ship to address 1 is Mandatory")
            Return False
            Exit Function
        End If

        '        If sa_shiptoterritory.selectedindex < 0 Then
        'lblmessage.text = Weblib.getAlertMessageStyle("Ship to territory is Mandatory")
        'Return False
        'Exit Function
        'End If

        If sa_shiptostate.selectedindex < 0 Then
            lblmessage.text = Weblib.getAlertMessageStyle("Ship to state is Mandatory")
            Return False
            Exit Function
        End If

        If datediff("d", sa_needdate.datevalue, getOrderDate()) > 0 Then
            lblmessage.text = Weblib.getAlertMessageStyle("Invalid Need Date")
            Return False
            Exit Function
        End If

        If sa_needdate.datevalue.DayOfWeek.ToString().tolower = "sunday" Then
            lblmessage.text = Weblib.getAlertMessageStyle("Need date cannot be a Sunday")
            Return False
            Exit Function
        End If

        If datediff("d", sa_needdate.datevalue, dateadd("d", SOSettings.NeedDateMinDays, getOrderDate())) > 0 Then
            lblmessage.text = Weblib.getAlertMessageStyle("Earliest Need Date : " & Weblib.formatthedate(dateadd("d", SOSettings.NeedDateMinDays, getOrderDate())))
            Return False
            Exit Function
        End If

        'Max Date
        If isnumeric(SOSettings.NeedDateMaxDays) = True Then
            If CLng(SOSettings.NeedDateMaxDays) <> 0 Then
                If datediff("d", sa_needdate.datevalue, dateadd("d", SOSettings.NeedDateMaxDays, getOrderDate())) < 0 Then
                    lblmessage.text = Weblib.getAlertMessageStyle("Latest Need Date : " & Weblib.formatthedate(dateadd("d", SOSettings.NeedDateMaxDays, getOrderDate())))
                    Return False
                    Exit Function
                End If
            End If
        End If

        Dim lstate As String = ""

        Dim objdest As New RuntimeDestinationCode
        If objdest.getinfo(sa_destinationcode.text) = False Then
            lblmessage.text = Weblib.getAlertMessageStyle("Destination code cannot be validated")

            Return False
        Else
            sa_destinationcode.textdesc = objdest.Description
            lstate = objdest.Key3

        End If
        objdest = Nothing
        If sa_destinationcode.textdesc.trim = "" Then
            lblmessage.text = Weblib.getAlertMessageStyle("Destination code description cannot be empty")
            Return False
            Exit Function
        End If


        '       lstate = Weblib.GetValueClear("mstrdestination", "de_state", "de_code", "'" & sa_destinationcode.text.trim & "'")


        Dim lshiptostate As String = ""
        If sa_shiptostate.selectedindex < 0 Then
            lshiptostate = ""
        Else
            lshiptostate = sa_shiptostate.SelectedItem.value
        End If


        If lstate.Trim <> lshiptostate.Trim Then
            lblmessage.text = Weblib.getAlertMessageStyle("Ship to state and destination code state does not match")
            Return False
            Exit Function
        End If



        Return True
    End Function
    Public Overrides Function LoadData() As Boolean
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow
        Dim templi As ListItem
        If isnumeric(rid.value) = False Then
            bid.value = ""
            Call loadsalesitem()

            Exit Function
        End If

        Try
            cmd.CommandText = "Select * from sales where sa_id=" & rid.value
            cmd.Connection = cn
            ad.SelectCommand = cmd
            ad.Fill(ds, "datarecords")
            For Each dr In ds.Tables("datarecords").Rows
                counter = counter + 1
                litcreateon.text = dr("sa_createdt") & ""
                bid.value = dr("sa_uid") & ""
                sa_custcode.text = dr("sa_custcode") & ""
                sa_pono.text = dr("sa_pono") & ""
                sa_needdate.Textdmy = Weblib.Formatthedate(dr("sa_needdate"))
                sa_shiptocode.text = dr("sa_shiptocode") & ""

                lblorderdate.text = Weblib.Formatthedate(dr("sa_createdt"))
                sa_destinationcode.text = dr("sa_destinationcode") & ""
                sa_destinationcode.textdesc = dr("sa_destinationdesc") & ""

                sa_soldtoname.text = dr("sa_soldtoname") & ""
                sa_soldtoadd1.text = dr("sa_soldtoadd1") & ""
                sa_soldtoadd2.text = dr("sa_soldtoadd2") & ""
                sa_soldtoadd3.text = dr("sa_soldtoadd3") & ""
                sa_soldtoadd4.text = dr("sa_soldtoadd4") & ""
                sa_soldtocity.text = dr("sa_soldtocity") & ""
                sa_soldtostate.text = dr("sa_soldtostate") & ""
                sa_soldtopostcode.text = dr("sa_soldtopostcode") & ""
                sa_shiptoname.text = dr("sa_shiptoname") & ""
                sa_shiptoadd1.text = dr("sa_shiptoadd1") & ""
                sa_shiptoadd2.text = dr("sa_shiptoadd2") & ""
                sa_shiptoadd3.text = dr("sa_shiptoadd3") & ""
                sa_shiptoadd4.text = dr("sa_shiptoadd4") & ""
                sa_shiptocity.text = dr("sa_shiptocity") & ""


                templi = sa_shiptostate.Items.FindByText(dr("sa_shiptostate") & "")
                sa_shiptostate.SelectedIndex = sa_shiptostate.Items.IndexOf(templi)

                '                sa_shiptostate.text = dr("sa_shiptostate") & ""




                sa_shiptopostcode.text = dr("sa_shiptopostcode") & ""
                templi = sa_shiptocountry.Items.FindByValue(dr("sa_shiptocountry") & "")
                sa_shiptocountry.SelectedIndex = sa_shiptocountry.Items.IndexOf(templi)
                '               templi = sa_shiptoterritory.Items.FindByValue(dr("sa_shiptoterritory") & "")
                '                sa_shiptoterritory.SelectedIndex = sa_shiptoterritory.Items.IndexOf(templi)
                templi = sa_custsmp.Items.FindByValue(dr("sa_custsmp") & "")
                sa_custsmp.SelectedIndex = sa_custsmp.Items.IndexOf(templi)
                sa_pricingremarks.text = dr("sa_pricingremarks") & ""
                sa_deliveryremarks.text = dr("sa_deliveryremarks") & ""
                litcreateby.text = dr("sa_createby") & ""
                litupdateby.text = dr("sa_updateby") & ""
                litupdateon.text = dr("sa_updatedt") & ""

                lblstatus.text = dr("sa_status") & ""
                If (dr("sa_approval") & "") = "Y" Then
                    lblapproved.text = "<font color=""red"">Approval Required</font>"
                Else
                    lblapproved.text = "<font color=""blue"">No submission approval required</font>"
                End If

                If (dr("sa_approved") & "") = "Y" Then
                    lblapproved.text = "<font color=""blue"">Approved on " & dr("sa_approveddt") & "</font>"
                End If
                If (dr("sa_reject") & "") = "Y" Then
                    lblapproved.text = "<font color=""red"">Rejected on " & dr("sa_rejectdt") & "</font>"
                    lblapproveremarks.text = dr("sa_rejectreason") & ""
                End If

                If dr("sa_status").ToString.ToLower <> "pending submission" Then
                    btnsubmit.visible = False
                    btnsave.visible = False
                    cansave.value = "N"
                Else
                    btnsubmit.visible = True
                End If

                Exit For


            Next
            cn.Close()
            cmd.Dispose()
            cn.Dispose()

            Call loadsalesitem()

        Catch ex As Exception
            lblmessage.text = ex.Message
        End Try
    End Function

    Public Function autoapprove() As Boolean


        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow

        Try
            cn.open()
            cmd.CommandText = "Update sales set sa_approved='Y',sa_approveddt=getdate() where isnull(sa_approval,'')='' and sa_id=" & rid.value
            cmd.Connection = cn
            cmd.ExecuteNonQuery()

            cn.Close()
            cmd.Dispose()
            cn.Dispose()

            Return True


        Catch ex As Exception
            Return False
            lblmessage.text = ex.Message
        End Try


    End Function

    Public Sub submitorder(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Dim insertfields, insertvalues As String
        Dim ldocno As String = ""
        insertfields = ""
        insertvalues = ""
        If ValidateForm() = False Then
            Exit Sub
        End If
        Try
            If rid.value = "" Then

                lblmessage.text = "This order cannot be submitted"

            Else
                insertvalues = insertvalues & "sa_status='Submitted'"
                insertvalues = insertvalues & ",sa_submitby='" & weblib.LoginUser.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_submitdt=getdate()"

            End If

            If savedata(insertfields, insertvalues) = True Then
                If autoapprove() = False Then
                    '                    Call gotoback()
                    response.redirect("postpage.aspx?NextPage=Sales.aspx&ga=" & rid.value & "&ba=" & bid.value & "&msg=" & "Error submitting. Please email administrator")


                Else
                    Call gotoback()

                End If

            End If



        Catch Err As Exception
            lblmessage.text = Err.message
        Finally

        End Try
    End Sub
    Public Sub savepage(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Dim insertfields, insertvalues As String
        Dim ldocno As String = ""
        Dim lapprovalneeded As String = ""
        insertfields = ""
        insertvalues = ""

        If ValidateForm() = False Then
            Exit Sub
        End If
        Dim lsa_shiptocountry As String = ""
        If sa_shiptocountry.selectedindex < 0 Then
            lsa_shiptocountry = ""
        Else
            lsa_shiptocountry = sa_shiptocountry.SelectedItem.Value
        End If

        Dim lshiptostate As String = ""
        If sa_shiptostate.selectedindex < 0 Then
            lshiptostate = ""
        Else
            lshiptostate = sa_shiptostate.SelectedItem.text
        End If

        Dim lsa_shiptoterritory As String = ""
        '        If sa_shiptoterritory.selectedindex < 0 Then
        ' lsa_shiptoterritory = ""
        ' Else
        ' lsa_shiptoterritory = sa_shiptoterritory.SelectedItem.Value
        ' End If
        Dim lsa_custsmp As String = ""
        If sa_custsmp.selectedindex < 0 Then
            lsa_custsmp = ""
        Else
            lsa_custsmp = sa_custsmp.SelectedItem.Value
        End If


        Dim objdest As New RuntimeDestinationCode
        If objdest.getinfo(sa_destinationcode.text) = False Then
            lblmessage.text = Weblib.getAlertMessageStyle("Destination code cannot be validated")
            Exit Sub
        Else
            lsa_shiptoterritory = objdest.Key3
        End If
        objdest = Nothing


        Try
            If rid.value = "" Then

                If bid.value.trim <> "" Then
                    lblmessage.text = "Duplicate Saved Detected. Please retry."
                    Exit Sub
                End If

                ldocno = WebLib.GetDocNo("sales", "sa_uid", "SALES")

                If ldocno.Trim = "" Then
                    lblmessage.text = "Invalid Unique Identifier"
                    Exit Sub
                End If

                insertfields = insertfields & "sa_merchantid"
                insertvalues = insertvalues & "'" & weblib.MerchantID.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_filter"
                insertvalues = insertvalues & ",'" & weblib.FilterCode.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_branchid"
                insertvalues = insertvalues & "," & weblib.Branchid & ""
                insertfields = insertfields & ",sa_uid"
                insertvalues = insertvalues & ",'" & ldocno & "'"

                insertfields = insertfields & ",sa_orderdt"
                insertvalues = insertvalues & ",'" & Weblib.formatthedate(getOrderDate()) & "'"


                insertfields = insertfields & ",sa_createdt"
                insertvalues = insertvalues & ",getdate()"
                insertfields = insertfields & ",sa_custcode"
                insertvalues = insertvalues & ",'" & sa_custcode.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_pono"
                insertvalues = insertvalues & ",'" & sa_pono.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_needdate"
                insertvalues = insertvalues & ",'" & weblib.formatthedate(sa_needdate.datevalue) & "'"
                insertfields = insertfields & ",sa_shiptocode"
                insertvalues = insertvalues & ",'" & sa_shiptocode.text.replace("'", "''") & "'"

                insertfields = insertfields & ",sa_destinationcode"
                insertvalues = insertvalues & ",'" & sa_destinationcode.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_destinationdesc"
                insertvalues = insertvalues & ",'" & sa_destinationcode.textdesc.replace("'", "''") & "'"

                insertfields = insertfields & ",sa_soldtoname"
                insertvalues = insertvalues & ",'" & sa_soldtoname.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_soldtoadd1"
                insertvalues = insertvalues & ",'" & sa_soldtoadd1.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_soldtoadd2"
                insertvalues = insertvalues & ",'" & sa_soldtoadd2.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_soldtoadd3"
                insertvalues = insertvalues & ",'" & sa_soldtoadd3.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_soldtoadd4"
                insertvalues = insertvalues & ",'" & sa_soldtoadd4.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_soldtocity"
                insertvalues = insertvalues & ",'" & sa_soldtocity.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_soldtostate"
                insertvalues = insertvalues & ",'" & sa_soldtostate.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_soldtopostcode"
                insertvalues = insertvalues & ",'" & sa_soldtopostcode.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_shiptoname"
                insertvalues = insertvalues & ",'" & sa_shiptoname.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_shiptoadd1"
                insertvalues = insertvalues & ",'" & sa_shiptoadd1.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_shiptoadd2"
                insertvalues = insertvalues & ",'" & sa_shiptoadd2.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_shiptoadd3"
                insertvalues = insertvalues & ",'" & sa_shiptoadd3.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_shiptoadd4"
                insertvalues = insertvalues & ",'" & sa_shiptoadd4.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_shiptocity"
                insertvalues = insertvalues & ",'" & sa_shiptocity.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_shiptostate"
                insertvalues = insertvalues & ",'" & lshiptostate & "'"
                insertfields = insertfields & ",sa_shiptopostcode"
                insertvalues = insertvalues & ",'" & sa_shiptopostcode.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_shiptocountry"
                insertvalues = insertvalues & ",'" & lsa_shiptocountry & "'"
                insertfields = insertfields & ",sa_shiptoterritory"
                insertvalues = insertvalues & ",'" & lsa_shiptoterritory & "'"
                insertfields = insertfields & ",sa_custsmp"
                insertvalues = insertvalues & ",'" & lsa_custsmp & "'"
                insertfields = insertfields & ",sa_pricingremarks"
                insertvalues = insertvalues & ",'" & sa_pricingremarks.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_deliveryremarks"
                insertvalues = insertvalues & ",'" & sa_deliveryremarks.text.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_status"
                insertvalues = insertvalues & ",'Pending Submission'"
                insertfields = insertfields & ",sa_createby"
                insertvalues = insertvalues & ",'" & weblib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_updateby"
                insertvalues = insertvalues & ",'" & weblib.LoginUser.replace("'", "''") & "'"
                insertfields = insertfields & ",sa_updatedt"
                insertvalues = insertvalues & ",getdate()"


                If sa_pricingremarks.text.trim <> "" Then
                    insertfields = insertfields & ",sa_approvalremarks"
                    insertvalues = insertvalues & ",'Pricing Remarks'"
                    insertfields = insertfields & ",sa_approval"
                    insertvalues = insertvalues & ",'Y'"
                    lapprovalneeded = "Y"
                Else
                    insertfields = insertfields & ",sa_approvalremarks"
                    insertvalues = insertvalues & ",'Auto Approved'"
                    insertfields = insertfields & ",sa_approval"
                    insertvalues = insertvalues & ",''"
                    lapprovalneeded = "N"

                End If

            Else

                If bid.value.trim = "" Then
                    lblmessage.text = "Discrepancy in Order. Please retry."
                    Exit Sub
                End If


                insertvalues = insertvalues & "sa_custcode='" & sa_custcode.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_pono='" & sa_pono.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_needdate='" & weblib.formatthedate(sa_needdate.datevalue) & "'"
                insertvalues = insertvalues & ",sa_orderdt='" & Weblib.Formatthedate(getOrderDate()) & "'"

                insertvalues = insertvalues & ",sa_shiptocode='" & sa_shiptocode.text.replace("'", "''") & "'"

                insertvalues = insertvalues & ",sa_destinationcode='" & sa_destinationcode.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_destinationdesc='" & sa_destinationcode.textdesc.replace("'", "''") & "'"

                insertvalues = insertvalues & ",sa_soldtoname='" & sa_soldtoname.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_soldtoadd1='" & sa_soldtoadd1.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_soldtoadd2='" & sa_soldtoadd2.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_soldtoadd3='" & sa_soldtoadd3.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_soldtoadd4='" & sa_soldtoadd4.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_soldtocity='" & sa_soldtocity.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_soldtostate='" & sa_soldtostate.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_soldtopostcode='" & sa_soldtopostcode.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_shiptoname='" & sa_shiptoname.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_shiptoadd1='" & sa_shiptoadd1.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_shiptoadd2='" & sa_shiptoadd2.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_shiptoadd3='" & sa_shiptoadd3.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_shiptoadd4='" & sa_shiptoadd4.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_shiptocity='" & sa_shiptocity.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_shiptostate='" & lshiptostate & "'"
                insertvalues = insertvalues & ",sa_shiptopostcode='" & sa_shiptopostcode.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_shiptocountry='" & lsa_shiptocountry & "'"
                insertvalues = insertvalues & ",sa_shiptoterritory='" & lsa_shiptoterritory & "'"
                insertvalues = insertvalues & ",sa_custsmp='" & lsa_custsmp & "'"
                insertvalues = insertvalues & ",sa_pricingremarks='" & sa_pricingremarks.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_deliveryremarks='" & sa_deliveryremarks.text.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_updateby='" & weblib.LoginUser.replace("'", "''") & "'"
                insertvalues = insertvalues & ",sa_updatedt=getdate()"

                If sa_pricingremarks.text.trim <> "" Then
                    insertvalues = insertvalues & ",sa_approvalremarks='Pricing Remarks'"
                    insertvalues = insertvalues & ",sa_approval='Y'"
                    lapprovalneeded = "Y"

                Else
                    insertvalues = insertvalues & ",sa_approvalremarks=''"
                    insertvalues = insertvalues & ",sa_approval=''"
                    lapprovalneeded = "N"

                End If


            End If

            If savedata(insertfields, insertvalues) = True Then

                If rid.value = "" Then
                    bid.value = ldocno
                    rid.value = Weblib.GetValue("Sales", "sa_id", "sa_uid", "'" & bid.value & "'", "sa_merchantid", "sa_filter")
                    lblmessage.text = ""
                    Call SaveItems(ldocno, True, lapprovalneeded)
                    '                    Call LoadData()
                    response.redirect("postpage.aspx?NextPage=Sales.aspx&ga=" & rid.value & "&ba=" & bid.value & "&msg=" & lblmessage.text)

                Else
                    lblmessage.text = ""
                    Call SaveItems(bid.value, True, lapprovalneeded)
                    'Call LoadData()
                    response.redirect("postpage.aspx?NextPage=Sales.aspx&ga=" & rid.value & "&ba=" & bid.value & "&msg=" & lblmessage.text)

                End If


                lblmessage.text = "<font color=""blue"">Record Saved</font>"

                '                Call gotoback()
            End If
        Catch Err As Exception
            lblmessage.text = Err.message
        Finally

        End Try
    End Sub
    Protected Sub rep_ItemDataBound(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.RepeaterItemEventArgs) Handles rep.ItemDataBound


        If e.Item.ItemType = ListItemType.Item Or e.Item.ItemType = ListItemType.AlternatingItem Then

            Dim myObject As Object = e.Item.FindControl("txtid")

            If Not myObject Is Nothing Then
                Dim myObject2 As Object = e.Item.FindControl("pt_part")
                If Not myObject2 Is Nothing Then
                    If isnumeric(myObject.Value) = True Then
                        myObject2.Visible = False
                    Else
                        myObject2.Visible = True

                    End If
                End If

                myObject2 = e.Item.FindControl("sd_qty")
                If Not myObject2 Is Nothing Then
                    If isnumeric(myObject.Value) = True Then
                        myObject2.Visible = False
                    Else
                        myObject2.Visible = True

                    End If
                End If
                myObject2 = e.Item.FindControl("sd_listprice")
                If Not myObject2 Is Nothing Then
                    If isnumeric(myObject.Value) = True Then
                        myObject2.Visible = False
                    Else
                        myObject2.Visible = False

                    End If
                End If
                myObject2 = e.Item.FindControl("sd_adhocdisc")
                If Not myObject2 Is Nothing Then
                    If isnumeric(myObject.Value) = True Then
                        myObject2.Visible = False
                    Else
                        myObject2.Visible = True

                    End If
                End If

                Dim lcansave As Boolean = True
                myObject2 = Page.FindControl("cansave")
                If Not myObject2 Is Nothing Then

                    If myObject2.value = "N" Then

                        lcansave = False
                    End If
                End If

                myObject2 = e.Item.FindControl("btndel")
                If Not myObject2 Is Nothing Then
                    If isnumeric(myObject.Value) = True And lcansave = True Then
                        myObject2.Visible = True
                    Else
                        myObject2.Visible = False

                    End If
                End If

                myObject2 = e.Item.FindControl("btnsave")
                If Not myObject2 Is Nothing Then

                    If bid.value.trim = "" Or lcansave = False Then
                        myObject2.Visible = False

                    Else

                        If isnumeric(myObject.Value) = True Then
                            myObject2.Visible = False
                        Else
                            myObject2.Visible = False  'True (Remove to ensure all save via "SAVE Button"

                        End If

                    End If
                End If

            End If


        End If
    End Sub
    Protected Sub rep_ItemCommand(ByVal source As Object, ByVal e As System.Web.UI.WebControls.RepeaterCommandEventArgs) Handles rep.ItemCommand
        If e.CommandName = "Del" Then
            Call DeleteItems(e.CommandArgument)
        End If
        If e.CommandName = "Save" Then
            Call SaveItems(bid.value)
            '            Call DeleteRec(e.CommandArgument)
        End If

    End Sub
    Private Sub loadsalesitem(Optional ByVal _p_searchkey As String = "")
        Dim cn As New OleDbConnection(connectionstring)

        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow

        If _p_searchkey.Trim <> "" Then
            _p_searchkey = " where " & _p_searchkey
        End If

        cn.Open()
        'cmd.CommandText = "Select salesdetails.*,pt_desc,pt_part,sd_linetotal = isnull(((isnull(sd_qty,0) * isnull(sd_listprice,0)) * ((100-isnull(sd_adhocdisc,0))/100)),0) from salesdetails left outer join product on sd_partno = product.pt_part and sd_merchantid= pt_merchantid and sd_filter = pt_filter where sd_uid='" & bid.value & "' and sd_merchantid='" & weblib.merchantid & "' and sd_filter='" & weblib.filtercode & "' and sd_branchid=" & Weblib.branchid & " order by sd_id asc"
        cmd.CommandText = "Select salesdetails.*,pt_desc,pt_part,sd_linetotal = isnull(((isnull(sd_qty,0) * isnull(sd_listprice,0)) * ((100-isnull(sd_adhocdisc,0))/100)),0) from salesdetails left outer join product on sd_partno = product.pt_part and sd_merchantid= pt_merchantid and sd_filter = pt_filter where sd_uid='" & bid.value & "' and sd_merchantid='" & weblib.merchantid & "' and sd_filter='" & weblib.filtercode & "' and sd_branchid=" & Weblib.branchid & " order by sd_id asc"

        cmd.Connection = cn
        ad.SelectCommand = cmd
        ad.Fill(ds, "datarecords")

        Dim dt As DataTable = ds.Tables("datarecords")
        Dim dv As New DataView(dt)

        If dt.Rows.Count = 0 Then
            dr = dt.NewRow()
            dt.Rows.Add(dr)
            btnsubmit.visible = False
            '        Else
            'If btnsubmit.visible <> False Then
            '   btnsubmit.visible = True
            'End If
        End If
        Dim pgitems As New PagedDataSource()
        pgitems.DataSource = dv

        rep.DataSource = pgitems
        rep.DataBind()

    End Sub
    Private Sub SaveItems(ByVal pUID As String, Optional ByVal isFirst As Boolean = False, Optional ByVal hasApproval As String = "")
        Dim cn As New OleDbConnection(connectionstring)
        Dim itrans As OleDbTransaction

        Dim cmd As New OleDbCommand()
        Dim counter As Integer = 0
        Dim lSql As String = ""
        Dim luid As String = pUID
        Dim lGotDiscount As Boolean = False
        If luid.Trim = "" Then
            lblmessage.text = "Invalid Unique Identifier"
            Exit Sub
        End If

        lblmessage.text = ""

        cn.Open()
        cmd.Connection = cn

        Dim item As RepeaterItem
        For Each item In rep.Items

            Dim myObject As Object = item.FindControl("txtid")
            If Not myObject Is Nothing Then
                If isnumeric(myObject.Value) = True Then
                    GoTo NextItem
                End If
            Else
                GoTo NextItem
            End If

            Dim lStockCode As String = ""
            Dim lAmt As String = ""
            Dim lSprice As String = ""
            Dim lDisc As String = ""
            Dim mtTextBox1 As Object = item.FindControl("pt_part")
            If Not mtTextBox1 Is Nothing Then
                lStockCode = mtTextBox1.Text
            End If

            If lStockCode.Trim = "" Then

                If isFirst = True Then
                    GoTo NextItem
                Else
                    lblmessage.text = "Part No. cannot be empty"
                    Exit Sub
                End If
            End If
            Dim mtTextBox2 As TextBox = item.FindControl("sd_Qty")
            If Not mtTextBox2 Is Nothing Then
                lAmt = mtTextBox2.Text

            End If
            If lAmt.Trim = "" Then

                If isFirst = True Then
                    GoTo NextItem
                Else
                    lblmessage.text = "Qty cannot be empty"
                    Exit Sub
                End If

            End If
            Dim mtTextBox3 As TextBox = item.FindControl("sd_listprice")
            If Not mtTextBox3 Is Nothing Then
                lSprice = mtTextBox3.Text
            End If
            If isnumeric(lSprice.Trim) = False Then
                lSprice = 0
                '                If isFirst = True Then
                'GoTo NextItem
                'Else
                '    lblmessage.text = "S/Price must be a valid number"
                '   Exit Sub
                'End If
            End If

            mtTextBox3 = item.FindControl("sd_adhocdisc")
            If Not mtTextBox3 Is Nothing Then
                lDisc = mtTextBox3.Text
            End If
            If isnumeric(lDisc.Trim) = False Then
                lDisc = 0
            End If

            Dim objproduct As New RuntimeProduct
            Dim luom As String = ""
            Dim lpartname As String = ""
            If objproduct.getProductInfo(lStockCode) = True Then
                luom = objproduct.PartUOM
                lpartname = objproduct.PartNAme
            Else
                GoTo nextitem
            End If
            objproduct = Nothing



            If isQtyValid(lstockcode, luom, lAmt) = False Then
                Exit Sub
            End If


            lSql = lSql & ";Insert into [salesdetails] (sd_uid,sd_partno,sd_partname,sd_listprice,sd_qty,sd_uom,sd_adhocdisc,sd_merchantid,sd_filter,sd_branchid,sd_createdt,sd_createby) Values (" & _
                "'" & luid & "','" & lStockCode & "','" & lpartname & "'," & lSprice & "," & lAmt & ",'" & luom & "'," & lDisc & ",'" & Weblib.Merchantid & "','" & weblib.filtercode & "'," & weblib.branchid & ",getdate(),'" & Weblib.LoginUser & "')"

            If CDbl(lDisc) > 0 Then
                lGotDiscount = True
            End If
NextItem:
        Next

        Try

            If lSql.Trim <> "" Then

                If lGotDiscount = True Then
                    lSql = lSql & ";Update sales set sa_approval='Y',sa_adhocdisc='Y' where sa_uid='" & luid & "'"
                Else
                    Dim ltemptemp As String = ""
                    If hasapproval = "Y" Then
                        ' dont need to anything
                    End If
                    If hasapproval = "N" Then
                        ltemptemp = ", sa_approval=''"
                        ' dont need to anything
                    End If



                    lSql = lSql & ";Update sales set sa_adhocdisc='' " & ltemptemp & " where sa_uid='" & luid & "'"

                End If
                itrans = cn.BeginTransaction()
                cmd.Transaction = itrans
                cmd.CommandText = lSql
                cmd.ExecuteNonQuery()
                itrans.Commit()
            End If
            '            If rid.value <> "" Then
            Call loadsalesitem()
            'End If
            '            response.redirect("saleslist.aspx")

        Catch Err As Exception
            Try
                itrans.Rollback()

            Catch ex As Exception

            End Try
            lblmessage.text = Err.Message
        End Try


    End Sub
    Private Sub DeleteItems(ByVal pID As String)
        Dim cn As New OleDbConnection(connectionstring)
        Dim itrans As OleDbTransaction

        Dim cmd As New OleDbCommand()
        Dim counter As Integer = 0
        Dim lSql As String = ""

        If bid.value.trim = "" Then
            lblmessage.text = "Invalid Unique Identifier"
            Exit Sub
        End If
        If isnumeric(pID) = False Then
            lblmessage.text = "Invalid Identifier"
            Exit Sub
        End If

        lblmessage.text = ""

        cn.Open()
        cmd.Connection = cn

        lSql = "Delete from SalesDetails where sd_id=" & pID & " and sd_uid='" & bid.value.trim & "' and sd_merchantid='" & weblib.Merchantid & "' and sd_filter='" & Weblib.FilterCode & "'"
        Try

            itrans = cn.BeginTransaction()
            cmd.Transaction = itrans
            cmd.CommandText = lSql
            cmd.ExecuteNonQuery()
            itrans.Commit()

            Call loadsalesitem()

        Catch Err As Exception
            Try
                itrans.Rollback()

            Catch ex As Exception

            End Try
            lblmessage.text = Err.Message
        End Try


    End Sub

    Public Function isQtyValid(ByVal _p_partno As String, ByVal _p_uom As String, ByVal _p_qty As String) As Boolean
        Dim cn As New OleDbConnection(connectionstring)
        Dim cmd As New OleDbCommand()
        Dim ad As New OleDb.OleDbDataAdapter()
        Dim ds As New DataSet()
        Dim counter As Integer = 0
        Dim dr As DataRow

        If isnumeric(_p_qty) = False Then
            lblmessage.text = "Invalid Qty"
            Return False
            Exit Function
        End If

        Try
            cmd.CommandText = "Select * from salesmax where sx_partcode='" & _p_partno & "' and sx_uom='" & _p_uom & "'"
            cmd.Connection = cn
            ad.SelectCommand = cmd
            ad.Fill(ds, "datarecords")
            For Each dr In ds.Tables("datarecords").Rows


                If CDbl(_p_qty) > CDbl(dr("sx_maxqty")) Then
                    lblmessage.text = "Invalid Item Qty. Max : " & dr("sx_maxqty") & " " & _p_uom
                    Return False
                    Exit Function
                End If

                If CDbl(_p_qty) < CDbl(dr("sx_minqty")) Then
                    lblmessage.text = "Invalid Item Qty. Min : " & dr("sx_minqty") & " " & _p_uom
                    Return False
                    Exit Function
                End If

                Exit For
            Next
            cn.Close()
            cmd.Dispose()
            cn.Dispose()

            Return True


        Catch ex As Exception
            Return False
            lblmessage.text = ex.Message
        End Try
    End Function

End Class

