Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.OleDb
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls
Partial Public Class testuiblock_class
    Inherits detailspage
    'Generated by VI FEANDI SOFTLABS FORM GENERATOR (http://www.vifeandi.net) VER 2014.1
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        listingpage = "mstrdestinationlist.aspx"
        _FormsName = "Masterfile : Destination Code"
        TableName = "mstrdestination"
        IDPField = ""
        IDField = "de_id"
        AppIDField = ""
        MerchantIDField = ""
        FilterField = "de_filter"
        APPCode = "SALES"
        AddRights = "MD0001"
        DelRights = "MD0003"
        ModRights = "MD0002"
        ViewRights = "MD0004"
        FullRights = ""
        NmSpace = "masdestc"
        If Page.IsPostBack = False Then


        End If
        Call InitLoad()
    End Sub
    Private Function ValidateForm()

    End Function
    Public Overrides Function LoadData() As Boolean


    End Function
    Public Sub savepage(ByVal sender As System.Object, ByVal e As System.EventArgs)
        Dim ScriptManager As ClientScriptManager = Page.ClientScript

        '        ScriptManager.RegisterStartupScript(Me.GetType(), "uniqueid" & System.Guid.NewGuid.ToString, "<script>$.blockUI({ css: {border: 'none', padding: '15px', backgroundColor: '#000', '-webkit-border-radius': '10px', '-moz-border-radius': '10px', opacity: .5, color: '#fff'} }); setTimeout($.unblockUI, 4000);</script>")
        ScriptManager.RegisterStartupScript(Me.GetType(), "uniqueid" & System.Guid.NewGuid.ToString, "<script>$.blockUI({css: {border: 'none', padding: '15px', backgroundColor: '#000', '-webkit-border-radius': '10px', '-moz-border-radius': '10px', opacity: .5, color: '#fff'},message: '<h1>Processing....Please wait...</h1>' });</script>")
        Dim counter As Integer = 0
        Dim abc As Integer
        For counter = 1 To 5000000
            abc = abc + 1
        Next
        '        ScriptManager.RegisterStartupScript(Me.GetType(), "uniqueid" & System.Guid.NewGuid.ToString, "<script>$.unblockUI();</script>")

    End Sub
End Class

